
    
<div class="sticky">

	<a href="prepschool" class="fancybox red-button">
	Get Prepared
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->
 
 


	<div id="main-content" role="main">
                        
  <div class="blue-bg clear">

		<section class="what-is">   

			<div class="wrapper">  

				<header>
					<h1 class="red">About the Preparedness Quiz</h1>                     
				</header>                                                                                        


			</div>  <!-- end wrapper -->            

			<div class="ribboncorners"></div>

		</section> <!-- end what-is -->           

		<div class="clear"></div>


	</div>

				<section class="about-quiz">
                
     <div class="box">
					
						<h1 class="large">
							<span>WHAT</span> 
							are the reasons you're motivated to increase your preparedness?
						</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>
							<div class="col">
							<h4 class="black">Question #1: What are you prepping for?</h4>
							<p>Until you can define the existing and possible threats you're preparing for, it's rather impossible to draft a quiz to tell you if you're ready for it.
							<br><br>Some people are preparing for job loss or continued inflation, while others are preparing for total economic collapse.  As you can imagine, preparations vary greatly based upon what possible threats you're preparing for.
							<br><br>This Quiz takes the middle ground, somewhat.  We're not including questions about nuclear/biological attacks, for example.  But know that in a grid down situation, you need to be worried about nearby and upwind nuclear power plants.
							<br><br>Some of the motivations that created this quiz are described in <a href="whyprepare">why we prepare</a>.
							<br>
							<i>Have you written out the reasons why you're a prepper?</i><br><br>
							<strong>To gauge your preparedness, take the quiz below!</strong>
							
											
							</p></div>
							<div class="col">
								<h4 class="black">Reasons you might become a prepper:</h4>
								<ul>
									<li>Develop Self Sufficiency Skills</li>
									<li>Job Loss / Bankruptcy</li>
									<li>House Fire / Tornado</li>
									<li>Area Flood / Earthquake / Other Disaster</li>
									<li>Drought / Crop Failures / Food Supply Disruption</li>
									<li>Sustained Power Outage</li>
									<li>Social Unrest / Riots</li>
									<li>Economic Collapse</li>
									<li>Hyperinflation</li>
									<li>Martial Law</li>
									<li>EMP</li>
									<li>Solar Flare/CME</li>
									<li>Nuclear Power Plant Meltdown</li>
									<li>Nuclear or Biological Warfare</li>
									<!--<li>Polar Shift</li> -->
									<li>Terrorist Attack</li>
									<li>Virus / Pandemic</li>
									<li>Zombie Apocalypse (just kidding!)</li>

								</ul>

							</div><!-- end col-->

						<div class="clear"></div>

						</div><!-- end speech -->

					</div>

				</section><!-- end about-quiz -->




	</div><!-- end main-content -->
