<article>

<header>
    <h1 class="red">Bill Still</h1>
     
</header>


	<p>
	Bill Still is a former newspaper editor and publisher, best-selling author and award-winning documentary writer/director.</p>
	<p>Bill has written for USA Today, The Saturday Evening Post, the Los Angeles Times Syndicate, OMNI magazine. In 1982, he produced the first short-subject syndicated radio program, Health News. He has written 20 books, including his latest, No More National Debt (March 2011); and three feature-length documentaries, including <strong>The Money Masters</strong> (1995), the 15th-most-watched film on the Internet in history; and <strong>The Secret of Oz</strong> (2010, <a href="http://www.secretofoz.com" target="_blank">www.secretofoz.com</a>), winner of Best Documentary of 2010 at the Beloit International Film Festival.</p><p>His new book is entitled, “No More National Debt” (2011, <a href="http://www.billstill.com" target="_blank">www.billstill.com</a>).
</p>
</article>
