<div class="sticky">

	<a href="#" class="fancybox red-button">
		Inquire Today
	</a>
	<a href="#" class="fancybox grey-button">
		Ask a question
	</a>
</div><!-- end sticky -->


<div id="main-content" role="main">



	<div class="blue-bg clear">

		<section class="what-is">   

			<div class="wrapper">  

				<header>
					<h1 class="red">Blank page template</h1>                     
				</header>                                                                                        

			</div>  <!-- end wrapper -->            

			<div class="ribboncorners"></div>

		</section> <!-- end what-is -->           

		<div class="clear"></div>


	</div><!-- end blue-bg -->    


	<section>




		<div class="box">                       

			<h3>Blank page full col</h3>

			<p>We plan on several locations, built one at a time over the next several years.  
				Locations are designed to allow for access from major cities on a single tank of gas.  
				They are also picked strategically for their resilience to the following:</p>

			<ul class="decorated">
				<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
				<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>
				<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
				<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>
				<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
				<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>

			</ul>                      


		</div> <!-- end box -->



		<div class="box">                       

			<div class="col">
				<h3>Blank page Half width</h3>

				<p>We plan on <span class="blue">Blue Text</span> several locations, built one at a time over the next several years.  
					Locations are designed to allow for access from major cities on a single tank of gas.  
					They are also picked strategically for their resilience to the following:</p>

				<ul>
					<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>

				</ul>                      
			</div><!-- end col -->

		</div> <!-- end box -->






	</section><!-- end main-content -->




</div><!-- end middle-content -->