<div class="sticky">

	<a href="application/signup" class="fancybox red-button">
		Sign Up Today
	</a>
	<a href="contact" class="fancybox grey-button">
		Ask a question
	</a>
</div> <!-- end sticky -->


<div id="main-content" role="main">



	<div class="blue-bg clear">

		<section class="what-is">   

			<div class="wrapper">  

				<header>
					<h1 class="red">First Adopters Wanted</h1>                     
				</header>                                                                                        

			</div>  <!-- end wrapper -->            

			<div class="ribboncorners"></div>

		</section> <!-- end what-is -->           

		<div class="clear"></div>


	</div><!-- end blue-bg -->    


	<section>




		<div class="box">                       

			<h3>Help Us, and we'll help you!</h3>

			<p>Getting a new business up and going is alot of work.  It's also wildly expensive!  As a customer, this business is young and unproven.  We may likely be a little wobbly when we first get going, and most likely, you won't get 100% value for several months.
			<br><br>But that's why we're giving our first 500 customers FREE access!<br>
			Try it out! If you're willing to help us launch this business and join as a first adopter, we'll help you with long term discounts!</p>

<h2>Prep School Membership Cost: <strike>$60/mo</strike></h2>

<div class="box">

						<h1 class="large">
							<span>SAVE BIG</span> with our special<br>First Adopter Discounts:
						</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>
							
										<h4>AS A FIRST ADOPTER, YOU'LL PAY 50-70% LESS THAN OTHER MEMBERS!</h4>


							<div class="col">
								<h4 class="black">First Adopter Discounts:</h4>
			<ul class="decorated">
				<li><u>First 500 Members:</u> <b>FREE TRIAL<br />
				Today thru Oct. 1, 2012!</b>
				<p><i>You'll be part of our "test audience"...<br>
				We'll train you, then survey you.<br>100% FREE through 10-1-12!</i></p></li>
				<li>Members 501-600: $20/mo</li>
				<li>Members 601-850: $25/mo</li>
				<LI>Members 851-999: $30/mo</li>
			</ul>
							</div><!-- end col-->

							<div class="col">
								<h4 class="black">It Gets Better!</h4>
			<p>A special perk ONLY for our FIRST ADOPTERS:<br><br>
			<strong>When we reach 1,000 members...<br>your monthly fee will be lowered to <br>just $20/mo, forever!</strong>
			</p>


							</div><!-- end col-->

							<div class="clear"></div>
			
						</div><!-- end speech -->

					</div><!-- end box -->   

			

	<div class="box">
						<div class="clear speech">

							<div class="speech-corner-r"></div>

							<h1>Interested in being a First Adopter?</h1>

								<div class="col">
								<div class="blue-ribbon">
									
									<h3>Member Fee:<strike>$60.00/mo</strike></h3>
									<h1>FREE TRIAL</h1>
									<p class="notice">- Free Trial signup ends Aug 31, 2012 or at 500 members -<br>
									- On 10-1-2012, you'll be offered a SPECIAL price of $20/mo -<br>
									- This offer only available to first 500 members! -</p>
								</div><!-- end blue-ribbon -->
								
								
								<!-- 20/mo
								<div class="col">
								<div class="blue-ribbon">
									<h3>Monthly Member Fee</h3>
									<h3>Member Fee:<strike>$60.00/mo</strike></h3>
									<h1>Special Price: $20</h1>
									<p class="notice">- subject to change after 50 members join! -</p>
								</div> end of $20/mo -->
								
								
								<!-- 30/mo
								<div class="col">
								<div class="blue-ribbon">
									<h3>Monthly Member Fee</h3>
									<h3>Member Fee:<strike>$60.00/mo</strike></h3>
									<h1>Special Price: $30</h1>
									<p class="notice">- subject to change after 50 members join! -</p>
								</div> end of $30/mo -->
								
								
								



							</div><!-- end col -->

							<div class="col">
								<h4 class="black">Reasons to Join Today:</h4>

								<ul class="decorated">
									<li>Your Special Price is Grandfathered in, Forever!</li>
									<li>100% Satisfaction Guarantee</li>
									<li>Earn a special thank you in our upcoming book!</li>
									                       
								</ul>

							</div><!-- end col-->

							
							<a href="application/signup" class="blue-rounded-btn animate-hover right cboxElement fancybox">BECOME A MEMBER</a>
<div class="clear"></div>
						<br><br>
						
                                   <a href="blaze#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
						</div><!-- end speech -->

					</div><!-- end box -->

	</section><!-- end main-content -->




</div><!-- end middle-content -->