
    
 <div class="sticky">

	<a href="contact" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->



	<div id="main-content" role="main">
		<div class="blue-bg clear">
			<section class="what-is">   
				<div class="wrapper">  
					<header>
						<h1>Preparedness as a Business</h1>                      
					</header>
					<div class="content">
						<h2 class="question">
						Can you make money prepping?
						</h2>

						<p>
						Mainstream Preppers offers several ways to make money in the preparedness industry.  
						Income opportunities range from investments in our retreat concepts to direct and referral marketing rewards.</p>


							</div><!-- end content -->    

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>

					<div class="box">

						<h1 class="large">
							<span>Why</span> 
							would someone want to make preparedness into a business?
						</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>

							<div class="col">
								<h4 class="black">Get Paid for what you Love</h4>
								<p>Life coaches often say your business should be in the same industry as your passion.
								If you&rsquo;re into preparedness as a lifestyle, work with us and turn your passion<br />
								into an income!<br />
</p>

								<h4 class="black">Tax Benefits</h4>
								<p>Preparedness is expensive. Gear, training, gear, books, gear, gas and more.
								With a preparedness business, you'll deduct gear, fuel, trips, training, etc as necessary for your business.
						  </p> 
							</div><!-- end col-->

							<div class="col">
								<h4 class="black">Benefits of a Preparedness Business</h4>
								<ul class="decorated">
									<li>Make $$$ doing what you Love</li>
									<li>Help Friends/Family get Prepared</li>
									<li>Residual Income Opportunity</li>
									<li>Possibly Significant Tax Benefits</li>
									

								</ul>

							</div><!-- end col-->

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->   

					
				<div class="box">                       
					<div class="col">
						<h3>Investors</h3>

						<p><b>Solid Return on Investment, plus perks!</b></p>

							<ul class="red-bullets">
							
							<li><p>Quarterly Investor Dividend</p></li>
							<li><p>Residual Income!</p></li>
							<li><p>Investor Perks</p></li>
							<li><p>Several Options Available</p></li>
							</ul>
							<a href="contact" class="blue-rounded-btn animate-hover left fancybox cboxElement">Investor Inquiries</a>

<!--<a href="businessinvest" class="blue-rounded-btn animate-hover left cboxElement">Investor Details</a> 
                      		-->
                      		<!--
							<a href="businessinvest" class="link-box">Investing Details</a>-->

						</div><!-- end col -->

						<div class="col">
							<h3>Marketers</h3>
							<p><b>Great Rewards for Growing our Customer Base!</b></p>
							
							<ul class="red-bullets">
								<li><p>Refer Just 3 - Your membership is FREE!</p></li>
								<li><p>Website/Blog/Forum/Channel Sponsorships</p></li>
								<li><p>Significant Income Opp for Serious Marketers</p></li>
                                <li><p><b><a href="marketingexample" class="fancybox">See Income Example</a></b></p></li>
							</ul>

							
                       
							<a href="contact" class="blue-rounded-btn animate-hover left fancybox cboxElement">Marketing Inquiries</a>

						</div><!-- end col -->                      

					</div> <!-- end box -->


					<div class="box">



						<div class="col">
							<h3>Instructors</h3>
							<p><b>Professional Pay for Professional Instructors</b></p>
							
							<ul class="red-bullets">
								<li><p>Guest Instructors - Great Pay for a Great Weekend</p></li>
								<li><p>Key Instructors - Full Classes, Great Pay + <br />
										Revenue Share!</p></li>
								<li><p>Virtual (online) Trainings - Residual Income!</p></li>
							</ul>
							
							<a href="contact" class="blue-rounded-btn animate-hover left fancybox cboxElement">Instructor Inquiries</a>
							
							
							<div class="clear"></div><br><br>
							<a href="business#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                     

						</div><!-- end col -->

						<div class="col">
							<h3>Strategic Partnerships:</h3>
							<p><b>Let&rsquo;s help each other!</b></p>
							
							<ul class="red-bullets">
								<li><p>Want to Sponsor our events? Want us to sponsor yours?</p></li>
								<li><p>Looking to grow your business?  Can we help?</p></li>
								<li><p>How can we work together and everyone win</p></li>
							</ul>
							<a href="contact" class="blue-rounded-btn animate-hover left fancybox cboxElement">Partner/Affiliate Inquiries</a>


						</div><!-- end col -->   
						
					</div><!-- end box -->







				</section><!-- end main-content -->




			</div><!-- end middle-content -->
