
 <div class="sticky">

	<a href="contact" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->


	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>Investing in Mainstream Preppers</h1>
						<br><p>this page is a work in progress</p>                      
					</header>


					  

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>

					
					<!--<div class="box">  
				
						<h1 class="large">
							<span>How</span> 
							can someone want INVEST in Mainstream Preppers?
						</h1>
                  
					</div>--><!-- end box -->



					<div class="box">
						<div class="clear speech">

							<div class="speech-corner-r"></div>

							<h1>The $100,000 HOMESTEAD Investor package:</h1>

							<div class="col">
								<div class="blue-ribbon">
									<h3>5 Acre Homestead, plus</h3>
									<h1>Residual Revenue %</h1>
									<!--<p class="notice">- You Pick your plot! -</p>-->
								</div><!-- end blue-ribbon -->


							<a href="#" class="link-box">Inquire for details</a>
							
							</div><!-- end col -->

							<div class="col">
								<h4 class="blue">What You'll Get:</h4>

								<ul class="decorated">
									<li>5+ Acre Homestead in Prime Location of your choice.</li>
									<li>Earn 10% of the prep school investor dividend*<!--, FOREVER-->!<br><i>*inquire for details</i></li>
									<li>Earn 15% your retreat's investor dividend*<!--, FOREVER-->!</li>
									<li>No Monthly Maintenance Fees, EVER!</li>
									<li>FREE <a href="prepschool">Prep School</a> membership</li></ul>
							</div><!-- end col-->
							<h4>Example ROI</h4>							
							<p>With 2,000 members and a 15 customer retreat, you'd be receiving over $1,000/month in residual income <!-- 2k x $30 x .15 x .1=900; plus 15x300x.15x.15=$100 --><br>With 5,000 members it's about $2,500 per month!</p>

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->

					<div class="box">
						<div class="clear speech">

							<div class="speech-corner-r"></div>

							<h1>The $75,000 RETREAT Investor package:</h1>

							<div class="col">
								<div class="blue-ribbon">
									<h3>Retreat Membership, plus</h3>
									<h1>Residual Revenue %</h1>
									<!--<p class="notice">- secured by retreat land! -</p>-->
								</div><!-- end blue-ribbon -->


							<a href="#" class="link-box">Inquire for details</a>
							
							</div><!-- end col -->

							<div class="col">
								<h4 class="blue">What You'll Get:</h4>

								<ul class="decorated">
									<li>Retreat Membership at Location of your choice<br />(a $20,000 Value!)</li>
									<li>Earn 5% of the prep school investor dividend*<!--, FOREVER-->!<br><i>*inquire for details</i></li>
									<li>Earn 15% of your retreat's investor dividend*<!--, FOREVER-->!</li>
									<li>No Retreat Monthly Maintenance Fees, EVER!<br />(a $40,000 Value over 10 years!)</li>
									<li>FREE <a href="prepschool">Prep School</a> membership</li></ul>
							</div><!-- end col-->
							<h4>Example ROI</h4>							
							<p>With 2,000 members and a 15 customer retreat, you'd be receiving over $550/month in residual income <!-- 2k x $30 x .15 x .05=450; plus 15x300x.15x.15=$100 --><br>With 5,000 members it's about $1,500 per month!</p>

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->



					<div class="box">
						<div class="clear speech">

							<div class="speech-corner-r"></div>

							<h1>The $50,000 straight investment</h1>

							<div class="col">
								<div class="blue-ribbon">
									<h3>Return on Investment:</h3>
									<h1>5% + revenue share</h1>
									<!--<p class="notice">- secured by retreat land -</p>-->
								</div><!-- end blue-ribbon -->


							<a href="#" class="link-box">Inquire for details</a>

							</div><!-- end col -->

							<div class="col">
								<h4 class="blue">INVESTOR PERKS:</h4>
									<ul class="decorated">
									<li>Investment secured by valuable retreat property</li>
									<li>Your Investment Repaid with 5% interest over 84 months<br /><i>
									First 12 months: no payments, no interest.  Open for negotiation.</i></li>
									<li>5% of total  prep school dividend, for 10 years.</li>
									<li>10% of 1 retreat dividend, for 10 years.</li>
									<li>FREE <a href="prepschool">Prep School</a> membership</li></ul>

							</div><!-- end col-->

							<h4>Example ROI</h4>							
							<p>With 5,000 members and a 20 customer retreat, you'd receive $625/mo in loan repayments plus $1,240/month in residual income (ends after 10 years). <!-- 5k x $30 x .15 x .05=1125; plus 20x300x.20x.1=$120 --></p>

								
							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->






				</section><!-- end main-content -->




			</div><!-- end middle-content -->
