<header>
	<h1 class="red underline">Contact Mainstream Preppers</h1>
</header>



<section class="form">

	<div id="form-message"></div>

	<form action="contact" id="contact-form" method="post">

		<label for="emailaddress">Email Address:</label>
		<input name="emailaddress" type="email"  class="required" id="emailaddress" />                

		<label for="firstname">First Name:</label>
		<input name="firstname" id="firstname" type="text" class="firstname required"  />

		<label for="lastname">Last Name (optional):</label>
		<input name="lastname" type="text" id="lastname"   />

		<label for="phone">Phone (optional):</label>
		<input name="phone" id="phone" type="tel" maxlength="10" />

		<label for="comments">Questions/Concerns</label>
		<textarea  name="comments" id="comments" class="commments required" ></textarea>

		<input type="submit" class="form-btn " value="Submit" name="submit" />        
	</form>

</section>
