


<link href="css/course.css" rel="stylesheet">


 <div class="sticky">

	<a href="application/signup" class="fancybox red-button">
		Sign Up Today
	</a>
    
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->






	<div id="main-content" role="main">


		<div class="blue-bg clear">



					<section class="course-page-header">   
					
							<div class="wrapper">  	
						
						<header>
							<h1><span class="course-detail-icon">Course Detail</span></h1>
						</header>
					
					
							<a href="#" class="vid-preview right">
													<span class="vid-icon"></span>
													Video image put it here
								</a>
					
						<div class="course-description with-video">					

							<h1>Women&rsquo;s Self Defense</h1>
							
							<div class="tags">
								
								<ul>
									<li><b>Tags:</b></li>
									<li><a href="#">Basic 101</a></li>
									<li><a href="#">Security &amp; Defense</a></li>
									<li><a href="#">Basic 101</a></li>
								</ul>
								
							</div>
								
							<div style="clear: left;"></div>	
													
							<p>It can be a dangerous world out there but you need not live in fear. This course will empower you to move around in society with confidence and safety, 
							avoid bad situations, and if problems do occur – deal with them efficiently and effectively regardless of your size, age, or physical condition. 
							</p>

							<p class="course-instructor"><a href="instructorbio">INSTRUCTOR: JOE FOX, VIKING PREPAREDNESS &raquo;</a></p>
						
						</div><!-- end course-description -->
						
						
								  
										
						

				
						<div class="clear"></div>
						
							</div>  <!-- end wrapper -->            
				
							<div class="ribboncorners"></div>
							
							
							
								<div class="breadcrumbs">
									<a href="#">Home</a> > <a href="#">Prep School</a> > <a href="#">Viking Preparedness</a> > <a href="#">Women&rsquo;s Self Defense</a>
								</div>
								
							<br />
					</section> <!-- end instructor-page-header -->    
					       

					<div class="clear"></div>
				</div><!-- end blue-bg -->    


						
							




<section class="box twocol" id="course-page-content">
       
          
                                  
                           <div class="right-col wide">
						   
						   
                                  
										<div class="course-detail-lessons-list">
											<h4>Lessons included in this course:</h4>
											<ul>
											
												<li>
													<a href="#">
													<span class="title">Basic Firearm 101</span>
													<span class="instructor">Taught by: Joe Fox</span>
													</a>
													<div class="reviews">
														<span class="stars"><b class="rated four">Four Stars</b></span>
														<a href="#">20 Reviews</a>
													</div>
												</li>
											
											
												<li>
													<a href="#">
													<span class="title">Medical 101</span>
													<span class="instructor">Taught by: Joe Fox</span>
													</a>
													<div class="reviews">
														<span class="stars"><b class="rated five">Five Stars</b></span>
														<a href="#">20 Reviews</a>
													</div>
												</li>


												<li>
													<a href="#">
													<span class="title">Survival 101</span>
													<span class="instructor">Taught by: Joe Fox</span>
													</a>
													<div class="reviews">
														<span class="stars"><b class="rated three">three Stars</b></span>
														<a href="#">20 Reviews</a>
													</div>
												</li>


												<li>
													<a href="#">
													<span class="title">Survival 101</span>
													<span class="instructor">Taught by: Joe Fox</span>
													</a>
													<div class="reviews">
														<span class="stars"><b class="rated two">two Stars</b></span>
														<a href="#">20 Reviews</a>
													</div>
												</li>

												<li>
													<a href="#">
													<span class="title">Survival 101</span>
													<span class="instructor">Taught by: Joe Fox</span>
													</a>
													<div class="reviews">
														<span class="stars"><b class="rated one">one Stars</b></span>
														<a href="#">20 Reviews</a>
													</div>
												</li>
												

					

												<li>
													<a href="#">
													<span class="title">Survival 101</span>
													<span class="instructor">Taught by: Joe Fox</span>
													</a>
													<div class="reviews">
														<span class="stars">no reviews</span>
														<a href="#">0 Reviews</a>
													</div>
												</li>

											</ul>
											
											<div class="clear"></div>
										</div><!-- end course-detail -->
										
										
										<div id="enroll-now">
											<a href="#" class="enroll-button"><span class="button">Enroll in this Course</span></a>
										</div>
							
							
							
										  
									<img title="comments" src="images/prepschool-comment.gif">
										  

								  

								  
                                
                                  
                          </div><!-- end right-col -->
                          
    
	
          
                  <aside class="sidebar instructor-info">                  
                           
						   <header><h1>ABOUT THE INSTRUCTOR</h1></header>
						   
						   <img src="images/course/instructor/joe-fox.jpg" title="Joe Fox" />
						   
						   <p><b>Joe Fox</b> is a former Special Forces and intelligence officer who has studied and taught wilderness survival, combatives, and preparedness subjects to men, women and children for over 30 years. He is married with three adult children and lives on a self-sufficient homestead.</p>

						   
						   <ul class="instructor-overview">
						   
						   	<li><a href="#" class="courses"><b>12</b> courses</a></li>
						   	<li><a href="#" class="lessons"><b>291</b> lessons</a></li>
						   	<li><a href="#" class="stars"><b>4</b> out of 5 stars</a></li>
						   	<li><a href="#" class="reviews"><b>5</b> reviews</a></li>
						   	<li style="margin-top: 25px;"><a href="#" class="contact"><b>Contact Joe</b></a></li>
								<li><a href="http://www.vikingpreparedness.com/" class="website"><b>Company URL</b></a></li>
								<li><a href="http://www.youtube.com/user/VikingPreparedness" class="youtube"><b>YouTube Channel</b></a></li>
								<li><a href="http://www.vikingpreparedness.blogspot.com/" class="blog"><b>Blog</b></a></li>

						   
						   </ul><!-- end overview-->
						   
                  </aside>   
	
	
	
          			<div class="clear"></div>			
					
					
								  
								  
								  
								  <article class="events-in-area">
								  
								  
								  		<header>
											<h1>Other courses in the Leavenworth, KS</h1>
											<a href="#">See Full Course List <span>&raquo;</span></a>
											<div class="clear"></div>
										</header>
										
										<ul>
										
											<li>
												<a href="#">
													<b>Awesome Learning Course</b>
													<i>Taught by: Joe Fox</i>
												
												</a>											
											</li>
											
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Course</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Course</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Course</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Course</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
											
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Course</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Course</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
										</ul>
										
										<div class="clear"></div>
										
								  </article><!-- end events-in-area -->
					
					
					
					
					
          </section><!-- end instructor-page-content -->




			</div><!-- end middle-content -->
