
    
<!-- <div class="sticky">

	<a href="contact" class="fancybox red-button">
		Inquire Today
	</a-->
   <!--  
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div>end social -->
    
	<!--a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div> end sticky -->



	<div id="main-content" role="main">
                        
                            <div class="blue-bg clear">
                            
                                <section  id="create-profile-banner" >   
                                  
                                                    <header>
                                                        <h1>Create a MSP Profile. Gain access to to the Prep School and Prepper Network.</h1>                      
													
                                                    </header>
                                  					
				                  </section>        
                    
                                        <div class="clear"></div>
                                </div><!-- end create-profile-banner -->    


					<section>

                       
                                
                                	<section class="box twocol"> 
                                        
                                         
                                          <div class="wide-left sixtyfive">
                                         	  <link href="css/form.css" rel="stylesheet">
                                            
                                       		
                                            
                                                <form action="#" method="post" id="create-profile" class="myform">
                                                
                                                   <div class="form">
                                               
                                               
                                                       <label for="emailaddress">Email Address:</label>
                                                       <input name="emailaddress" id="emailaddress" type="email"  class="required" />     
                                                  
                                                        <label for="zip" class="clear">Zip Code:</label>
                                                        <input name="zip" id="zip" type="text" class="zipcode required" maxlength="10" />
                                                   
                                                    
                                                       <label for="username">Username:</label>
													   
													   <!-- NOTE: add class 'valid' or 'invalid' to switch the username-check icon -->  
													   <a href="#" class="username-check valid"><span>Username</span> 													   
													  	  Username<br />Available
													   <!-- NOTE: switch text to " Username<br />Available" or "  Username Not<br />Available" or "Check" -->
													   </a> 

                                                       <input name="username" id="username" type="text"  class="required username-with-check left" />  
													   

                                                  
													
                                                    <div class="clear"></div>
                                                       
                                                     <div>
                                                        <label for="password" class="clear">Password:</label>
                                                        <input name="password" id="password" type="password" class="password required"  />
                                                     </div>			
                                                       
                                                     <div>
                                                        <label for="password2" class="clear">Confirm Password:</label>
                                                        <input name="password2" id="password2" type="password" class="password-confirm required" />
                                                     </div>
													 
													
                                                    <div class="clear"></div>
                                                       
													   
											
													   	<label for="terms">Terms of Service:</label>
														I have read and agree to the <a href="terms" class="fancybox">Terms of Service</a>
														<input type="checkbox" id="terms" name="terms" />  
													 
                                        <br /><br />
                                                            <div class="clear"></div>
                                               
                                           				 </div><!-- end form -->
                                       
                                                       
                                                       
                                                         <div id="form-message"></div>
                                                         
                                                       <input type="submit" class="form-btn" value="SUBMIT" name="submit" id="submit"/> 
                                                       
                                               
                                               
                                                </form>         
                                                
                                            
                                            </div><!-- end wide-left-->
                                            
                                            
                                            
                                            
                                            <aside class="right-col" style="">
								
												<div class="notice" style="margin-top: 30px;">
												<div class="arrow" ></div>
													<h3>Email:</h3> your email is never released or shared.  never sold.  no spam.
												</div>
													
												<div class="notice">
												<div class="arrow"></div>
													<h3>Zip code:</h3> is used to help you network with preppers in your area.
												</div>
	
												<div class="notice">
													<div class="arrow"></div>
													<h3>Username:</h3> for max privacy, we suggest a unique username different than used on other sites.
												</div>
												<div class="notice" style="margin-bottom: 10px;">
													<div class="arrow"></div>
													<h3>Password:</h3> we suggest a password with 5 or more characters and including at least 1 number.
												</div>


                                            		<a href="contact" class="questions-on-signup fancybox" data-fancybox-type="iframe" style="margin-left: -3px; margin-top:0;">
                                                    <b>Questions?</b>
                                                    ASK US</a><br />
                                                    
                                            </aside><!-- end right-col-->
                                            
                                            <div class="clear"></div>

	                                </section><!-- end twocol-->
                                
                                
                                	
                                
                         







				</section><!-- end section -->




	</div><!-- end main-content -->
