<article>

<header>
    <h1 class="red">Don Harrold - The DayTrade Show</h1>
     
</header>


	<p>
	Don Harrold is a trader who believes
<strong>every</strong> decision you make with
money is an investment choice.  
He believes the old adage, "time is money,"
is more accurately read, "money is time,"
because every penny you make or lose
means more time you must spend
to make it back.  
</p><p>He learned to trade
stocks, options, precious metals, and
currency pairs over 14 years of daily,
actual, live trading.  His services have
been used by over 50,000 traders and
investors around the world.
</p><p>
Mr. Harrold says there are four things you need to
do every day:
<ol><li>Get out of debt
</li><li>take on
no further debt
</li><li>make more money today
than you did yesterday
</li><li>own hard assets</li></ol>
We look forward to bringing you economic news and updates from Don Harrold.</p>
</article>
