<article>

<header>
    <h1 class="red">Joe & Amy Alton - Doom and Bloom LLC</h1>
     
</header>


	<p>
	Joseph Alton is a Fellow of the American College of Surgeons and the American College of OB/
Gyn. He has been a speaker at various survival and preparedness conferences on the subject of medical
readiness in austere times. A member of MENSA, Dr. Alton collects medical books from the 19th century
to gain insight on off-the-grid medical protocols.
</p><p>
Amy Alton is an Advanced Registered Nurse Practitioner and a Certified Nurse-Midwife. She has had
years of experience working in large teaching institutions as well as smaller, family-oriented hospitals.
Amy has extensive medicinal herb and vegetable gardens and works to include natural remedies into her
strategies.
</p><p>
Dr. and Ms. Alton are both Master Gardeners for their state. They also are devoted aqua culturists
(currently raising tilapia) and are well-known aquaponic, raised bed and container gardening experts.
</p><p>
Dr. and Ms. Alton are the authors of the #1 Amazon Bestseller (Survival Skills and Safety/First Aid
categories) "The Doom and Bloom Survival Medicine Handbook" Additionally, they have been regular
contributors to Survivalist, Backwoods Home, and Self-Reliance Illustrated Magazines. As "Dr. Bones
and Nurse Amy", they host blog and radio programs under the Doom and Bloom label. They are also
the owners of a YouTube channel, <a href="http://www.youtube.com/user/drbonespodcast" target="_blank">drbonespodcast</a>, with medical and gardening videos.
</p><p>
Dr. and Ms. Alton use pseudonyms to allow them the freedom to buck the conventional medical wisdom
when necessary. They are firm believers that, to remain healthy in hard times, we must use all the tools
at our disposal. Their goal is to promote integrated medicine; in this way, their readers will have the
most options to keep their loved ones healthy in times of trouble.</p>
</article>
