


<link href="css/course.css" rel="stylesheet">


 <div class="sticky">

	<a href="application/signup" class="fancybox red-button">
		Sign Up Today
	</a>
    
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->






	<div id="main-content" role="main">


		<div class="blue-bg clear">



					<section class="course-page-header">   
					
							<div class="wrapper">  	
						
						<header>
							<h1><span class="course-detail-icon">Event Detail</span></h1>
						</header>
					
						<div class="course-description">					

							<h1>Women&rsquo;s Self Defense</h1>
													
							<p>It can be a dangerous world out there but you need not live in fear. This course will empower you to move around in society with confidence and safety, 
							avoid bad situations, and if problems do occur – deal with them efficiently and effectively regardless of your size, age, or physical condition. 
							</p>

							<p class="course-instructor"><a href="instructorbio">INSTRUCTOR: JOE FOX, VIKING PREPAREDNESS &raquo;</a></p>
						
						</div><!-- end course-description -->
						
						
								  
										  <div class="event-date-time-box">
											  <a href="#">
													<span class="location">Leavenworth, KS</span>
													<time datetime="10-28-2012T10:00-0600">
														<span class="event-weekday">Wednesday</span>
														<span class="event-month-date">Oct 11</span>
														<span class="event-time">10:00 AM - 10:00 PM</span>
													</time>
													
													
											  </a>
										  </div><!-- event-date-time-box -->
						

				
						<div class="clear"></div>
						
							</div>  <!-- end wrapper -->            
				
							<div class="ribboncorners"></div>
							
							
							
								<div class="breadcrumbs">
									<a href="#">Home</a> > <a href="#">Prep School</a> > <a href="#">Viking Preparedness</a>
								</div>
								
								

					</section> <!-- end instructor-page-header -->    
					       

					<div class="clear"></div>
				</div><!-- end blue-bg -->    


						
								<h4 class="red text-center box" style="padding: 5px; width: 950px;">REGISTRATION CLOSES AUGUST 14, 2012. RSVP TODAY!</h4>
								<div class="box" style="padding: 0; margin:5px auto;"><a href="#" class="text-center watch-online-link"><span>Can&rsquo;t Make this Class?</span>  <span class="watch-icon">Watch it Online</span></a></div>
							




<section class="box twocol" id="course-page-content">
       
          
                                  
                           <div class="right-col wide">
						   
						   
                                  
										<ul class="course-detail">
											<li>
												<span class="title">Event</span>
												<span class="detail">Women’s Self Defense</span>
											</li>
											<li>
												<span class="title">Instructor</span>
												<span class="detail">Joe Fox</span>
											</li>
											<li>
												<span class="title">Location</span>
												<span class="detail"><a href="http://map.google.com" class="map-icon">Map</a> RPCC, 5501 Full Address Rd., Leavenworth, KS 66554 </span>
											</li>
											<li>
												<span class="title">Date</span>
												<span class="detail">Sunday, August 13, 2012</span>
											<li>
												<span class="title">Time</span>
												<span class="detail">3:00 P.M. - 6:00 P.M. </span>
											</li>
											<li>
												<span class="title">Requirement</span>
												<span class="detail">Course is open to all women 16 years old and up. 
                                					  (16 and 17 year olds will require signed parental permission  and release form) </span>
											</li>
											<li>
												<span class="title">Class Size</span>
												<span class="detail">Class size is limited to 12</span>
											</li>								
										
										
										</ul><!-- end course-detail -->
							
										  
										  <div class="event-course-sign-up">
										  
										  		<ul>
														<li class="sign-up-before">
															<p>
															<b class="save">SAVE $50</b>
															<span class="before-date">when signup before August 15th</span>
															
															<div class="slot-open">															
																<span class="slot-num">16</span> SLOTS CURRENTLY OPEN.
															</div><!-- end slot-open -->
															
															<div class="pointer"></div>
															
														</li>
														
														<li>
															<a href="#" class="enroll-button">
																<b>Non-Member</b>
																<del class="regular-price">$295</del>
																<span class="discounted-price">$270</span>		
																<span class="button">Enroll</span>													
															</a>														
														</li>
														
														
														<li class="last">
															<a href="#" class="enroll-button">
																<b>Member</b>
																<del class="regular-price">$175</del>
																<span class="discounted-price">$150</span>	
																<span class="button">Enroll</span>															
															</a>														
														</li>
															
												
												</ul>
												
										  	<div class="event-notice clear">
												<p>This event is confirmed when 8 students sign up.<br />
												Your payment is only authorized at that time.</p>
											</div><!-- end event-notice-->  
												
										  </div><!-- end event-course-sign-up -->
										  

										  
										  
											<ul class="course-detail clear">
												<li>
													<span class="title">Special Note</span>
													<span class="detail">
												Wear comfortable clothing that allows you to move, minimal jewelry. Bring your purse/bag and any defensive items you  normally carry. You may also wish to bring paper and pencil, 
												   water and a snack. <br />
													
													<b>CLASS WILL BE FILMED AND FILM MADE AVAILABLE IN MSP PREP SCHOOL</b>
													</span>
												</li>
											</ul><!-- end course-detail -->
											

										  
										  
										  
										  
										  
							
									<article class="related-events">
										<header>
											<h1>Related Event in Same Series</h1>
										</header>
										
										<ul>
											<li>
												<a href="#">
														<time datetime="08-22-2012">
															<span class="event-month">Aug</span>
															<span class="event-date">22</span>
														</time>
														
														<h2>Women&rsquo;s Self Defense</h2>
														<p>Leavenworth, KS<br />
														Taught by: Joe Fox</p>											
												</a>
											</li>
											<li>
												<a href="#">
														<time datetime="08-30-2012">
															<span class="event-month">Aug</span>
															<span class="event-date">30</span>
														</time>
														
														<h2>Women&rsquo;s Self Defense</h2>
														<p>Leavenworth, KS<br />
														Taught by: Joe Fox</p>											
												</a>
											</li>
											<li>
												<a href="#">
														<time datetime="08-22-2012">
															<span class="event-month">Aug</span>
															<span class="event-date">22</span>
														</time>
														
														<h2>Women&rsquo;s Self Defense</h2>
														<p>Leavenworth, KS<br />
														Taught by: Joe Fox</p>												
												</a>
											</li>
											<li>
												<a href="#">
														<time datetime="08-30-2012">
															<span class="event-month">Aug</span>
															<span class="event-date">30</span>
														</time>
														
														<h2>Women&rsquo;s Self Defense</h2>
														<p>Leavenworth, KS<br />
														Taught by: Joe Fox</p>												
												</a>
											</li>
											
										</ul>
										  
										  
									</article><!-- end upcoming-events -->
								  

								  
                                
                                  
                          </div><!-- end right-col -->
                          
    
	
          
                  <aside class="sidebar instructor-info">                  
                           
						   <header><h1>ABOUT THE INSTRUCTOR</h1></header>
						   
						   <img src="images/course/instructor/joe-fox.jpg" title="Joe Fox" />
						   
						   <p><b>Joe Fox</b> is a former Special Forces and intelligence officer who has studied and taught wilderness survival, combatives, and preparedness subjects to men, women and children for over 30 years. He is married with three adult children and lives on a self-sufficient homestead.</p>

						   
						   <ul class="instructor-overview">
						   
						   	<li><a href="#" class="courses"><b>12</b> courses</a></li>
						   	<li><a href="#" class="lessons"><b>291</b> lessons</a></li>
						   	<li><a href="#" class="stars"><b>4</b> out of 5 stars</a></li>
						   	<li><a href="#" class="reviews"><b>5</b> reviews</a></li>
						   	<li style="margin-top: 25px;"><a href="#" class="contact"><b>Contact Joe</b></a></li>
								<li><a href="http://www.vikingpreparedness.com/" class="website"><b>Company URL</b></a></li>
								<li><a href="http://www.youtube.com/user/VikingPreparedness" class="youtube"><b>YouTube Channel</b></a></li>
								<li><a href="http://www.vikingpreparedness.blogspot.com/" class="blog"><b>Blog</b></a></li>

						   
						   </ul><!-- end overview-->
						   
                  </aside>   
	
	
	
          			<div class="clear"></div>			
					
					
								  
								  
								  
								  <article class="events-in-area">
								  
								  
								  		<header>
											<h1>Other events in the Leavenworth, KS</h1>
											<a href="#">See Full Event List <span>&raquo;</span></a>
											<div class="clear"></div>
										</header>
										
										<ul>
										
											<li>
												<a href="#">
													<b>Awesome Learning Lesson</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Lesson</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Lesson</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Lesson</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Lesson</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
											
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Lesson</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
										
											<li>
												<a href="#">
													<b>Awesome Learning Lesson</b>
													<i>Taught by: Joe Fox</i>
													Oct 20, 2012
												</a>											
											</li>
											
										</ul>
										
										<div class="clear"></div>
										
								  </article><!-- end events-in-area -->
					
					
					
					
					
          </section><!-- end instructor-page-content -->




			</div><!-- end middle-content -->
