
    
 <div class="sticky">

	<a href="contact" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->


<div id="main-content" role="main">



	<div class="blue-bg clear">

		<section class="what-is">   

			<div class="wrapper">  

				<header>
					<h1 class="red">FAQ for prepper newbies</h1>                     
				</header>                                                                                        

			</div>  <!-- end wrapper -->            

			<div class="ribboncorners"></div>

		</section> <!-- end what-is -->           

		<div class="clear"></div>


	</div><!-- end blue-bg -->    


	<section>




		<div class="box">                       

    <h1 class="red">FAQ</h1>
    <h4>Short Answers to Common Questions</h4>

			<h3>NO CONTENT HERE YET.  STOP READING</h3>

<img src="images/placeholder.jpg" class="image right" />

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum porta neque, eget consectetur risus pharetra eget. Aliquam vitae mi quis lacus consequat tincidunt porta vel ante. 
Vivamus eu venenatis arcu. Praesent tortor elit, volutpat ut auctor sit amet, 
convallis vitae dui. In hac habitasse platea dictumst. Integer bibendum eleifend enim, vitae sollicitudin justo condimentum rutrum. Quisque vulputate elit vitae arcu malesuada porta. Nullam et sapien nulla.</p>

			<h3>Blank page full col</h3>

			<p>We plan on several locations, built one at a time over the next several years.  
				Locations are designed to allow for access from major cities on a single tank of gas.  
				They are also picked strategically for their resilience to the following:</p>

			<ul class="decorated">
				<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
				<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>
				<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
				<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>
				<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
				<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>

			</ul>                      


		</div> <!-- end box -->



		<div class="box">                       

			<div class="col">
				<h3>Blank page Half width</h3>

				<p>We plan on <span class="blue">Blue Text</span> several locations, built one at a time over the next several years.  
					Locations are designed to allow for access from major cities on a single tank of gas.  
					They are also picked strategically for their resilience to the following:</p>

				<ul>
					<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">Perimeter Security with LP/OP's.</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">Strategic Entrance Plan with Choke Point</a></li>

				</ul>                      
			</div><!-- end col -->

		</div> <!-- end box -->






	</section><!-- end main-content -->




</div><!-- end middle-content -->