<article>

<header>
    <h1 class="red">Gary Williams<br />&mdash; F.I.R.E. Defensive Skills LLC</h1>
     
</header>


	<p>
	Since 2001, Gary Williams has been assisting others with development of life skills, self-esteem, and confidence.  Williams has made it his mission to ensure students are able to help themselves in any situation.</p><p>
Gary Williams is co-owner and founder of F.I.R.E. Defensive Skills LLC.  Williams has more than 15 years of formal training and experience in all phases of military and civilian law enforcement training.  
</p><p>Williams holds black belts in Tae Kwon Do, F.I.R.E. MMA, and has numerous professional certifications to include: Kansas Certified Law Enforcement Officer, Kansas Concealed Carry Instructor, U.S. Air Force Combat Arms Training & Maintenance, NRA Pistol, Rifle & Personal Protection Inside the Home Instructor, Aircrew Combat Tactics instructor, Basic SWAT operator, Simunitions instructor, Patrol Response to Active Shooter instructor, Mixed Martial Arts instructor, Certified Personal Trainer, Glock Certified Armorer, Taser instructor, Instructor in Nonlethal Individual Weapons, and Pressure Point Control Tactics Instructor.  Additionally, Gary trained Ugandan security contractors, and Iraqi military members in firearms and hand to hand combat techniques while deployed to Iraq in 2008.
</p><p>
Mr. Williams is married, and has one young child in the home.   Currently, he is a full time military member, and PT police officer.  Williams is a veteran of Operation Iraqi Freedom.
</p>
</article>
