<link rel="stylesheet" href="css/overlay.css" />
			<header>
						<h1 class="red">MSP is Hiring!</h1> 							
						<p class="small">Position: Content Marketer<br>Date of First Offer: September 24, 2012<br>Desired Hire Date: Sometime in October, 2012</p>  				 
			</header>
			<p>We're pleased to announce we have a Content Marketing position available.  This position is about creating and keeping momentum working for MSP's marketing efforts as we continue through our launch phase.  After launch, it's about making the Internet boil with buzz about MSP.<br>
			
			<br><strong>Is spreading the word about preparedness your dream job?</strong><br>If so... please continue reading about this position.</p>
			
			
			<div class="bar"></div>
						
			<article class="box">
								
								<header><h2>About the Position:</h2></header>
								
								<p>
This position is based around the following skill sets:
<ul><li>
Content Creation (Copywriter) for client ad campaigns and rel marketing.
</li><li>Campaign Optimization as well as some Search Engine Marketing / SEO.
</li><li>Analysis of tasks, timelines, projects, and results.
</li><li>Publishing a bi-weekly report for highlighting results and next milestones.
</li><li>Present report findings in person.  Speak with preppers at key client locations,
</li><li>Ability to maintain and strengthen MSP's relationships.
</li><li>Comfort in creating content for social media, youtube (yes you'd be on video), and writing for blogs.
</li></ul>
<br>
<br>This is a position for a prepper who has at least a novice to intermediate level background or education in marketing.<br>
			<i>(not to be rude, but this is not a position for a motivated prepper with a computer and hoping to pick up what skills they need on the job)</i><br><br>

We are a small company, so it is 90% likely that you'll help us with some other projects as well.
<br>Most people at MSP wear multiple hats.... it's just how we get the job done.
<br><strong>
You must be: Likeable, accountable, responsible, a hard worker, intelligent, full of integrity, and maintain a positive mental attitude.
</strong>
<br><br>
Because this position may allow you to work from home up to 75% of the time, it is REQUIRED that you have a suitable home workspace available for use.
We can discuss these details later. Essentially, a child and distraction free work environment in your home.

<br><br>
At our company, we give our team time freedom, independence, and a level of trust is required for this to work.
<br>As such, you must be self motivated, trustworthy, and hard working.
The right person will thrive in this environment.
<br><br>
Candidates should have the following qualities:
<ul><li>Strong academic record
</li><li>Ability to Lead
</li><li>Detail Oriented
</li><li>Comfort on Youtube, comfort writing... both are a must.
</li><li>High level of self-motivation; ability to accomplish goals independently
</li><li>Multi tasking and time management skills
</li><li>A native business sense and analytical mind
</li><li>Entrepreneurial, and positive attitude
</li><li>*** Articulate and well-spoken; strong interpersonal, communication and presentation skills ***
</li><li>Highly Internet savvy with knowledge of SEM, SEO, Adwords, Social Media Marketing, Lead Generation, etc.
</li></ul>

<br><br>Extra Credit:<br>
Are you professionally familiar with <b>Kenshoo</b>? If so, be sure to let us know this. It's not required, but helpful.
<br><br>
COMPENSATION<br>
$10 to $14/hr base pay, based upon qualifications
<br>This position may well be a full time position, depending on your experience.
<br>
Possibility for income and skills growth within our company.
<br><br>
INQUIRIES<br>
Inquire by sending resume, up to 5 links of relevant marketing works (describe your roll in the project pls).<br>
Don't forget to tell us what specifically qualifies you for our position.<br>
Email us your inquiry.  Send to info [at] mainstream preppers dot com<br>
Phone and in person inquiries are not accepted, though such appointments are part of the interview process later on.<br>
For extra attention, include a link to an unlisted (therefore private) YouTube video less than 2 minutes long, introducing yourself and your qualifications (optional).<br>
Don't forget to tell us your city/state please.<br>
<br>
<strong>We thank you for your interest.</strong>
</p>
									
				</article><!-- end other -->




