

<div id="main-content" role="main">



	<div class="blue-bg clear">

		<section class="what-is">   

			<div class="wrapper">  

				<header>
					<h1 class="red">Prep School Cashflow & Budget</h1>                     
				</header>                                                                                        

			</div>  <!-- end wrapper -->            

			<div class="ribboncorners"></div>

		</section> <!-- end what-is -->           

		<div class="clear"></div>


	</div><!-- end blue-bg -->    


	<section>




		<div class="box">                       

			<h3>Startup Phases</h3>

			<p>The business will be launched with "first adopters" who see the value and opportunity in <a href="mission">our mission</a>.  
			This applies to customers, who will see incentive through discount.  It applies to instructors, who will see incentive through ground floor entry leading to higher income (more on this later).  It also applies to marketers and investors, who will have an opportunity to help launch this business and see nice rewards for their energy and capital.</p>
			<h4>Phases:</h4>
			<ol class="decorated">
				<li>Launch on July 4, 2012</li>
				<li>July 30: 500 First Adopter (free trial) customers, 3 Instructors, 3 Marketers, 2 Investors. </li>
				<li>October 30: Operationally afloat w/ 250 paying customers, 5 Trainers, Marketing Funds Funnel working.</li>
				<li>By Nov 30: 500 customers, website back end (alpha) in place.</li>
			</ul>                      
		</div> <!-- end box -->





		<div class="box">                       

			
						
				<h3>Revenue Model</h3>

				<p>After paying our bills each month, any profits will be split as follows:</p>



				<ul class="decorated">
					<li><strong>First 10%: Reserved for God's work.</strong><br />
					<i>Possibly going to a mission, establishing a food pantry, or towards a Torah observant retreat/community.</i></li>
					<li><strong>30%: Instructor Compensation</strong><br />
					<i>Guest Instructor Fees + Recurring Income for Key Instructors</i></li>
					<li><strong>20%: Marketing</strong><br /><i>FB/YT/Adwords/Email/Sponsorship/Social Media, SEO.</i></li>
					<li><strong>20%: Investor Rewards*</strong><br />
					<li><strong>10%: Growth of Operations</strong></li>
					<li><strong>10%: Special Project Fund</strong><br />
					<i>Wanna Do Something BIG?  This will help fund it.<br />Also it's the oh $#!^ we need cash fund.</i></li>
				</ul>                      
				<h5>* note: Until 400 active members or January 1, 2013:<br>
				Investor Rewards will go towards the Trainer Compensation.</h5>
							
				
	

					
		</div> <!-- end box -->




	</section><!-- end main-content -->




</div><!-- end middle-content -->