

 <div class="sticky">

	    <a href="network#join" class="cboxElement red-button">Sign Up<h2 class="free">FREE</h2></a>
    
    
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->
 
 
 <script>
 
$(document).ready(function() {
 	$('.fancybox-inline').fancybox( 
	);
});
 </script>
 

<div id="main-content" role="main">

		<link rel="stylesheet" href="css/natgeo.css">


      <div class="blue-bg">
	  
	  				<section id="natgeo">
					
						<header>Mainstream Preppers at Featured on Doomsday Preppers on National Geographic Network</header>
						
						<div class="wrapper">
						
						<div class="content">
						
							<!-- use this code when video is NOT ready		--> 				
						
							<a href="#soon" id="watch-natgeo" class="fancybox-inline"><img src="images/natgeo/watch-msp-natgeo-soon.png" 
							title="Watch MSP on National Geographic Channel - COMING SOON!" /></a>
							
							<div id="soon" style="display: none; text-align: center; padding: 10px;">
								<h1 class="red">Response video coming soon!</h1>
								<p>Join us today and we&rsquo;ll notify you when the video is ready!</p>
							</div> 
							
							
							<!-- use this code when video is ready 
							
							
							<a href="#watch" id="watch-natgeo" class="fancybox-inline watch-natgeo">Watch Mainstream Preppers on National Geographic Now!</a>
							
							<div id="watch" style="display: none; text-align: center; padding: 10px;">
								<iframe width="560" height="315" src="https://www.youtube.com/embed/9sVZM7MX9Zw" frameborder="0" allowfullscreen></iframe>
							</div>
							
							-->
							
							
							
							<form id="responsevid-form" action="#">
							
								 
								
								<h1>View Our Response Video &amp; More!</h1>
								
							 
								<ul>
								
									<li><b class="green">FREE ACCESS</b> to Our Prepper Network</li>
									<li><em class="cyan"><b>Coming Very Soon</b></em>: View Our Response Video &amp;<br />Show Discussion Thread </li>
									<li><b class="green">Bonus:</b> MSP Training Course - FREE!</li>
								</ul>
								
								<input type="email" class="required" id="emailaddress" name="emailaddress" value="Enter Your Email">
								<input type="text" class="required" id="zip" name="zip" value="Zip Code">
								<input type="submit" name="submit" value="Join Us" class="form-btn ">
								<div id="messageBox"></div>
							
							
							
							</form>
						
						
						</div><!-- end content -->
						
						</div><!-- end wrapper  -->
						
					
					</section><!--- end natgeo-->
	  
                       
                                <section id="home-banner" >
                                       
                                       <header>
	                                       <h1 class="plaintext">Thriving through good times and bad</h1> 
                                       </header> 
                                       
                                       <div id="plan-options">
                                       		<h3>We teach self reliance + strength in numbers.  Join Us!</h3>
                                            
                                            <nav>
                                                    <ul>
                                                    	<li>
                                                                <a href="network">
                                                                	<img src="images/free-flag-vertical-green.png" title="Free to join!" alt="Join our Free Network" class="free-vertical"/>
                                                                    <strong>Join the <br>
																	Network</strong>
                                                                    	Find Prepper Groups
                                                                    </a>
                                                        </li>
                                                    	<li>
                                                                <a href="prepschool">
                                                                    <strong>Get <br>
																			Training</strong>
                                                                 	   We Teach Self Reliance
                                                                    </a>
                                                        </li>
                                                    	<li>
                                                                <a href="retreats">
                                                                    <strong>Join a <br>
																			Retreat</strong>
                                                                    	Strength in Numbers
                                                                    </a>
                                                        </li>
                                                    	<li class="last">
                                                                <a href="paradise">
                                                                    <strong>Prepper&rsquo;s <br>
																			Paradise</strong>
                                                                   	Community Homesteading
                                                                    </a>
                                                        </li>
                                                    
                                                    </ul>
                                            </nav>
                                            

                                       
                                       </div><!-- end plan-options-->
                                        
                                        
                                 </section>
                                        
           
                    </div><!-- end blue-bg -->                    
                                 


</div><!-- end middle-content -->



<section id="blog" class="box">

	
	<br>
	
                                   <a href="index#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>

	<div class="clear"></div>			
</section><!-- end blog -->

