<div id="main-content" role="main">


    <div class="blue-bg">
    
      <link rel="stylesheet" href="css/fb.css" />
                       
                                <section id="home-banner" class="fb-landing">
                                       
                                       <header>
	                                       <h1>Replace Your Fear with Skills and Gear</h1>                                          
                                       </header>
                                       
                                      
                                       
                                       <div id="plan-options">
                                       		<h3>We teach self reliance + strength in numbers.  Join Us!</h3>
                                            
                                            <nav>
                                                    <ul>
                                                    	<li>
                                                                <a href="/network">
                                                                	<img src="images/free-flag-vertical-green.png" title="Free to join!" alt="Join our Free Network" class="free-vertical"/>
                                                                    <strong>Join the <br>
																	Network</strong>
                                                                    	Find Prepper Groups
                                                                    </a>
                                                        </li>
                                                    	<li>
                                                                <a href="/prepschool">
                                                                    <strong>Get <br>
																			Training</strong>
                                                                 	   We Teach Self Reliance
                                                                    </a>
                                                        </li>
                                                    	<li>
                                                                <a href="/retreats">
                                                                    <strong>Join a <br>
																			Retreat</strong>
                                                                    	Strength in Numbers
                                                                    </a>
                                                        </li>
                                                    	<li class="last">
                                                                <a href="/paradise">
                                                                    <strong>Prepper&rsquo;s <br>
																			Paradise</strong>
                                                                   	Community Homesteading
                                                                    </a>
                                                        </li>
                                                    
                                                    </ul>
                                            </nav>
                                            

                                       
                                       </div><!-- end plan-options-->
                                        
                                        
                                 </section>
                                        
           
                    </div><!-- end blue-bg -->                    
                                 


</div><!-- end middle-content -->

<!--


<section id="blog" class="box">


	<aside class="sidebar">                  
		<nav>
			<ul>                
				<li>
					<a href="#">FAQ
						<span>Frequently Asked Questions</span>
					</a>
				</li>
				<li>
					<a href="#">ABOUT
						<span>About Mainstream Preppers</span>
					</a>
				</li>
				<li>
					<a href="#">NEWS
						<span>Prepping in the News</span>
					</a>
				</li>

				<li>
					<a href="#">FREE
						SMS Alerts
						<span>Receive Alerts for Free</span>
					</a>
				</li>
				<li>
					<a href="#">EXECUTIVE PREPPERS
						<span>Prepping for business&hellip;Ask us how!</span>
					</a>
				</li>
			</ul>            
		</nav>          

	</aside>          


	<div class="posts">

		<header>
			<h1>Recent Articles on Prepping:</h1>          
		</header>



		<article>
			<header>
				<h1><a href="#">There's no "I" in Prepared</a></h1>
				<h5 class="meta">By <a href="#" rel="author">John Doe</a>, <time datetime="2013-01-01">01/01/2013</time></h5>
			</header>
			<p>
				Give excerpt text Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
				Vestibulum at odio sit amet elit faucibus rutrum et vel metus. In vel nibh nibh, 
				Give excerpt text Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
				Vestibulum at odio sit amet elit faucibus rutrum et vel metus. In vel nibh nibh, 
				ac pharetra tortor. Vestibulum at odio sit amet elit faucibus rutrum et vel metus. In vel nibh nibh, ac pharetra tortor...
				<a href="#" class="continue-reading" rel="">[ READ MORE ]</a>
			</p>          
		</article>

		<article>
			<header>
				<h1><a href="#">We wrote "<em>The Book on Prepping</em>"!</a></h1>
				<h5 class="meta">By <a href="#" rel="author">John Doe</a>, <time datetime="2013-01-01">01/01/2013</time></h5>
			</header>
			<p>
				Give excerpt text Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
				ac pharetra tortor. Vestibulum at odio sit amet elit faucibus rutrum et vel metus. In vel nibh nibh, ac pharddetradd tortor...
				<a href="#" class="continue-reading" rel="">[ READ MORE ]</a>
			</p>          
		</article>

		<article>
			<header>
				<h1><a href="#">The Prepping Paradigm Shift</a></h1>
				<h5 class="meta">By <a href="#" rel="author">John Doe</a>, <time datetime="2013-01-01">01/01/2013</time></h5>
			</header>
			<p>
				Give excerpt text Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
				Vestibulum at odio sit amet elit faucibus rutrum et vel metus. In vel nibh nibh, 
				ac pharetra tortor.
			</p> 
			<p>
				Vestibulum at odio sit amet elit faucibus rutrum et vel metus. In vel nibh nibh, ac pharetra tortor...
				<a href="#" class="continue-reading" rel="">[ READ MORE ]</a>
			</p>               
		</article>

		<article>
			<header>
				<h1><a href="#">Prepping in the Media</a></h1>
				<h5 class="meta">By <a href="#" rel="author">John Doe</a>, <time datetime="2013-01-01">01/01/2013</time></h5>
			</header>
			<p>
				Give excerpt text Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
				Vestibulum at odio sit amet elit faucibus rutrum et vel metus. In vel nibh nibh, 
				ac pharetra tortor. Vestibulum at odio sit amet elit faucibus rutrum et vel metus. In vel nibh nibh, ac pharetra tortor...
				<a href="#" class="continue-reading" rel="">[ READ MORE ]</a>
			</p>          
		</article>



	</div>
	-->
	<!-- end posts -->
	
	<!--
	<footer class="clear"> 
		<a href="#" class="view-all-articles blue-rounded-btn animate-hover">View More Articles</a>
	</footer>
	-->
	<div class="clear"></div>			
</section><!-- end blog -->

