

    
    
   
 <div class="sticky">

    <a href="#" class="iframe cboxElement red-button">
	 	Join Now  	<h2 class="free">FREE</h2>
    </a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="#" class="twitter">Twitter</a>
		<a href="#" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="#">
		Ask a question
    </a>

 </div><!-- end sticky -->
  
    
    



	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>BUG OUT RETREATS</h1>                      
					</header>


					<div class="content">

						<h2 class="question">
							What is a Bug Out Retreat?
						</h2>

						<p>
							A <a href="http://en.wikipedia.org/wiki/Retreat_%28survivalism%29">bug out retreat</a> is a place of refuge for those who in the preparedness/survival movement.  Often called a "Bug Out Location" or "BOL", they are a self sufficient, secluded, easily defended, homestead that would be used in troubled times to escape the chaos, violence, and other effects of possible threats and disasters.</p>
							<p>
								Within a tank of gas of your home, a secure bug out retreat maintains at the ready stores of food and water, clothes, medical and other supplies, off grid power, and more.  Ready for your arrival a moment's notice.</p>


							</div><!-- end content -->    

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>

					<div class="box">

						<h1 class="large">
							<span>Why</span> 
							would someone want to
							have a <br>Bug Out Retreat?
						</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>

							<div class="col">
								<h4 class="black">The Typical Bug Out Location</h4>
								<p>Most survivalists cannot afford to live at a rural retreat year round.  They have jobs, families, etc.  Many choose to setup their retreat for an 11th hour departure, quietly arriving and sustaining themselves for the duration of the chaos.</p>
								<p>Such a retreat is time consuming to build, tremendously expensive, and burdensome to maintain.  Limited space and supplies eliminates the possibility of inviting even friends and family.  You're on your own, and so are they.  You end up loan wolfing it, hoping to avoid threats at your retreat because you know a few men cannot possibly maintain operations and security 24x7 for very long.</p>

								<h4 class="black">Our Bug Out Retreats</h4>
								<p>Mainstream Preppers is forming professionally designed, year round maintained, self sufficient and secure retreats for those who wish to team up with like minded people and be prepared as a team.</p>
								<p>Can you grab your bug out bag and head to such a place today?  If not, go ahead and price the time/expense in setting one up.  If you'd rather work as a team and share the load/expense while developing advanced skills from experts, our retreat concept might be ideal for you.                                                                                                                  </p> 
							</div><!-- end col-->

							<div class="col">
								<h4 class="black">Reasons you might want a Retreat</h4>
								<ul>
									<li>Develop Self Sufficiency Skills</li>
									<li>Job Loss / Bankruptcy</li>
									<li>House Fire / Tornado</li>
									<li>Area Flood / Earthquake / Other Disaster</li>
									<li>Drought / Crop Failures / Food Supply Disruption</li>
									<li>Sustained Power Outage</li>
									<li>Social Unrest / Riots</li>
									<li>Economic Collapse</li>
									<li>Hyperinflation</li>
									<li>Martial Law</li>
									<li>EMP Attack, or Solar Flare</li>
									<li>NBC Warfare</li>
									<!--<li>Polar Shift</li> -->
									<li>Terrorist Attack</li>
									<li>Virus / Pandemic</li>
									<li>Zombie Apocalypse (just kidding!)</li>
								</ul>

							</div><!-- end col-->

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->   




					<div class="box network-map">


						<div class="map">
							<div class="description">
								<h4>Planned locations include:</h4>
								<ol>
									<li class="phase-one-text">Camden County, MO</li>
									<li class="phase-two-text">Montgomery County, AR</li>
									<li class="phase-three-text">TBD, IN</li>
									<li class="phase-four-text">Uruguay, South America</li>
									<li><a href="contact.php">Have Land?  Contact Us</a></li>
									<li><a href="contact.php">Hebrew Roots? Contact Us</a></li>
								</ol>

							</div><!-- end description-->

							<div id="hover-des"></div>

							<div class="map-legend">
								<div class="phase-one-color"></div>Phase One<br>
								<div class="phase-two-color"></div>Phase Two<br>
								<div class="phase-three-color"></div>Phase Three
							</div>


							<div class="phase-one phases"><img src="images/network-map-marker.png" title="Marker" class="marker"/></div>
							<div class="phase-two phases"><img src="images/network-map-marker.png" title="Marker" class="marker"/></div>
							<div class="phase-three"></div>

							<img src="images/network-map.gif" class="map-image" />                                   
						</div><!-- end map -->

						<div class="col">
							<h3>Locations</h3>

							<p>We plan on several locations, strategically located away from populated areas yet accessible via multiple routes without rest stops.
								They are also picked strategically for the following:
							</p>

							<ul class="">
								<li>~1 tank of gas from large cities</li>
								<li>Light population density</li>
								<li>Away from likely channels/drift</li>
								<li>Away from Nuclear Power Plants/Fallout</li>
							</ul>

						</ul>

					</div><!-- end col -->


				</div><!-- end network-map -->


				<div class="box">                       
					<div class="col">
						<h3>Retreat Design</h3>

						<p>We plan on several locations, built one at a time over the next several years.  
							Locations are designed to allow for access from major cities on a single tank of gas.  
							They are also picked strategically for their resilience to the following:</p>

							<ul class="decorated">


								<li>Securable Perimeter, Secluded</li>
								<li>24x7x365 Security</li>
								<li>Hardened exterior with no blind spots</li>
								<li>Strategic Entrance Path / Choke Points</li>
								<li>Listening Posts / <a href="http://en.wikipedia.org/wiki/Observation_post">Observation Posts</a> (LP/OPs)</li>
								<li>Man Trap Foyer</li>
								<li>Underground "Bunker"</li>


							</ul>                      

						</div><!-- end col -->

						<div class="col">
							<h3>The Homestead</h3>

							<ul class="decorated">
								<li><a href="overlay.html"  class="fancybox">Large Community Kitchen</a></li>
								<li><a href="overlay.html"  class="fancybox">Bath/Shower rooms</a></li>
								<li><a href="overlay.html"  class="fancybox">Community R&amp;R Space</a></li>
								<li><a href="overlay.html"  class="fancybox">Private Dorms with ample storage.</a></li>
								<li><a href="overlay.html"  class="fancybox">Gardens &amp; Greenhouses</a></li>
								<li><a href="overlay.html"  class="fancybox">Animals / Livestock</a></li>
								<li>Secure Storage Areas</li>

							</ul>                      

						</div><!-- end col -->                      

					</div> <!-- end box -->


					<div class="box">



						<div class="col">
							<h3>Retreat Infrastructure</h3>

							<p>A well planned retreat is not just secure, it's sustainable for extended periods of time.</p>

							<ul class="decorated">
								<li><a href="overlay.html"  class="fancybox">PACE Plan for Water</a></li>
								<li><a href="overlay.html"  class="fancybox">PACE Plan for Electricity</a></li>
								<li>Off Grid Redundant / Sustainable</li>
								<li><a href="overlay.html"  class="fancybox">Tornado Shelter</a></li>
								<li><a href="overlay.html"  class="fancybox">Huge, EMP resistant Faraday Cage</a></li>
							</ul>    

						</div><!-- end col -->

						<div class="col">
							<h3>Retreat Supplies</h3>

							<ul class="decorated">
								<li>1 year food</li>
								<li>3 months living expenses</li>
								<li>Multiple water sources & storage</li>
								<li>Operational gardens/greenhouses</li>
								<li>Supplies for use, charity, and barter</li>
								<li>Medical and Defense Supplies</li>
								<li>Communications Systems</li>

							</ul>                      

						</div><!-- end col -->   

					</div><!-- end box -->



					<div class="box">
						<div class="clear speech">

							<div class="speech-corner-r"></div>

							<h1>Is the Bug Out Retreat Concept for you?</h1>

							<div class="col">
								<div class="blue-ribbon">
									<h3>Current Cost to Join:</h3>
									<h1>$13,000 + $330/mo</h1>
									<p class="notice">- subject to change -</p>
								</div><!-- end blue-ribbon -->



								<a href="#" class="link-box">Payment plans available</a>
								<a href="#" class="link-box">Inquire for details</a>

							</div><!-- end col -->

							<div class="col">
								<h4 class="red">THE COST OF NOT JOINING?</h4>

								<ul class="decorated">
									<li><a href="#">What kinds of events can you not ride out in your home?</a></li>
									<li><a href="#">Do you feel these events are possible, or even likely to occur?</a></li>
									<li><a href="#">What does setting up your own retreat cost?</a></li>
									<li><a href="#">Can you achieve our level of preparedness/sufficiency alone?</a></li>
									<li><a href="#">How much will you learn with us in the next year alone?</a></li>
									<li><a href="#">How much is your family's security &amp; preparedness worth?</a></li>                               
								</ul>

							</div><!-- end col-->

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->


					<br>





					<div class="box">

						<div class="col">

							<a href="#" class="member-requirement iframe cboxElement">

								<h3>Member Requirements</h3>
								<span>Click to read the requirements</span>
								<span class="arrow">></span>
							</a>

							<article class="content">
								<header>
									<h3 class="red">Scholarships &amp; Discounts</h3>
								</header>

								<p>Scholarships and discounts may be available on a case by case basis for those with expertise in:
									<ul>
										<li>Medical / Paramedic / Nursing</li>
										<li>Security / Defense / Military Background</li>
										<li>Gardening / Greenhouse / Livestock</li>
										<li>Concrete Home Construction</li>
										<li>Preparedness Influence / Audience</li>
									</ul>


									Please describe any expert skills / training you may have when you request your member application.
								</p>
							</article><!-- end content -->

						</div><!-- end col -->


						<div class="col">

							<article id="stepstojoin">
								<header>
									<h3><span class="red">7</span> Steps to join</h3>
								</header>

								<ol class="steps-to-join">
									<li><span>Submit Application Form</span></li>
									<li><span>Interviews</span></li>
									<li><span>Members Vote</span></li>
									<li><span>Joining Fee: Placed in Escrow</span></li>
									<li><span>Criminal Background Check</span></li>
									<li><span>Drug Test</span></li>
									<li><span>Work/Training Weekends</span></li>                                                                    
								</ol>

								<a href="#" class="blue-rounded-btn animate-hover right iframe cboxElement">Request Application Form</a> 

								<div class="clear"></div>

							</article><!-- end stepstojoin -->                                


						</div><!-- end col -->

						<div class="clear"></div>

					</div><!-- end box -->
                    
                    
                    
                       
                       
                       <div class="box">
                                   <article class="further-reading-box">
                                                <header>
                                                        <h1>learn more, further reading:</h1>
                                                        <h2>Bug Out Retreat</h2>
                                                </header>
                                                
                                                <ul class="col">
                                                    <li><a href="#" class="currentpage">What is a Retreat</a></li>
                                                    <li><a href="#" class="currentpage">Why you need a BOL</a></li>
                                                    <li><a href="#">Retreat vs SIP (City)</a></li>
                                                    <li><a href="#">Retreat vs Rural House</a></li>
                                                    <li><a href="#">Mainstream Prepper Retreats Mainstream Prepper Retreats Mainstream Prepper Retreats</a></li>                                    
                                                </ul>      
                                                
                                                <ul class="col">
                                                    <li><a href="#">Current / Future Locations</a></li>
                                                    <li><a href="#">Membership Requirements</a></li>
                                                    <li><a href="#">Submit a Retreat Survey</a></li>
                                                    <li><a href="#">Join a Retreat (Application)</a></li>                           
                                                </ul>                    
                                            <div class="clear"></div>
                                   
                                   </article><!-- further-reading-box -->
                                   
                                   
                                   <a href="inside#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                       </div><!-- end box -->





				</section><!-- end main-content -->




			</div><!-- end middle-content -->
