


<div id="main-content" role="main">
                        
  <div class="blue-bg clear">

		<section class="what-is">   

			<div class="wrapper">  

				<header>
					<h1 class="red">Instructor Preview</h1>                     
				</header>                                                                                        


			</div>  <!-- end wrapper -->            

			<div class="ribboncorners"></div>

		</section> <!-- end what-is -->           

		<div class="clear"></div>


	</div>



		<link rel="stylesheet" href="css/course.css" />
		
				<section class="instructor-preview">
                
					 
					 	<ul class="instructor-list">
						
								<li class="red">
								
									<div class="categories">Preparedness Lifestyle</div>
										
										<div class="instructor-photo">
											<img src="images/course/instructor/joe-fox-big.jpg" title="Joe Fox" />
										</div>
										
										<div class="instructor-name">
												<p class="co">
													<img src="images/course/instructor/viking-prepareness-logo.png" title="Viking Prepareness" />
													Viking Preparedness
												</p><!-- end co-name-->
												<p class="fullname">
													Joe Fox
												</p>
										</div><!-- end instructor-name -->
										<p class="brief">20 years, Army Special Forces </p>
										
										<ul>
											<li>SERE Instructor </li>
											<li>Survivalist, Prepper, Author, Pastor</li>
											<li>Special Emphasis in Preparedness Lifestyle</li>
										</ul>
										
										<a href="joefox" class="see-bio fancybox">See Instructor&rsquo;s Bio</a>								
								</li>
								
								
						
								<li class="blue">
								
									<div class="categories">Aquaponics</div>
										
										<div class="instructor-photo">
											<img src="images/course/instructor/paul-range-160.jpg" title="Paul Range" />
										</div>
										
										<div class="instructor-name">
												<p class="co">
													
													Reliance Community Farms
												</p><!-- end co-name-->
												<p class="fullname">
													Dr. Paul Range
												</p>
										</div><!-- end instructor-name -->
										<p class="brief">Innovator & Instructor in Aquaponics</p>
	<ul>
	<li>Certified Permaculture Design Specialist</li>
	<li>Instructor in Permaculture, Water Storage, Canning, Dehydrating, Urban Survival & Emergency Preparedness</li>
	<li>Homesteader, featured on Doomsday Preppers Season 1</li>
	</ul>
	<a href="paulrange" class="fancybox see-bio">See Instructor&rsquo;s Bio</a>								
													</li>
								
								<li class="blue">
								
									<div class="categories">Economic Knowledge</div>
										
										<div class="instructor-photo">
											<img src="images/course/instructor/bill-still-160.jpg" title="Bill Still" />
										</div>
										
										<div class="instructor-name">
												<p class="co">
													
													The Money Masters
												</p><!-- end co-name-->
												<p class="fullname">
													Bill Still
												</p>
										</div><!-- end instructor-name -->
										<p class="brief">Expert on the US Monetary System</p>
										
										<ul>
											<li>Best Selling Author of over 20 books</li>
											<li>Award winning documentary writer/director</li>
											<li>Creator of the Money Masters</li>
											<li>Creator of <a href="http://www.secretofoz.com" target="_blank">The Secret of Oz</a></li>
											
											
										</ul>
							
										<a href="billstill" class="fancybox see-bio">See Instructor&rsquo;s Bio</a>								
								</li>
								
									<li class="red">
								
									<div class="categories">Firearms (Basic)</div>
																			
										<div class="instructor-photo">
											<img src="images/course/instructor/gary-williams-160.jpg" title="Gary Williams" />
										</div>
										
										<div class="instructor-name">
												<p class="co">
													
													F.I.R.E. Defensive Skills
												</p><!-- end co-name-->
												<p class="fullname">
													Gary Williams
												</p>
										</div><!-- end instructor-name -->
										<p class="brief">"Train Like You Fight"</p>
										
										<ul>
											<li>Certified law enforcement officer</li>
											<li>Active duty military member</li>
											<li>NRA certified instructor</li>
											<li>20yr martial arts practitioner</li>

										</ul>
										
										<a href="garywilliams" class="fancybox see-bio">See Instructor&rsquo;s Bio</a>								
								</li>	
								
								
						
								<li class="red">
								
									<div class="categories">Basic Preparedness</div>
										
										<div class="instructor-photo">
											<img src="images/course/instructor/zac-bauer-160.jpg" title="Zac Bauer" />
										</div>
										
										<div class="instructor-name">
												<p class="co">
													
													New 2 Torah
												</p><!-- end co-name-->
												<p class="fullname">
													Zachary Bauer
												</p>
										</div><!-- end instructor-name -->
										<p class="brief">Preparedness 101</p>
										
										<ul>
											<li>Former Infantry Soldier</li>
											<li>Firearms instructor, avid shooter</li>
											<li>Special Emphasis in Emergency Basics</li>
											<li>Learning and Teaching Torah</li>
										</ul>
										
										<a href="zacbauer" class="fancybox see-bio">See Instructor&rsquo;s Bio</a>								
								</li>
								
								
						
								<li class="blue">
								
									<div class="categories">Preparing your Finances</div>
																			
										<div class="instructor-photo">
											<img src="images/course/instructor/don-harrold-160.jpg" title="Don Harrold" />
											
										</div>
										
										<div class="instructor-name">
												<p class="co">
													
													The Day Trade Show
												</p><!-- end co-name-->
												<p class="fullname">
													Don Harrold
												</p>
										</div><!-- end instructor-name -->
										<p class="brief">Economic Preparedness</p>
	<ul><li>Get out of Debt</li><li>Stay out of Debt</li><li>Make More $$$ than you do today</li><li>Own Hard Assets</li>
	</ul>
	<a href="donharrold" class="see-bio fancybox">See Instructor's Bio</a>						</li>	
								
								
								<li class="blue">
								
									<div class="categories">Prepper Medical</div>
										
										<div class="instructor-photo">
											<img src="images/course/instructor/joe-amy-alton-160.jpg" title="Joe and Amy Alton" />
											
										</div>
										
										<div class="instructor-name">
												<p class="co">
													Doom and Bloom LLC
												</p><!-- end co-name-->
												<p class="fullname">
													Joe & Amy
												</p>
										</div><!-- end instructor-name -->
										<p class="brief">#1 Amazon Bestseller "The Doom and<br>Bloom(tm) Survival Medicine Handbook</p>
										<ul>
											<!--<li>Articles in Backwoods Home, Survivalist, Self Reliance Illustrated, and Survival Quarterly magazines</li>-->								<li>Joe is a Fellow of the American College of Surgeons and<br>the American College of OB/
Gyn</li>
											<li>Amy is an Advanced Registered Nurse Practitioner and a Certified Nurse-Midwife</li>
											
										</ul>
	<ul>
	</ul>
	<a href="doomandbloom" class="fancybox see-bio">See Instructor's Bio</a>				</li>
								
								
						
								<li class="red">
								
									<div class="categories">Firearms (Advanced)</div>
																			
										<div class="instructor-photo">
										
											<img src="images/course/instructor/invictus-160.jpg" title="Invictus AGI">
										</div>
										
										<div class="instructor-name">
												<p class="co">
												</p><!-- end co-name-->
												<p class="fullname">
													Invictus Alliance Group</p>
										</div><!-- end instructor-name -->
										<p class="brief">Veteran Owned Elite Professional Organization includes:</p>
	<ul><li>2 Green Berets & former Delta Force (Tom and Scot)</li>
	<li>2 Army Special Forces Veterans (Magnus and Jasper)</li><li>1 Marine Scout Sniper Instructor (Grant)</li>
	</ul>
	<a href="invictus" class="fancybox see-bio">See Instructor Bios</a>							</li>	
								
												
								
						</ul><!-- end instructor-list -->
						
						<div class="clear"></div>

				</section><!-- end instructor-preview -->




	</div><!-- end main-content -->
