
<link href="css/course.css" rel="stylesheet">


 <div class="sticky">

	<a href="application/signup" class="fancybox red-button">
		Sign Up Today
	</a>
    
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->






	<div id="main-content" role="main">


		<div class="blue-bg clear">



					<section class="instructor-page-header">   
					
							<div class="wrapper">  	
						
						<header>
							<h1>Prep School Instructor</h1>
						</header>
					
						<div class="instructor-description">					

							<h1>Viking Preparedness, LLC</h1>
							<h4 class="blue"><i>Prepared Americans for a Strong America</i></h4>
							
							<p>Joe Fox is a former Special Forces and intelligence officer who has studied and taught wilderness survival, combatives, and preparedness subjects to men, women and children for over 30 years. He is married with three adult children and lives on a self-sufficient homestead.
</p>
							
							<a href="http://www.VikingPreparedness.com" target="_blank">http://www.VikingPreparedness.com</a>						
						
						</div><!-- end instructor-info-->
						
						
						
						
						<div class="instructor-info">
							<h5>Instructor Info</h5>
								<img src="images/course/instructor/joe-fox.jpg" class="instructor-pic" title="Joe Fox" />
							<p>

								<span class="instructor-name">Joe Fox</span>
								<span class="instructor-subtitle">20 years, Army Special Forces</span>
							<p>
							
							<ul class="red-bullets">
							
								<li><p>SERE Instructor <a href="sere" class="fancybox">More info</a></p></li>
								<li><p>Survivalist, Prepper, Author, Pastor</p></li>
								<li><p>Special Emphasis in Preparedness Lifestyle</p></li>
								<li><p><a href="joefox" class="fancybox">Read Full Bio</a></p></li>
							</ul>

							<ul class="quick-overview">
								<li><a href="#" class="num-courses"><b>18</b> Courses</a></li>
								<li><a href="#" class="num-lessons"><b>291</b> Lessons</a></li>
								<li><a href="#" class="num-stars"><b>4/5</b> Stars</a></li>
								<li><a href="#" class="num-reviews"><b>5</b> Reviews</a></li>

							</ul>
						
							<div class="clear"></div>
							
						</div><!-- end instructor-info -->

				
						<div class="clear"></div>
						
							</div>  <!-- end wrapper -->            
				
							<div class="ribboncorners"></div>
							
							
							
								<div class="breadcrumbs">
									<a href="#">Home</a> > <a href="#">Prep School</a> > <a href="#">Viking Preparedness</a>
								</div>
								
								

					</section> <!-- end instructor-page-header -->    
					       

					<div class="clear"></div>
				</div><!-- end blue-bg -->    







<section class="box twocol" id="instructor-page-content">
       
          
                                  
                           <div class="right-col wide">
                                  
								  
								  <article class="next-event">
								 	 <div class="section-bar">NEXT EVENT</div>
								  		
										  <header>
											<h1>Survive, Escape, Resist, Evade</h1>          
										  </header>
										  
										  <div class="event-date-time-box">
											  <a href="#">
													<span class="location">Leavenworth, KS</span>
													<time datetime="10-28-2012T10:00-0600">
														<span class="event-month-date">Oct 11</span>
														<span class="event-time">10:00 AM - 10:00 PM</span>
													</time>
													
													<span class="seedetails">See Event Details <b>></b></span>
											  </a>
										  </div><!-- event-date-time-box -->
										  
										  <p>Excerpt text Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at odio sit amet elit faucibus rutrum et vel metus. 
										  In vel nibh nibh, ac pharetra tortor&hellip; <a href="#"><b>READ DETAILS &raquo;</b></a>
										  
										  
										  <div class="event-course-sign-up">
										  
										  		<ul>
														<li class="sign-up-before">
															<p>
															<b class="save">SAVE $50</b>
															<span class="before-date">when signup before August 15th</span>
															
															<div class="slot-open">															
																<span class="slot-num">16</span> SLOTS CURRENTLY OPEN.
															</div><!-- end slot-open -->
															
															<div class="pointer"></div>
															
														</li>
														
														<li>
															<a href="#" class="enroll-button">
																<b>Non-Member</b>
																<del class="regular-price">$295</del>
																<span class="discounted-price">$270</span>		
																<span class="button">Enroll</span>													
															</a>														
														</li>
														
														
														<li class="last">
															<a href="#" class="enroll-button">
																<b>Member</b>
																<del class="regular-price">$175</del>
																<span class="discounted-price">$150</span>	
																<span class="button">Enroll</span>															
															</a>														
														</li>
															
												
												</ul>
										  </div><!-- end event-course-sign-up -->
										  
										  
								  </article><!-- end next-event -->
                                  
								  
								  <a href="#" id="see-all-upcoming">Show All Events<span>&nbsp;</span></a>
								  									  
									<article class="upcoming-events">
										<header>
											<h1>all upcoming courses</h1>
										</header>
										
										<ul>
											<li>
												<a href="#">
														<time datetime="08-22-2012">
															<span class="event-month">Aug</span>
															<span class="event-date">22</span>
														</time>
														
														<h2>Women&rsquo;s Self Defense</h2>
														<p>Leavenworth, KS</p>												
												</a>
											</li>
											<li>
												<a href="#">
														<time datetime="08-30-2012">
															<span class="event-month">Aug</span>
															<span class="event-date">30</span>
														</time>
														
														<h2>Women&rsquo;s Self Defense</h2>
														<p>Leavenworth, KS</p>												
												</a>
											</li>
											<li>
												<a href="#">
														<time datetime="08-22-2012">
															<span class="event-month">Aug</span>
															<span class="event-date">22</span>
														</time>
														
														<h2>Women&rsquo;s Self Defense</h2>
														<p>Leavenworth, KS</p>												
												</a>
											</li>
											<li>
												<a href="#">
														<time datetime="08-30-2012">
															<span class="event-month">Aug</span>
															<span class="event-date">30</span>
														</time>
														
														<h2>Women&rsquo;s Self Defense</h2>
														<p>Leavenworth, KS</p>												
												</a>
											</li>
											
										</ul>
											
										
										  
										  
									</article><!-- end upcoming-events -->
								  
								  <img src="images/prepschool-comment.gif" title="comments"/>
								  
                                
                                  
                          </div><!-- end right-col -->
                          
    
	
          
                  <aside class="sidebar">                  
                            <nav>
                                <ul>                
                                    <li>
                                        <a href="#">What&rsquo;s New?</a>
                                    </li>
                                    <li class="hasChildren">
                                        <a href="#"><span class="show-hide">&#9660;</span> COURSES</a>
										<ul class="children">
											<li><a href="#">Women&rsquo;s Self Defense</a></li>
											<li><a href="#" class="course-group-title">Self Defense Handgun</a>
													<ul>
														<li><a href="#">Intro to Handguns</a></li>
														<li><a href="#">Every Day Carry 101</a></li>
														<li><a href="#">Marksmanship Level 1</a></li>
														<li><a href="#">Tactical Handgun 1</a></li>
														<li><a href="#">Marksmanship Level 2</a></li>
														<li><a href="#">Tactical Handgun 2</a></li>
													</ul>
											<li>
											<li><a href="#">Some Other Course</a></li>
										</ul>
                                    </li>
                                    <li>
                                        <a href="#">DVD&rsquo;S </a>
                                    </li>
                
                                    <li>
                                        <a href="#">EVENTS</a>
                                    </li>
                                    <li>
                                        <a href="http://drupal.vikingpreparedness.com/?q=node/46" target="_blank"><img src="images/course/survivalist-family-prepared-americans-for-strong-america.jpg" title="MUST READ! Survivalist Family Prepared Americans for a Strong America" /></a>
                                    </li>
                                </ul>            
                            </nav>          
                  
                  </aside>   
	
	
	
          			<div class="clear"></div>			
					
					
          </section><!-- end instructor-page-content -->




			</div><!-- end middle-content -->
