<div id="main-content" role="main">


		<div class="blue-bg clear">

                        
              		 <section id="instructorprogram-banner">   

                                                                        
                                    <div class="notice">
                                         We&rsquo;re Looking for <b>12 Key Instructors</b> with who want to join with MSP at the ground floor. <br />
                                        <b>Are you one of them? We offer significant perks for first adopters. </b><br />
                                Please read through our instructor program.  If interested, please <a class="fancybox" data-fancybox-type="iframe" href="contact">Contact Us</a>  to chat about the details.
                                    </div>
                                    
                                    <header>
                                        <h1>MSP instructor program. A Win-Win-Win Model.</h1>
                                        <h2>Instructors from around the country (and eventually probably internationally) are joining MSP as Instructors.  By doing this, they are forming a strategic partnership with MSP,
                                         a partnership we think can be a win-win-win (you, us & our members) provided we keep the #1 goal in focus: Awesome Training.</h2>
                                        
                                    </header> 
                        


					</section> <!-- end instructorprogram-banner -->    
                        
        

					<div class="clear"></div>


			</div><!-- end blue-bg -->    


		
				
				
		  


                                                                 
                                                
                <div class="box">
                                
                                <h1>HOW IT WORKS:</h1>
                                
                                <p>We know that what you&rsquo;re doing today already works.  <br>Working with Mainstream Preppers (MSP) doesn't change how you offer courses and training.  <b>We compliment it!</b></p>

<p>By partnering with MSP in a <b class="larger red">NON-EXCLUSIVE</b> relationship, you'll be heavily promoted and well compensated for working with us.  You'll be paid for live training signups and paid AGAIN when those trainings are viewed as on demand video courses in our online preparedness school.  Then paid AGAIN if/when you refer new members.</p>

<p>Your revenue may possibly explode when you join the largest and most comprehensive preparedness school in existence.  Mainstream Preppers is going to be a game changer in the prepper/survivalist/homsteading communities.<br><br>Would you like to be a part of it?</p>
                                    
                                    
                                    
                                    <div class="instructor-benefits-links">
                                  		<a href="instructorsprivate#exposure" class="exposure-link">MSP Will Bring You Exposure. More Info</a>
                                         	<a href="instructorsprivate#revenue" class="add-revenue-link">MSP Will Add to Your Revenue. More Info</a>
                                  		<a href="instructorsprivate#referrals" class="pay-referrals-link">MSP Will Pay You For Referrals. More Info</a>
                                    </div>     
                                    
                                    
                  </div><!-- end box -->
                                  

					<div class="box" id="exposure">
                    	<div class="left" style="width: 520px;">
                    		<h1>EXPOSURE</h1>
                            <p>MSP is developing the largest preparedness network in existence, 
                            and this includes people in your area.  We&rsquo;ll expose your business to survivalists, homesteaders, and preppers in your area that don&rsquo;t know about you.
                             We&rsquo;ll promote your courses and your events.</p>

							<p>Then, we&rsquo;ll invite people from across the nation to read your blog, like you on Facebook and subscribe to your YouTube channel.  
                            We&rsquo;ll include you in our newsletter and social media marketing. We will help you promote your gear, DVDs, etc. 
                            You&rsquo;ll be included in our handouts at trade shows and events. 
                            If you say something cool – we’ll retweet it and share it on Facebook (with credit as it&rsquo;s due).  Heck&mdash;we&rsquo;re even likely to help you rank better in Google because we&rsquo;ll link to your site from ours.</p>
			<p><strong>Bottom Line: MSP greatly increases exposure for its instructors.</strong></p>
                           </div> 
                            
                            
                            <div class="bookmarked-style right" >
                            
                            		<h3 class="blue">
                                    What&rsquo;s the cost<br />
for this exposure? </h3>
                                    <h1 class="red">NOTHING.</h1>
                                    
                                    <p>MSP hopes to make a profit someday of course, but we’re not going to do it at the expense of our instructors.
					<br><br>We spent months planning MSP so it's GREAT for our instructors.  We compliment what you already do.  We’re like an amplifier – we crank up the exposure dial.
										</p>
                            
                            </div><!-- end bookmarked-style-->
                            
							<div class="clear"></div><br />
                                        <div class="bar"></div>
                    </div><!-- end box -->
                    

                    
                    
                    <div class="box" id="revenue">
                    		<h1>REVENUE</h1>
                            
                                        <div class="quote-left ">
                                        <p>MSP has a unique and strong revenue model.  We're all about a win-win-win relationship. 
                                                We&rsquo;re going to put a spin on your training income that might just make you smile!
                                                </p>
                                        </div>
                                        
                                        
                                        <div style="margin-left: 370px;">
                                                <p><b class=" blue">FIRST</b> We&rsquo;re going to promote your events and help fill them up.  
                                                      <span class="indent"> &nbsp; You get all the $$$.</span></p>
            
                                                <p><b class="blue" >THEN</b> We&rsquo;re going to ask you to video the course and send it to us.     
                                                     <span class="indent"> &nbsp;That&rsquo;s where it gets exciting:</span> </p>
                                                     
                                                <p>
                                                MSP has a &ldquo;<a href="prepschool">Prep School</a>&rdquo;, as you probably know.  Our members enroll to access all of the course materials in our preparedness school.  
                                                They pay a monthly fee for this.  Every month, we add up the revenue received.  
                                                Then we take the largest chunk of that revenue and pay it back out to you, the instructor.<br />
            The best part? You&rsquo;re <b class="red">PAID PER VIEW</b>!</p>
                                        </div>
                                        
                                        
                                        <div class="clear"></div>
                                        <div>
                                        
                                        
                                        <div>
                                                            <br />
                                                            
                                                             <blockquote class="right">
                                                                          <span>&ldquo;</span> You will get paid for  the views that happen this month, next month, heck &mdash; next year!<span>&rdquo;</span>
                                                           </blockquote>
                                                            
                                                            <p>
                                                            <b>Yep, that&rsquo;s right, you’re PAID PER VIEW.  Here&rsquo;s how: </b></p> 
                                                            
                    
                                                           
                                                        <p>Every month we tally the views and customer ratings of all your 
                                                        courses.  These counts, plus a few other metrics, add up to your 
                                                        score.  Every instructor has a score.  We look at your score&rsquo;s % of 
                                                        the total score of all instructors, and that&rsquo;s the % of the instructor 
                                                        payout that you&rsquo;ll get.  Simple.  Fair. Lucrative.<p>
                                                        
                                                        <p>Here&rsquo;s the best part: you will get paid for the views that happen this month, next month, heck – next year!  You’ll be getting a check for trainings you did in 2012 in 2014… Plus, everyone that’s watched your course will be more tempted to ATTEND one of your future live courses, b/c they can see the value! Right now you have to keep doing trainings to earn a paycheck.  MSP pays residual income, forever!</p>
                                                        
                                                        <h4><br />
<b class="black">We sweeten the pot with some specific features:</b><br /><br />
</h4>
                                                        
                                                        <div class="num-box">
                                                        		<span class="num">1</span>
                                                                
                                                                <h1>Prerequisite Courses:  </h1>
																<p>These are level 1 and 2 courses that a prep school member must complete before they get into level 3 (just like in college).  This increases your views, therefore your income. </p>
                                                        </div><!-- end num-box -->
                                                        
                                                        
                                                        <div class="num-box last">
                                                        		<span class="num">2</span>
                                                                
                                                                <h1>Member Ratings  </h1>
																<p>Our members will rate your course and share their review of the course.  This vastly increases the number of views you receive (provided the feedback &amp; rating is good).  
We love free market solutions!</p>
                                                        </div><!-- end num-box -->
                                                        
                                                        
                                                                                                                
                                                        <div class="num-box" style="height: 360px;">
                                                        		<span class="num">3</span>
                                                                
                                                                <h1>Frequent New Courses</h1>
																<p>We will pimp new courses and awesome courses as we see fit.  The cream will rise to the top.</p>

<p>We plan to emphasis a different area of preparedness/survivalism/homesteading each month, just to help focus member conversations and keep people varied in the type of courses they&rsquo;re taking.</p>
                                                        </div><!-- end num-box -->
                                                        
                                                                                                                
                                                        <div class="num-box last" style="height: 360px;">
                                                        		<span class="num">4</span>
                                                                
                                                                <h1>Six Figures Incentives </h1>
																<p>We have some seriously AMAZING incentives (6 figure incentives) for instructors that join NOW and help us build MSP from the ground up.  
                                                                        <b>We want 12 key instructors.  Are you one of them?</b></p>
                                                                        
                                                                        <p><b>You can join whenever, but if you join as a first adopter &mdash; you may earn 50% to 100% more than if you wait.</b></p>
                                                                        
                                                                                        <p class="text-center"><a href="comingsoon" class="fancybox"><img src="images/residual-revenue-estimator.gif" title="RESIDUAL REVENUE ESTIMATOR" /></a></p>

                                                        </div><!-- end num-box -->
                                                        
                                                        
                                                        <h3 class="blue text-center">
                                                                <i>We announce our phase 1 instructors on<br />
                                                                                July 31st, 2012.  Will you be one of them?
                                                                </i>
                                                         </h3>
                                                                
                                                           <br />
     
                                        				<div class="bar"></div>
                                         </div>
                                        
                                        
                                        
                            </div>
                            
                            
                    </div><!-- end revenue -->
                    
                    
                    
                    

					<div class="box" id="referrals">
                    
                    		<div class="col">
                            	<h1>REFERRALS</h1>
                                
                                <p>MSP realizes that our instructors will probably link to MainstreamPreppers.com from their websites, Facebook posts, YouTube channels, or all of the above.  </p>

<p>Our instructors with a large audience will literally feed thousands of visits to MSP, definitely increasing prep school enrollment and course views.  Well, we think that when instructors refer us customers, they should be compensated.</p>

<p>It&rsquo;s pretty simple: MSP will give instructors a unique referral code to include in the links they post.</p>

<p>You put the link in your video, post, or on your website &mdash; and we&rsquo;ll track all the people that visit through that link.  When they sign up for our prep school &mdash; we&rsquo;ll credit you for the referral.  You get paid.</p>

                            
                            </div><!-- end col-->
                            
                            
                            <div class="col">
                            
                                            
                                            <h3 class="red">Here&rsquo;s how referral compensation works:</h3>
                                            
                                            <ul class="arrow" style="marign-left:0">
                                                    <li>$20 per referral for first 50.</li>
                                                  <li>After 50 members, we&rsquo;ll pay you <b>RESIDUAL income for every month that your referrals continue their membership</b>.  If we&rsquo;re doing our jobs right as instructors and course width/depth, we think MANY people will remain members indefinitely. </li>
                                             </ul>
                
                
                
                                                                                                        <p class="text-center"><a href="comingsoon" class="fancybox"><img src="images/residual-revenue-estimator.gif" title="RESIDUAL REVENUE ESTIMATOR" /></a></p>
                                            <p>If you have an audience you influence, whether via Facebook, YouTube, etc &mdash; it&rsquo;s quite possible that you&rsquo;ll be able to generate a  3, 4 or 5 figure monthly income just from promoting Mainstream Preppers!</p>

                            
                            
                            </div><!-- end col-->
                    
                    
                    
                    
                    		<div class="clear"></div>
                    
                    
                    
                    </div><!-- end referrals-->
                    
                    
                    
                    <div id="requirements" class="box">
                    
                    
                                   <div class="col">
                                            <h4 class="red">INSTRUCTOR REQUIREMENTSs</h4>
                                            
                                            <ul class="red-bullets">
                                            
                                                <li><p>You cannot post a training in our prep school that is available free online.</p></li>
                                                <li><p>You are welcome to post it in the free tips area though.  You can suggest it for inclusion in our newsletter or social media marketing.</p></li>
                                                <li><p>You cannot charge MSP customers for a course that you're giving away free.</p></li>
                                                <li><p>You cannot charge MSP customers more a course than others are paying.</p></li>
                                                <li><p>For live events / trainings - Prep School members must receive at least a 50% discount.</p></li>
            
                                            </ul>
                                            
                                            <p>If you feel something is a big issue, <a href="contact" class="fancybox">talk to us</a>.  We might be able to propose another solution.</p>
                                            
                                   </div><!-- end col-->
                                            
                                            
                                  <div class="col">
                                  	<h4 class="blue">COURSE SUGGESTIONS</h4>
                                    
                                    <ul class="blue-bullets">
                                    
                                    	<li><p>Divide your course into modules (lessons).  Teach one module at a time, and consider editing any relevant Q&amp;A into that module.  If you can’t do this for some reason, we&rsquo;ll edit the video afterwards.</p></li>

                                    	<li><p>If a module builds on a prior module, start that module with a 30-90 second recap, highlighting the main points covered.  If you can&rsquo;t do this during the training, do it after and we can edit it in.</p></li>

                                    	<li><p>Always introduce yourself and your course in each module.  If this is not done at the time of live training, edit it in later.</p></li>

                                    	<li><p>We encourage your courses to be separated in to modules no larger than 1 hour.  Half hour modules are also great. </p></li>

                                    	<li><p>Lessons less than 15 minutes may be accepted but on a case by case basis.  Our members are looking for depth and details.</p></li>
                                    </ul>
                                            
                                   </div><!-- end col-->
                    
                    			<div class="clear"></div>
                    
                    </div><!-- end requirements -->
                    
                    <div class="box stripe-box">
                    
                    	<h3 class="black">We want 12 key instructors.  Are you one of them?</h3>
                        
                        <a href="contact" class="blue-rounded-btn animate-hover smaller fancybox"><h3 class="white">INSTRUCTOR SIGNUP</h3></a>
                        
                        <p><b>FOR QUESTIONS &ndash; <a href="contact" class="fancybox">CONTACT US</a></b> </p>
                    
                    </div>









				</div><!-- end main-content -->



