 <div class="sticky">

	<a href="contact" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->



	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>Become an Instructor</h1>                      
					</header>


						</div>  <!-- end wrapper -->      
												<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

				

				</div><!-- end blue-bg -->    


				<section>
 
						
					
							     


					<div class="box">

						<h1 class="large">
							<span>WHY</span> are Instructors joining on with Mainstream Preppers?</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>
							
							<div class="col">
								<p><strong>There are 4 main reasons:</strong></p>
								<ul class="decorated">
									<li>Exposure</li>
									<li>Revenue</li>
									<li>Residual Income</li>
									<li>To Help More People</li>
								</ul>

								<p><strong>Mainstream Preppers only adds to the success of an Instructor's business.  Everyone benefits.</strong></p>
														

							</div><!-- end col-->
							
							<div class="col">
								<p><strong>Why Instructors like Mainstream Preppers:</strong></p>
								<ul><li>Instructors do <b>NOT</b> work <u>FOR</u> us.  
								They work <u>WITH</u> us.</li><li>
								All Instructors are NON-EXCLUSIVE to MSP.<br>We do not limit ANYTHING they do.  No contracts.</li><li>
								Instructors retain the rights to ALL their content.
								</li><li>We fill their courses and pay them for it.
								</li><li>We bring them residual income every month.
								</li><li>We don't tell them how to run their business.
								</li><li>We're doing what we say we're going to do.</li></ul>
																
							</div><!-- end col-->

							

							<div class="clear"></div>
<p><strong>MSP is focused on its members & instructors receiving significant value from us!</strong></p>
<p>Instructors naturally want to have lots of students.  That's where value is created.  Mainstream Preppers supplies students.<br>
We don't have burdonsome rules or policies.  Instructors benefit from exposure, course signups, & new revenue streams.

<br><br>After checking out our program in detail, you kind of have to ask,<br>
<strong>Why <u>WOULDN'T</u> an instructor want to partner with Mainstream Preppers?</strong></p> 
								

						
						<div class="clear"></div>
						</div><!-- end speech -->

					</div><!-- end box -->   


					
					<div class="box">
					<h2>Want to Inquire about Becoming an Instructor?</h2>


						<div class="col">



							<article id="stepstojoin">
								<header>
									<h3>There's<br><span class="red">4</span> Steps:</h3>
								</header>

								<ol class="steps-to-join">
									<li><span><a href="contact" class="fancybox">Fill out an Inquiry Form</a></span></li>
									<li><span>Talk to us by telephone (15 min)</span></li>
									<li><span><a href="instructors.php">Read the Full Details</a></span></li>
									<li><span>Announce your First Course</span></li>
								</ol>

								<a href="contact" class="blue-rounded-btn animate-hover right fancybox cboxElement">Instructors - Inquire Here</a> 

								<div class="clear"></div>

							</article><!-- end stepstojoin -->                                


						</div><!-- end col -->
						<div class="col">
						<br><br><h3>Who's Already an Instructor?</h3>
						<article class="mark-your-calendar">
                          	  <header>
                              <h1>Mark Your Calendar</h1>
                              </header>
                              <ul>
                                    <li>
                                    <a href="instructors.php" class="cboxElement">
                                        <time datetime="2012-07-31">July <span>31</span></time>
                                        <h2>SPECIAL ANNOUNCEMENT:</h2>
                                        <p><b class="red">Key Instructors</b> will be<br />
											announced on July 31, 2012.</p>
    
    
                                    </a>
                                    
                                    </li>
                                    
                                    <li><p><b><a href="contact" class="fancybox">CLICK HERE TO SUGGEST AN INSTRUCTOR</a></b></p></li>
                                
                                </ul>
                                
     
    
                                <!--a href="comingsoon" class="fancybox cboxElement">
    
                                    <img src="images/mark-your-calendar.jpg" title="Meet Our Instructors on July 31st" />
                                </a-->
                            
                            </article><!-- end mark-your-calendar--></div>

						<div class="clear"></div>

					</div><!-- end box -->





				</section><!-- end main-content -->




			</div><!-- end middle-content -->
