


<div id="main-content" role="main">
                        
  <div class="blue-bg clear">

		<section class="what-is">   

			<div class="wrapper">  

				<header>
					<h1 class="red">Instructor Preview</h1>                     
				</header>                                                                                        


			</div>  <!-- end wrapper -->            

			<div class="ribboncorners"></div>

		</section> <!-- end what-is -->           

		<div class="clear"></div>


	</div>



		<link rel="stylesheet" href="css/course.css" />
		
				<section class="instructor-preview">
                
					 
					 	<ul class="instructor-list">
						
								
						
								
								<li class="red">
								
									<div class="categories">Food Production</div>
																			
										<div class="instructor-photo">
											
											<img src="images/course/instructor/marjory-wildcraft-160.jpg" title="Marjory Wildcraft" />
										</div>
										
										<div class="instructor-name">
												<p class="co">
													
													Backyard Food Production</p><!-- end co-name-->
												<p class="fullname">
													Marjory Wildcraft
												</p>
										</div><!-- end instructor-name -->
										<p class="brief"></p>
										
										<ul>
											
										</ul>
										
										<a href="joefox" class="fancybox see-bio">See Instructor&rsquo;s Bio</a>								
								</li>	
								
								
								
								
								
								
								
								
								
								
								
								
								
								
								
								
								
						
								<li class="blue">
								
									<div class="categories">Prepper Medical</div>
																			
										<div class="instructor-photo">
										</div>
										
										<div class="instructor-name">
												<p class="co">
													
												</p><!-- end co-name-->
												<p class="fullname">
													Billy Brooks
												</p>
										</div><!-- end instructor-name -->
										<p class="brief"></p>
	<ul>
	</ul>
	<!--<a href="#" class="see-bio"></a>-->							</li>	
								
								
								<li class="blue">
								
									<div class="categories">Food Storage</div>
										
										<div class="instructor-photo">
											
										</div>
										
										<div class="instructor-name">
												<p class="co">
													Noah's Pantry
												</p><!-- end co-name-->
												<p class="fullname">
													Mark Price
												</p>
										</div><!-- end instructor-name -->
										<!--<p class="brief">20 years, Army Special Forces </p>
										
										<ul>
											<li>SERE Instructor </li>
											<li>Survivalist, Prepper, Author, Pastor</li>
											<li>Special Emphasis in Preparedness Lifestyle</li>
											<li>4th line is last line of text</li>
										</ul>-->
										<a href="#" class="see-bio">See Instructor&rsquo;s Bio</a>								
								</li>
								
								
						
								<li class="red">
								
									<div class="categories">Basic Survival</div>
																			
										<div class="instructor-photo">
											
										</div>
										
										<div class="instructor-name">
												<p class="co">
						
												</p><!-- end co-name-->
												<p class="fullname">
													Fran Tully
												</p>
										</div><!-- end instructor-name -->
										<!--<p class="brief">20 years, Army Special Forces </p>
										
										<ul>
											<li>SERE Instructor </li>
											<li>Survivalist, Prepper, Author, Pastor</li>
											<li>Special Emphasis in Preparedness Lifestyle</li>
											<li>4th line is last line of text</li>
										</ul>-->
										
										<a href="#" class="see-bio">See Instructor&rsquo;s Bio</a>								
								</li>								
								
								
								
								
										<li class="red">
								
									<div class="categories">Prepper 101</div>
										
										<div class="instructor-photo">
											
										</div>
										
										<div class="instructor-name">
												<p class="co">
													
													Southern Plains Consulting
												</p><!-- end co-name-->
												<p class="fullname">
													Mark A Smith
												</p>
										</div><!-- end instructor-name -->
										
										<a href="#" class="see-bio">See Instructor&rsquo;s Bio</a>								
								</li>
								
								
						
								<li class="blue">
								
									<div class="categories">Wilderness / Survival</div>
																			
										<div class="instructor-photo">
											
										</div>
										
										<div class="instructor-name">
												<p class="co">
												Equip 2 Endure	
												</p><!-- end co-name-->
												<p class="fullname">
													Adam Francis
												</p>
										</div><!-- end instructor-name -->
										<!--<p class="brief">20 years, Army Special Forces </p>
										
										<ul>
											<li>SERE Instructor </li>
											<li>Survivalist, Prepper, Author, Pastor</li>
											<li>Special Emphasis in Preparedness Lifestyle</li>
											<li>4th line is last line of text</li>
										</ul>-->
										
										<a href="#" class="see-bio">See Instructor&rsquo;s Bio</a>								
								</li>	
								
								
								
								<li class="blue">
								
									<div class="categories">Security & Defense</div>
										
										<div class="instructor-photo">
											
										</div>
										
										<div class="instructor-name">
												<p class="co">
													
													FS Dallas
												</p><!-- end co-name-->
												<p class="fullname">
													Derek Ringlet
												</p>
										</div><!-- end instructor-name -->
										<p class="brief"></p>
	<ul>
	</ul>
	<!--<a href="#" class="see-bio"></a>-->							</li>
								
								
								
										<li class="red">
								
									<div class="categories">Homestead Consulting</div>
										
										<div class="instructor-photo">
											
										</div>
										
										<div class="instructor-name">
												<p class="co">
													
													Practical Preppers LLC	
												</p><!-- end co-name-->
												<p class="fullname">
													Scott & David
												</p>
										</div><!-- end instructor-name -->
										<p class="brief">Consultants and Personalities of "Doomsday Preppers"</p>
	<ul><li>David: the Infamous <i>SouthernPrepper1</i> on Youtube</li>
	<li>Scott: "Mr. Gasification" and <i>Engineer775</i> on Youtube</li> 
	</ul>
	<!--<a href="#" class="see-bio"></a>-->	</li>
								
								
								
											
												
								
						</ul><!-- end instructor-list -->
						
						<div class="clear"></div>

				</section><!-- end instructor-preview -->




	</div><!-- end main-content -->
