<article>

<header>
    <img src="images/course/instructor/invictus-logo.png" title="Invictus AGI"/>
											<h1 class="red">Invictus Alliance Group, Inc.</h1>
     
</header>


	<p>
	<h2>Qualifications</h2>
	Critical Infrastructure Subject Matter Expert consultants is comprised of four individuals that aggregately possess the following: 
<ul><li>72 years of military experience
</li><li>48 years as Green Berets
</li><li>18 years in Delta Force
</li><li>One of a kind resumes in all aspects of barrier defeat and breaching
</li><li>Extensive experience in Target Analysis (TA) and the conduct of Vulnerability and Threat Assessments (VTA) 
</li><li>Experience in the preparation for and formal delivery of presentations to the Nuclear Regulatory Committee due to formal inquiries and or regulatory violation findings
</li><li>Vast experience in the conduct of security assessments at both the Macro and Micro level
</li><li>7 years of Direct Action Combat experience, which provides a real world frame of reference for understanding terrorist mindset, tactics, techniques and procedure 
</li><li>Thousands of both detailed and contingency planning scenarios 
</li><li>5 years of direct work with scientists at the National Laboratories developing explosive breaching charges for US forces
</li><li>17 years of Tier One operation experience with breaching and infiltration operations
</li><li>48 years of experience as formal instructors, which enables us to train an audience of any size, in any area of interest that falls within our subject matter expertise</li></ul>
	
	
	<br><br>
	
	<h2>The Team</h2>
	<ul><li><img src="images/course/instructor/invictus-sara-160.png" title="Sara Dawdy" align="right"><strong>Sara Dawdy</strong>
<p>Sara is the focal point of our organization, and provides the vision and clarity required to turn our team's potential energy into business opportunity and reality. Sara's innate ability to craft and communicate the true "WOW" factor of what Invictus has to offer is pure genius.</p><br><br></li>

<li><strong>Jasper Davis</strong>
<p>Jasper is a veteran of 26 years, a Green Beret and a board member of Invictus Alliance Group. Jasper is our resident Sleeper Agent, always there to provide the uncommon wisdom and clarity our team needs, right when we need it. Jasper's quiet professionalism, utter loyalty to the team, and dogged focus on our success, provides the glue that holds our team together in the ever changing and non-linear world we operate in. </p><br><br></li>

<li><strong>Tom Spooner</strong>
<p>Tom is a veteran of 21 years, a Green Beret, a former member of Delta Force and co-founder of Invictus Alliance Group. Tom is our resident Problem Solver at all levels. Tom's vast experience working in an environment that required time sensitive problem solving and decision making, with strategic implications mandate that his wisdom and guidance be heard and implemented into all decisions made at our company. Tom’s vast scope of world-class capabilities makes him an irreplaceable asset, both our company and yours.</p></li>

<li><img src="images/course/instructor/invictus-magnus-160.jpg" title="Magnus Johnson" align="right"/><strong>Magnus Johnson</strong></li>
<p>
Magnus is veteran of 8 years, and a Green Beret.  Magnus is our resident Rain Maker. Due to Magnus's vast life experience, unconventional wisdom and ability to execute tasks of any size make him our go to guy in all that we do. We can always count on Magnus to come up with the one idea that no one else has thought of.</p><br><br></li>

<li><img src="images/course/instructor/invictus-grant-160.jpg" title="Grant Royal" align="right"/><strong>Grant Royal</strong></li>
<p>Magnus is veteran of 8.5 years, and a former Marine Scout Sniper instructor at Camp Pendleton, CA.  Grant has served in 3 combat deployments and has was the overall winner of the 2009 International Sniper Competition in Ft Benning, GA.  Grant has develeloped the Long Range Hunting program and is the resident expert on long range marksmanship at Invictus.</p></li>


<li><strong>Scot Spooner</strong></li>
<p>Scot is a veteran of 17 years, a Green Beret, a former member of Delta Force, and co-founder of Invictus Alliance Group.  Scot is our resident Point Man. Through years of being put in charge of men and held personally responsible for all of their actions, in the best and worst situations, has enabled Scot’s ability to make strategic decisions and courses of action come alive his second nature. Scot’s ability to move forward comfortably in uncharted and rough waters, is something that we have come to rely upon.</p></li></ul>

</article>
