<article>

<header>
    <h1 class="red">Joe Fox &mdash; Viking Preparedness</h1>
     
</header>


	<p>
	With parents serving in the US Foreign Service, Joe Fox grew up overseas and came to understand and appreciate a variety of cultures and environments.  An early interest in martial arts and outdoor adventures set the course for the rest of his life.  His family had to “bug out’ or evacuate their homes on several occasions during his childhood and he had a Bug out Bag before the term was coined.</p>
	
	<p>After college, Joe served initially in the US Army Infantry and then in Special Forces.  He commanded and led units all over the world and worked with and trained US and foreign militaries, Federal, State and Local law enforcement organizations and US governmental civilians.</p>
	
	<p>Upon retirement, Joe formed <a href="http://www.vikingpreparedness.com/" target="_blank">Viking Services LLC</a> &mdash; a security and preparedness training company which has trained men, women and children all over the US.  He wrote &ldquo;<a href="http://drupal.vikingpreparedness.com/?q=node/46" target="_blank">Survivalist Family &ndash; Prepared Americans for a Strong America</a>&rdquo; and also provides insights and tips on his <a href="http://www.youtube.com/user/VikingPreparedness" target="_blank">YouTube channel</a> and <a href="http://www.vikingpreparedness.blogspot.com/" target="_blank">blog</a>.</p>
	
	<p>His interests and skillsets span a wide range from hunting and butchering wild game, to food preservation and storage; to family home preparedness, to wilderness survival, to combatives of all kinds - from children’s self-defense to team operations.  He has studied Tae Kwon Do, Kung-Fu and Filipino Martial Arts in addition to various military combatives styles and programs.  He is an expert with a variety of weapons from sticks to knives to firearms of all types. Joe likes to run long distances (he has completed several 100 mile races and other ultra-marathons) and do CrossFit.</p>
	
	<p>Joe and his wife live on a self-sufficient homestead in the mid-west.  When not running Viking Services LLC, Joe serves as an international consultant on matters related to his military service, pastors a hundred year old church, and serves as a volunteer firefighter.  He is also currently working on his next book and helping to establish a self-sufficient intentional community.</p>
	

</article>
