

    
 <div class="sticky">

	<a href="contact" class="fancybox red-button">
	Send a Comment
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->



	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>The Doomsday Preppers After Show</h1>                      
					</header>



<!--					<div class="content">

						<h2 class="question">
							Did you spot Kevin Barber on Doomsday Preppers?
						</h2>

						<p>
<img src="images/kevinbarber.jpg " alt="Kevin Barber" align="right" width="305">

							Kevin Barber heads up the Marketing side of Mainstream Preppers.  He and his family recently <a href="http://en.wikipedia.org/wiki/Retreat_%28survivalism%29" class="fancybox">bugged out</a> to Costa Rica.<br /><br />
							A former resident of Kansas, Kevin Barber searched worldwide for the best place to setup a self reliant homestead that allowed him the ability to live afforably, grow food year round, live securely, raise a family and enjoy life.<br /><br />
							He found what he was looking for in Costa Rica.
			<br /><br />				
Quick Links:  <a href="http://members.mainstreampreppers.com/preppers/25-costaricaprepper">Kevin on MSP: Costa Rica Prepper</a> | <a href="http://www.facebook.com/costarica.prepper">Kevin Barber on Facebook</a> | <a href="http://www.MainstreamPreppers.com/network">Join Mainstream Preppers - Free!</a></p>
 							
							</div>
							-->
							<!-- end content -->    

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>
				
				
					<div class="box"> 

<h3 class="black">Here's the questions we received after the show:</h3>


				
							<div class="clear"></div>
							
							<p><strong>
					Kevin Barber after Doomsday Preppers, along with Mainstream Preppers Instructor Marjory Wildcraft:</strong><br><br>
					-- <b>PRESS PLAY</b> ON THE VIDEO BELOW --<br />
							<iframe width="840" height="430" src="http://www.youtube.com/embed/IEcvxi7h-UM" frameborder="0" allowfullscreen></iframe>
						</div><!-- end box -->   


					<a name="why"></a> 
					<div class="box">
					
						<h1 class="large">
							<span>15 Reasons</span> 
							Why Kevin Barber Chose Costa Rica:
						</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>
							<div class="col">
								<h4 class="black">Benefits of Living in Costa Rica:</h4>
								<ul><strong>Environment:</strong>
									<li>No Heat or A/C Required. Ever.</li>
									<li>Year Round Growing Season</li>
									<li>Fantastic Soil, Ample Rain</li>
									<li>Less Reliant on Fossil Fuels</li>
									<li>No Nuclear Power Plants</li>
									<li>Government with Acceptable Foreign Policy</li>
									
									<strong>Culture:</strong>
									<li>Costa Rican Culture of Self Reliance</li>
									<li>Culture of Growing their own Food</li>
									<li>Local Power (Hydro), Local Water, Local Food.</li>
									<li>Very little debt held by Costa Ricans</li>
									
									<strong>Lifestyle:</strong>
									<li>Cost of Living</li>
									<li>Wife can stay home / homeschool kids</li>
									<li>Safe, Awesome, Beautiful Place to Live</li>
									<li>Less effected by Economic Collapse</li>
									<li>Kevin could become 100% Debt FREE!</li>
								</ul>

							</div><!-- end col-->

							<div class="col">
								<h4 class="black">The easiest of Expat Options.</h4>
								<p>Of the countries Kevin Barber researched and visited, Costa Rica was by far going to be the easiest transition for his family and business.  Same time zone, quality internet/communications, afforable airfare, desirable culture, safe and heatlhy for children.
								<br /><br />This may sound weird, but Kevin had narrowed his choices to Springfield MO, Arkansas, or Costa Rica.</p>
								
								<h4 class="black">It's a Pro/Con Thing.</h4>
								<p>For Kevin, the pros outweighed the cons.  But, Costa Rica has no army to defend from invasion, they sit on the ring of fire for earthquakes and volcanoes, and imported goods cost quite a bit more than in the USA.</p> 
								
								<h4 class="black">Is it Worth It?</h4>
								<p>Kevin Barber hopes his move to Costa Rica helps him achieve the ideal life for his family.  So far he is very excited with how his move has worked out and he'll be posting regular updates to MSP members, so be sure to <a href="/network">join - free!</a></p>

								</div><!-- end col-->

							
							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->   


	<div class="box"> 


<h3 class="black">What's Kevin's link to Mainstream Preppers?</h3>

<p>
<img src="images/kevinbarber.jpg " alt="Kevin Barber" align="right" width="305">

Kevin Barber has played a key role in the launching of Mainstream Preppers.<br /><br />He helped craft the mission of Mainstream Preppers because he felt surely there are more people just like him.. preppers that wanted to learn, share, network, and adopt a group driven mindset/strategy when it comes to preparedness.<br /><br />
								You can <a href="/network">join the MSP network</a> if you agree with this mission.  It's free!
								<br /><br />
								Quick Links:  <a href="http://members.mainstreampreppers.com/preppers/25-costaricaprepper">Kevin on MSP: Costa Rica Prepper</a> | <a href="http://www.facebook.com/costarica.prepper">Kevin Barber on Facebook</a> | <a href="http://www.MainstreamPreppers.com/network">Join Mainstream Preppers - Free!</a></p>

</div></div>

<!--	<div class="box"> 


<h3 class="black">Are you also thinking of bugging out?</h3>


<img src="images/retreat-preview.jpg" class="image right" />
								<p>Mainstream Preppers helps preppers connect with skilled prepper groups and form bug out retreats.  <strong>
The combination of skills, gear, and self reliance would be difficult to match working alone.</strong><br><br>
								When thinking about retreats, note that the #1 ingredient is having a prepper group.  
								There is strength in numbers.  
								With the right group in place, the retreat is stronger, and much more affordable.
								<br>
								<br>Please Note:<br>
								This graphic is for illustration purposes only.   
								Any real retreat design would be kept confidential.
								</p>
								
				
							<div class="clear"></div>
 -->							
						</div><!-- end box -->   


   						<div class="box">
                                   <article class="further-reading-box">
                                                <header>
                                                        <h1>Get Involved with MSP!</h1>
                                                        <h2>Here's how:</h2>
                                                </header>
                                                
                                                <ul class="col">
                                         
                                                    <li><a href="network">Join our FREE Prepper Network</a></li>
                                                    <li><a href="selfreliance2">Online Preparedness School</a></li>
                                                    <li><a href="retreats">Looking to Bug Out?</a></li>
                                                   </ul>      
                                                
                                                <ul class="col">
                                                    <li><a href="http://facebook.com/costarica.prepper" target="_blank">Kevin Barber's Facebook Page</a></li>
                                                    <li><a href="http://facebook.com/mainstreampreppers" target="_blank">MSP on Facebook</a></li>
                                                    <li><a href="http://members.mainstreampreppers.com/preppers/25-costaricaprepper">Kevin Barber on MSP</a></li>        
                                                </ul>                    
                                            <div class="clear"></div>
                                   
                                   </article><!-- further-reading-box -->
                                   
                                   
                                   <a href="retreats#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                       </div><!-- end box -->



				</section><!-- end main-content -->




			</div><!-- end middle-content -->
