



	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>About Mainstream Preppers</h1>                      
					</header>


					<div class="content">

						<h2 class="question">
						How is this business going to work?</h2>

						<p>Mainstream Preppers aims to attract the right instructors, marketers, and customers so as to be successful in offering training, retreats, and homesteading as a lifestyle.</p>
						

							</div><!-- end content -->    

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>

					
				
					


				<div class="box">
				<h1 class="large">MOTIVATIONS</h1><div class="clear"></div>	                       
					<div class="col">
						<a href="network"><h3>Network</h3></a>

							<ul class="decorated">
								<li>Show preppers the # of preppers in their area</li>
								<li>Facilitate Coalition Building &amp; Social Collaboration</li>
								<li>Offer summary versions of <a href="prepschool">Prep School</a> trainings</li>
								<li>Be a source of timely news and relevant info</li>
								<li><strong>Invite users to be a part of trainings, events, etc</strong></li>
								


							</ul>                      

						</div><!-- end col -->

						<div class="col">
							<h3><a href="prepschool">Prep School</a></h3>

							<ul class="decorated">
								<li>Be the Fast Track for entering preparedness</li>
								<li>Help Preppers gain skills, experience, wisdom</li>
								<li>Build networks/teams, develop positive culture</li>
								<li>Make a positive impact on the lives of everyone we train</li>
								
							</ul>                      

						</div><!-- end col -->   
						<div class="clear"></div>	
                        
						<div class="col">
							<h3><a href="retreats">Retreats</a></h3>

							
							<ul class="decorated">
								<li>Gather and Strengthen like minded people</li>
								<li>Help People Join Quality Prepper Groups</li>
								<li>Improved the Lifestyle of Preppers</li>
								<li>Best Team, Best Skills, Best Gear, Best Retreat, Period</li>
							</ul>      

						</div><!-- end col -->
						

						<div class="col">
							<h3><a href="paradise">Homestead</a></h3>

							<ul class="decorated">
								<li>Simply Paradise for preppers seeking to homestead</li>
								<li>Homesteading provides culture and stability to retreats</li>
								<li>Homesteaders benefit from strength in numbers</li>
								<li>Amazing Value, Hard to Duplicate.</li>
								<li><a href="ifyoubuildit" class="fancybox">If you Build It, He Will Come</a></li>
								

							</ul>                      

						</div><!-- end col -->                     
							<div class="clear"></div>	


					</div> <!-- end box -->
					
	
					


					<div class="box">
				<h1 class="large">GOALS</h1><div class="clear"></div>	                       
					
							<p><b>Here is a quick/rough list of our goals:</b></p>
                            
							<ul class="decorated">
								<li>Don't Go Bankrupt</li>
								<li>Find Like Minded People.  Partner with a few of them.</li>
								<li>Make a HUGE Impact in Preparedness Training - Help People</li>
								<li>Build Prepper Retreat Groups.  Join a Retreat Group Ourselves.</li>
								<li>In time, transition to a homestead of our own.. the Prepper's Paradise</li>
							</ul>  
							
						<p>We hope you can see that it's not just about making money.
						<br>We do hope to turn a profit though so that we can do great things.</p>     <br />
               
						<h4>For more details or to ask questions, <a href="contact" class="fancybox">contact us</a>.</h4>  
							</p>


					 
						
						                    

					</div> <!-- end box -->


					<div class="box">
						<div class="clear speech">

							<div class="speech-corner-r"></div>

							<h1 class="red">Want to Get Involved?</h1>

							<div class="col">
								<div class="blue-ribbon">
									<h3>Current Phase:</h3>
									<h1>Lean Startup</h1>
									
								</div><!-- end blue-ribbon -->


							</div><!-- end col -->

							<div class="col">
								<h4 class="black">READY TO GET INVOLVED?</h4>

								<ul class="decorated">
									<li>Instructors Wanted</li>
									<li>First Adopters Wanted</li>
									<li>Investors Wanted</li>
									<li>Marketers Wanted</li>                               
								</ul>
								
								<a href="contact" class="blue-rounded-btn animate-hover right fancybox cboxElement">GET INVOLVED</a> 


							</div><!-- end col-->

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->




				</section><!-- end main-content -->




			</div><!-- end middle-content -->
