<article>

<header>
    <h1 class="red">Marjory Wildcraft &mdash; Backyard Food Production</h1>
     
</header>

<img src="images/course/instructor/marjory-wildcraft-family.jpg" title="Marjory Wildcraft and family" class="right image-border"/>

	<p>As Marjory&rsquo;s husband will tell you, when she gets passionate about something, well, she is like a bull dog with a stick in its chops.  Marjory jettisoned her career managing a successful investment company to address this lurking crisis and began to figure out the fastest, easiest, and funnest ways for an individual or family to grow food.</p>

	<p>The experience and training Marjory brings to any problem is impressive: an undergraduate degree in electrical engineering (with honors) and a master’s degree in psychology are just the beginning.  Add to that permaculture design certification, dozens of gardening, homesteading, and farming classes, and years of dedicated research and experimentation.</p>



<div class="left" style="width: 250px">


<img src="images/course/instructor/marjory-wildcraft-2.jpg" width="220" title="Marjory Wildcraft showing the ideal size for a beginners garden bed" class="image-border"/>

<img src="images/course/instructor/marjory-wildcraft-3.jpg"  width="220" title="Marjory produces about half of her own diet in this backyard garden" class="image-border"/>



</div>
<br />
	<p>Marjory explores from the mundane to the bizarre to find the easiest ways to grow food.  She draws from organic farming, permaculture, agroforestry, indigenous teachings, historical anecdotes, relief work in developing countries, and barefoot crazies living off the land illegally in National forests.</p>




	<p>The results are impressive.  Her video tutorial is used by over 250,000 people in over 30 countries around the world.  She is a highly regarded guest on radio and television shows as her passion is contagious.</p>

	<p>She grows about half of her own diet.  And the side benefits?  Marjory says her health is so improved she has feels like a teenager again.  She has recently taken up skate-boarding as a test that her reflexes and balance are really as good as they feel.</p>

</article>
