<article>

<header>
    <h1 class="red">Example Marketing Revenue</h1>
     
</header>
<!--
<h3>For Trainers / Bloggers / Youtubers / etc</h3>-->
<p>Let's say you have a blog or youtube channel and you opt to promote Mainstream Preppers:
<br>
<h4>Blog Post Recommendation Example: </h4>
<ul>
<li>~2000 people watch your vid or read your blog post</li>
<li>80% viewing are actually preppers (1600)</li>
<li>1/2 like the concept and check out this site (800)</li>
<li>Just 1 out of 20 signup for the <a href="prepschool">Prep School</a> (40)</li>
</ul>

<p>
Your Referral Fee in this example: ~$800 <i>(contact us for details)</i>
</p> 
<h5>Not Bad for 1 blog post or 1 video!!</h5>
<hr>
<!-- 40 x $20 one time = $800 -->

<h4>Have a larger audience?</h4>
<p>After 50 referrals it starts to get exciting as we'll pay you a residual revenue share!<br>
Let us show you how referring just 20 members/mo through your blog or YouTube channel would generate an income of over $5,000 plus a residual income of over $1,000/mo!<!-- 4800 initial plus $5/mo x 200 members --> <br>
<br>Organizations, Top Trainers, and motivated preppers: Refer 1,000 members and earn over $60,000 a year.<br>

Let's talk about how we might work together.  <a href="contact" class="fancybox">Drop us an Inquiry</a>.</p>
</article>
