
    
<!-- <div class="sticky">

	<a href="contact" class="fancybox red-button">
		Inquire Today
	</a-->
   <!--  
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div>end social -->
    
	<!--a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div> end sticky -->


<link href="css/member.css" rel="stylesheet">



	<div id="main-content" role="main">
                        
                            <div class="blue-bg clear" id="member-login" >
                            
                                <section>   
                                  
                                                    <header>
	                                                        <h1>Member Sign In</h1>                      													
                                                    </header>
													
													<div class="content">
															
															<form action="#" id="member-login-form">
															
															<div id="messageBox" style="display:none;">
															
																We are sorry.  We do not have the username and/or password combination you entered.<br />
																<span><a href="#">Join</a> Our Prepper Network or <a href="#">Sign up</a> Prep School Free Trial.</span>
															
															</div>
															
																<div>
																	<label for="emailaddress">Email</label>
																	<input type="email" id="emailaddress" name="emailaddress" value="Email or username"  class="required"/>
																	<div class="clear"></div>
																</div>
																
																<div>																	
																	<label for="password">Password</label>
																	<input type="password" id="password" name="password"  class="required"/>
																	<div class="clear"></div>
																</div>
																	
																	<a href="#" id="forgot">Forgot Password?</a>
																	
																	<input type="submit" value="Member Sign In" />
																	
																	<div class="clear"></div>
															</form>
															
															
													</div><!-- end content -->     
															
															<aside class="no-accounts">
																<div class="content">
																	<header>
																		<h2>Not Yet a Member?</h2>
																	</header>
																	
																	
																	<a href="#" class="join-network-link">Join the Prepper Network <span>Free</span></a>
																	<div class="or">OR</div>
																	<a href="#" class="join-prepschool-link">Join our Prep School <span>Free</span> Trial</a>
																	
	
																		<div class="clear"></div>
                      					
																</div><!-- end content-->
																														
															</aside><!-- end no-accounts-->      
															
																<div class="clear"></div>
                      					
				                  </section>        
                    
                                        <div class="clear"></div>
                                </div><!-- end create-profile-banner -->    

     <div class="clear"></div>
					<section>

                       
             <br />
                                	
                                
                         







				</section><!-- end section -->




	</div><!-- end main-content -->
