 <div class="sticky">

	<a href="contact" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->



	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>Our Mission: Change the Prepper Paradigm</h1>                      
					</header>


					<div class="content">
					
						
						<h2 class="question">What&rsquo;s the #1 thing most preppers are missing?</h2>
						
						<br />
                        					
	
					
						<h4 class="black">Popular Guesses Include:</h4>
						<div class="col">
							<div class="col">
								
								<ul><li>Food?</li><li>
								Water?</li><li>
								Medical Training?</li></ul></div>
								<div class="col">
								<ul><li>Gardens?</li><li>
								Goats?</li><li>Guns?</li>
								</ul></div>
							</div>
								
							<div class="col">
								<div class="col">
								<ul><li>Caches?
								</li><li>
								Diesel Fuel?</li><li>
								Honey Bees</li></ul></div>
								<div class="col">
								<ul><li>
								Potassium Iodine?</li><li>
								AA Batteries?</li><li>
								Bad Ass Kung Fu?</li> 
								</ul></div>
								
							</div>
								
								
							<h4 class="blue"><i>All potentially useful, but none of the above.</i></h4>
							
							<br>
							<div class="clear"></div>
							

						<h4 class="black">Need a Hint?   Find the source of strength below:</h4>
														
								<div class="col">
                                <ul class="no-margin">
                                <li>Native American Tribes</li><li>
								Farming Co-op</li><li>
								US Marines</li><li>
								Mastermind Groups</li>
								</ul></div>
                                
                                <div class="col">
                                <ul class="no-margin">
                                <li>
								The Fire Department</li><li>
								Husbands &amp; Wives</li><li>
								Seal Team 6</li><li>
								ER Doctors</li>
								</ul></div>
																
							<div class="clear"></div><br />
                            
							<h2 class="red">Answer: They work as a TEAM.  None can thrive alone.</h2>
							
							
<br />
					
                        
						
						</div><!-- end content -->    

						</div>  <!-- end wrapper -->      
												<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

				

				</div><!-- end blue-bg -->    


				<section>
 
						
					<!--div class="box">
	
					
						<h4>Popular Guesses Include:</h4>
						<div class="col">
							<div class="col">
								
								<ul><li>Food?</li><li>
								Water?</li><li>
								Medical Training?</li></ul></div>
								<div class="col">
								<ul><li>Gardens?</li><li>
								Goats?</li><li>Guns?</li>
								</ul></div>
							</div>
								
							<div class="col">
								<div class="col">
								<ul><li>Caches?
								</li><li>
								Diesel Fuel?</li><li>
								Honey Bees</li></ul></div>
								<div class="col">
								<ul><li>
								Potassium Iodine?</li><li>
								AA Batteries?</li><li>
								Bad Ass Kung Fu?</li> 
								</ul></div>
								
							</div>
								
								
							<h4 class="black">All potentially useful, but none of the above.</h4>
							
							<br><br>	<br><br>
							<div class="clear"></div>
							

						<h4>Need a Hint?   Find the source of strength below:</h4>
														
								<div class="col"><ul><li>Native American Tribes</li><li>
								Farming Co-op</li><li>
								US Marines</li><li>
								Mastermind Groups</li>
								</ul></div><div class="col"><ul><li>
								The Fire Department</li><li>
								Husbands & Wives</li><li>
								Seal Team 6</li><li>
								ER Doctors</li>
								</ul></div>
																
							<div class="clear"></div>
							<h2 class="black">Answer: They work as a TEAM.  None can thrive alone.</h2>
							
							

						</div--><!-- end box-->
							     


					<div class="box">

						<h1 class="large">
							<span>REJECT</span> the idea that prepping should be done in secret and in isolation.
						</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>
							
							<div class="col">
								<p><strong>There are basically 4 types of people:</strong></p>
								<ul class="decorated">
									<li>There will be Wolves</li>
									<li>There will be Sheep</li>
									<li>There will be Shepherds</li>
									<li>There will be Hermits</li>
								</ul>
								<p><strong>Which type should preppers be?</strong></p>
								<p><strong>Which type should YOU be?</strong></p>
								

							</div><!-- end col-->
							
							<div class="col">
								<p><strong>If you answered hermit...</strong></p>
								<p>We respect your view.  You have every right to prepare for yourself and your family.  We understand your mission, motive, and opinion.</p>
								<p><strong>But if we act together, we can do more.</strong></p>

								<p>Like minded preppers can work together to improve their own preparedness while also increasing awareness about preparedness.
								By working together as Mainstream Preppers, we can help change the image of prepping.</p>			
								<p><strong>Together, we can change the preparedness paradigm</strong>.</p> 
								
								
							</div><!-- end col-->

							

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->   


					
					<div class="box">
					<h3>HOW TO CHANGE THE PREPPING PARADIGM</h3>


						<div class="col">



							<article id="stepstojoin">
								<header>
									<h3><span class="red">4</span> Easy<br>Steps:</h3>
								</header>

								<ol class="steps-to-join">
									<li><span><a href="network">Join our FREE Network</a></span></li>
									<li><span>Plug Into Training</span></li>
									<li><span>Join a Retreat or Homestead</span></li>
									<li><span>Share the Concept</span></li>
								</ol>

								<a href="network" class="blue-rounded-btn animate-hover right iframe cboxElement">Join the Network - FREE</a> 

								<div class="clear"></div>

							</article><!-- end stepstojoin -->                                


						</div><!-- end col -->
						<div class="col">
						<h3>Is Mainstream Preppers Legit?</h3>
						<p>It's a reasonable question to ask about the motivations and ethics of this company before getting involved.
						<br><br>
						Please visit our <a href="management">management</a> page for more information about our motivations and goals.
						Then, <a href="contact" class="fancybox">contact us</a> with any specific questions.
						</p></div>

						<div class="clear"></div>

					</div><!-- end box -->





				</section><!-- end main-content -->




			</div><!-- end middle-content -->
