
 <div class="sticky">

    <a href="network#join" class="cboxElement red-button">
	 	Join Now  	<h2 class="free">FREE</h2>
    </a>
    
    
    
 
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->



	<div id="main-content" role="main">


	<div class="blue-bg clear">

				<section id="join-network-banner" class="form success">   
				<a name="join"></a>
							
							  
							  <div class="thankyou">  
									<h2>Thanks for Joining Our <b>FREE</b> Preppers Network!</h2>
									<p>We&rsquo;ll be contacting you very soon. In the main time, <b>keep up-to-date with us</b>:</p>
									
								
													<ul class="thankyou-list">
														<li><a href="http://www.facebook.com/MainstreamPreppers" class="facebook"><img src="images/facebook-icon-bigger.png" title="Facebook"/>Like us on Facebook</a></li>
														<li><a href="prepschoolsignup" class="free-trial"><b class="green"><span>Free</span> 90 Day Trial</b> <br /> Prep School Membership</a></li>
														<li><a href="https://twitter.com/#!/PrepperSkills" class="twitter"><img src="images/twitter-icon-bigger.png" title="Twitter"/>Tweet @PrepperSkills</a></li>
														
													</ul>
									
								</div>
                              

                             

				</section> <!-- end join-network-banner -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    

				<section>

					<div class="box">

						<h1 class="large">
							<span>It's Simple.</span> Join to improve your overall preparedness.
						</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>
							
							<div class="col">
								<p><strong>What you'll get when you join our network:</strong></p>
								<ul class="decorated">
									<li>Connect with people in your own back yard</li><li>
									Help organize preparedness in your area</li><li>
									Build coalitions with local preppers</li><li>
									Link up with preparedness groups</li><li>
									Professional Tips & Training</li><li>
									Our numbers give us bulk purchasing power</li><li>
									Discounts and Special Offers</li><li>
								</ul>
								<p><strong>Plus, it's FREE</strong></p>
								

							</div><!-- end col-->
							
							<div class="col">
								<p><strong>What it takes to sign up:</strong></p>
								<p>We respect your privacy.  All we need from you to join the network is an email address and your zip code.</p>
								<ul class="decorated"><li>Your email address let's us setup your account and send you updates.
								</li><li>Your zip code lets us update you on what is happening related to preparedness in your area.</li></ul>
								
								<p><strong>Did we mention that it's FREE?</strong></p>
								
								<a href="network#join" class="blue-rounded-btn animate-hover right cboxElement">Join the Network - FREE</a> 
								
								<!--
								<a href="newsletter/signup" class="blue-rounded-btn animate-hover right fancybox cboxElement">Join the Network - FREE</a> 
								-->
							</div><!-- end col-->

							

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->   





					<div class="box">

						<div class="col">

						

								<header>
									<h3>100% Risk Free</h3>
								</header>

								
									<ul>
										<li>If you don't like it, simply unsubscribe</li>
										<li>The tips/training we send is very worthwhile</li>
										<li>Having a local coalition only strengthens your preparedness</li>
										<li>Don't be Greedy. Share your discount codes with friends</li>
										<li>An easy way to help introduce new ppl to preparedness</li>
									</ul>


						</div><!-- end col -->


						<div class="col">

							<h3>Discounts & Offers</h3>
							<p>Network members will receive updates when we do bulk purchases of preparedness gear like cache equipment, survival gear, apparel, backup power system components, and much more.  
							<br><br>Plus, discounts on local trainings and events - just for being part of this FREE network!</p>
						</div><!-- end col -->    
				
<div class="clear"></div>
          <a href="network#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>


					</div><!-- end box -->





				</section><!-- end main-content -->




			</div><!-- end middle-content -->
