
    
<!-- <div class="sticky">

	<a href="contact" class="fancybox red-button">
		Inquire Today
	</a-->
   <!--  
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div>end social -->
    
	<!--a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div> end sticky -->



	<div id="main-content" role="main">
                        
                            <div class="blue-bg clear">
                            
                                <section id="welcome-network">   
                                  
                                                    <header>
                                                        <h1>Welcome to the Free Prepper Network</h1>                      
													
                                                    </header>
													
													
													<div class="zip-stats">
														<h2>Quick Stats For <span>Garden City, Massachusetts</span></h2>
														
														<div class="num">
															<div class="digit">0</div>
															<div class="digit">0</div>
															<div class="digit">9</div>														
														</div><!-- end num -->
														
														<div class="label">
															<h3>Preppers</h3>
															<p><b>Found within 500 Miles Radius </b><br />
																Full details in the Member&rsquo;s Area
															</p>														
														</div>
														
													</div><!-- end zip-stats -->
                                  					
										
                                
                                </section> <!-- end free-trial-banner -->           
                    
                                        <div class="clear"></div>
                                </div><!-- end blue-bg -->    


							<section>

 

					
     
                                
                                
                       
                                
                                	<section class="box" style="padding-top:0;"> 
                                        
                                         
                                          
                                         	  <link href="css/form.css" rel="stylesheet">
                                            
<br />
                                       				<h3 class="text-center blue">Your signup is not yet complete.</h3>
													 
												<div class="next-steps">
													 
													 <h1>Your Next Steps:</h1>
													 
													 <ol class="signup-nextsteps">
														 
														 <li><span class="num">1</span> Check your email now to confirm your address.
														 <p class="small">Didn&rsquo;t receive an email? <a href="contact" class="fancybox">Contact Us</a></p>
														 </li>
														 
														 
														 <li>
															 <span class="num">2</span> 
															
															 Connect with us on Facebook:
																	<div id="fb-root"></div>
																	<script>(function(d, s, id) {
																	var js, fjs = d.getElementsByTagName(s)[0];
																	if (d.getElementById(id)) return;
																	js = d.createElement(s); js.id = id;
																	js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=197063410401392";
																	fjs.parentNode.insertBefore(js, fjs);
																	}(document, 'script', 'facebook-jssdk'));</script>
																	
																	<div class="fb-like" data-href="http://www.facebook.com/mainstreampreppers" data-send="false" data-width="500" data-show-faces="true"></div>
													
														 
														 </li>
														 <li>
														 	<span class="num">3</span> 
															
															 Follow us on Twitter (optional):
															<br />
															 <a href="https://twitter.com/PrepperSkills" class="twitter-follow-button" data-show-count="false" data-lang="en" data-size="large">Follow @PrepperSkills</a>
															 <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
															 
															 </li>
															 
															 
															<li>
														 	<span class="num">4</span> 
															
															 Add a <b>FREE</b> Trial of our Prep School:
															 <i class="subtitle">Adding the Prep School is optional.  But it&rsquo;s risk free.  No obligation.  No credit card required.</i>
															 
			
																								 
																<form  action="#" method="post" id="networkty-sign-up-prep-school">   
																
																		<p><b>To Enroll, we only need your: </b></p>
																
													   
																		<input type="text" value="First Name"  name="firstname" id="firstname"  class="required noPlaceholder" />
																		<input type="text" value="Last Name (optional)"  name="optional" id="optional"  class="required noPlaceholder" />
																	   <input type="submit" class="form-btn " value="Sign Up" name="submit" />      
																	   
																  <div id="messageBox"></div>    
																  
																  <div class="clear"></div>
															   
																	   
																  </form><!-- end form-->
															 
															 
															</li>
															 
															 
															 
														 <li>
															 <span class="num">5</span> 
															 Create your <a href="#"><img src="images/avatar.gif" title="Member Profile Avatar" /> Member Profile</a>
															 <p class="small">This enables your access to the Prep School and Prepper Network.</p>
														 
														 </li>
													 
													 </ol>
													 
													
										
				
                                            
												</div><!-- end next-steps -->
												
												
												 
													 <p class="text-center"><b>Thanks for signing up for our Free Prep School Membership.</b>

      We look forward to working with you!<br />
     

      Have a question or comment? <a href="/contact" class="fancybox">Contact Us</a>
</p>
												
												
                                      
                                            
                                            
                              
                                            <div class="clear"></div>

	                                </section><!-- end twocol-->
                                
                                
                                	
                                
                         







				</section><!-- end section -->




	</div><!-- end main-content -->
