
    



	<div id="main-content" role="main">
		<div class="blue-bg clear">
			<section>   
				<div class="wrapper">  
					<header>
						<h1>You did it! This is the end of the internet!</h1>                      
					</header>
					 

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>

					<div class="box">
					
						 <img src="images/404-web-title.gif" alt="404. Content cannot be found" class="title-404"/> 
							
						<div class="content-404">				
							<h1>We are sorry but we cannot find what you&rsquo;re looking for. <br />
							May we suggest you to:</h1>
						 
							
							<ul>
								<li><a class="fancybox" data-fancybox-type="iframe" href="contact">Contact Us</a> &ndash; we&rsquo;d be happy to assist you!</li>
								<li>Check our <a href="http://members.mainstreampreppers.com">Member&rsquo;s Area</a> for the info you seek.</li>
								<li>Visit our <a href="/">Homepage</a> and start again.</li>
							</ul>
							</div>
								
					</div><!-- end box --> 
					
					<div class="clear"></div>
					
				</section>




			</div><!-- end middle-content -->
