<article>

<header>
    <h1 class="red">Heading</h1>
    <h4>Smaller heading</h4>
   
</header>

<img src="images/placeholder.jpg" class="image right" />

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum porta neque, eget consectetur risus pharetra eget. Aliquam vitae mi quis lacus consequat tincidunt porta vel ante. 
Vivamus eu venenatis arcu. Praesent tortor elit, volutpat ut auctor sit amet, 
convallis vitae dui. In hac habitasse platea dictumst. Integer bibendum eleifend enim, vitae sollicitudin justo condimentum rutrum. Quisque vulputate elit vitae arcu malesuada porta. Nullam et sapien nulla.</p>


<p>Lorem ipsum dolor sit amet, <a href="#">consectetur adipiscing elit</a>. Aenean fermentum porta neque, eget consectetur risus pharetra eget. Aliquam vitae mi quis lacus consequat tincidunt porta vel ante. 
Vivamus eu venenatis arcu. Praesent tortor elit, volutpat ut auctor sit amet, 
convallis vitae dui. In hac habitasse platea dictumst. Integer bibendum eleifend enim, vitae sollicitudin justo condimentum rutrum. <b>Quisque vulputate elit vitae arcu</b> malesuada porta. Nullam et sapien nulla.
</p>


          
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum porta neque, eget consectetur risus pharetra eget. Aliquam vitae mi quis lacus consequat tincidunt porta vel ante. 
Vivamus eu venenatis arcu. Praesent tortor elit, volutpat ut auctor sit amet, 
convallis vitae dui. In hac habitasse platea dictumst. Integer bibendum eleifend enim, vitae sollicitudin justo condimentum rutrum. Quisque vulputate elit vitae arcu malesuada porta. Nullam et sapien nulla.</p>


<p>Lorem ipsum dolor sit amet, <a href="#">consectetur adipiscing elit</a>. Aenean fermentum porta neque, eget consectetur risus pharetra eget. Aliquam vitae mi quis lacus consequat tincidunt porta vel ante. 
Vivamus eu venenatis arcu. Praesent tortor elit, volutpat ut auctor sit amet, 
convallis vitae dui. In hac habitasse platea dictumst. Integer bibendum eleifend enim, vitae sollicitudin justo condimentum rutrum. <b>Quisque vulputate elit vitae arcu</b> malesuada porta. Nullam et sapien nulla.
</p>


	<ul>          
          <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
          <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
          <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
  </ul>
  
	<ul class="decorated">          
          <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
          <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
          <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
  </ul>
  
   <ol>          
          <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
          <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
          <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
  </ol>



</article>
