
 <div class="sticky">

	<a href="contact" class="fancybox cboxElement red-button">
		Coming Fall  	<h2 class="free">2012</h2>
	</a>

    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->


	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section id="homestead-banner">   

                
        
                            <header>
                                <h1>COMMUNITY HOMESTEADING A PREPPER'S PARADISE</h1>                      
                            </header>


			

					</section> <!-- end homestead-banner -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>

					<div class="box">

						<h1 class="large">
							<span>WHAT's</span> 
							a Prepper's Paradise?<br>Where is one located?
						</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>

							<div class="col">
								<h4 class="black">Looking to Homestead?</h4>
								<p>Why be a loan wolf homesteader where few if anyone near you is a prepper when you can homestead with like minded preppers?</p>

								<h4 class="black">Tactical & Practical</h4>
								<p>Mainstream Prepper Homesteads are tactical b/c in the event of an emergency, you have a built in survival group in place.
								Everyone will be skilled, geared, and ready to work together.  What's that worth?
								</p>
								<p>Our Homesteads are practical because there are numerous financial and cooperative benefits of homesteading near each other.  We're considering a community water tower, community barn/tractor/etc, and of course - Hey brother can you give me a hand pouring this concrete?  Having an extra set of hands now and then is priceless!</p> 
							</div><!-- end col-->

							<div class="col">
								<h4 class="black">Prepper Communities Make Sense:</h4>
								<ul>
									<li>Develop Self Sufficiency Skills</li>
									<li>Divide and Conquer various Projects</li>
									<li>Privacy, but with Preppers nearby</li>
									<li>Like Minded Prepper Neighbors</li>
									<li>Thrive in Good Times & Bad</li>
									<li>Prepper Retreat Nearby</li>
									<li>Far Easier to Take Vacations</li>
									<li>People are Social Creatures</li>
									<li>Permaculture? - yep</li>
									<li>Aquaponics? - yep</li>
									<li>Self Reliant? - oh Ya!</li>
									<li>Secure? - Like None Other</li>
									<li>We've got AMAZING Land!</li>
									<li>MUCH Cheaper than doing it alone</li>
									

								</ul>

							</div><!-- end col-->

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->   




					<div class="box network-map">


						<div class="map">
							<div class="description">
								<h4>Planned homestead communities:</h4>
								<ol>
									<li class="phase-one-text">Camden County, MO</li>
									<li class="phase-two-text">Montgomery County, AR</li>
									<li class="phase-three-text">TBD, likely IN or OH</li>
									<li class="phase-four-text">Uruguay and/or Costa Rica</li>
									<li><a href="contact.php">Israelite (YHVH) Community</a></li>
									<li><a href="contact.php">Have Land?  Let's Talk!</a></li>
								</ol>
								
				

							</div><!-- end description-->

							<div id="hover-des"></div>

							<div class="map-legend">
								<div class="phase-one-color"></div>Phase One<br>
								<div class="phase-two-color"></div>Phase Two<br>
								<div class="phase-three-color"></div>Phase Three
							</div>


							<div class="phase-one phases"><img src="images/network-map-marker.png" title="Marker" class="marker"/></div>
							<div class="phase-two phases"><img src="images/network-map-marker.png" title="Marker" class="marker"/></div>
							<div class="phase-three"></div>

							<img src="images/network-map.gif" class="map-image" />                                   
						</div><!-- end map -->

						<div class="col">
							<h3>Locations</h3>

							<p>We aim to form several homesteads with the following features:
							</p>

							<ul class="decorated">
								<li>1 tank of gas from large cities</li>
								<li>Light population density</li>
								<li>Away from likely drift</li>
								<li>Away from Nuclear Plants</li>
								<li>Away from major fault lines</li>
								<li>Secluded/Hidden</li>
								<li>Accessible yet VERY Secure</li>
								<li>Great soil for growing food</li>
								<li>Decent year round climate</li>
								<li>Usable Acreage</li>
								<li>Purpose built, but still nice</li>
							</ul>
					</div><!-- end col -->


				</div><!-- end network-map -->


				<div class="box">                       
					<div class="col">
						<h3>Homestead Features</h3>

						

							<ul class="decorated">


								<li>Securable Perimeter, Secluded</li>
								<li>24x7x365 Security</li>
								<li>Tornado Shelter</li>
								<li>Strategic Entrance Path / Choke Points</li>
								<li>Listening Posts / <a href="http://en.wikipedia.org/wiki/Observation_post">Observation Posts</a> (LP/OPs)</li>
								

							</ul>                      

						</div><!-- end col -->

						
						<div class="col">
							<h3>Existing Infrastructure</h3>

						
							<ul class="decorated">
								<li><a href="retreatpace"  class="fancybox">PACE Plan for Water</a></li>
								<li><a href="retreatpace"  class="fancybox">PACE Plan for Electricity</a></li>
								<li>High Speed Internet</li>
								<li>Barn, Greenhouses, Tractor, Skid Loader</li>
								<li>Creeks, Ponds, Water Tower & More</li>
							</ul>    

						</div><!-- end col -->

					
					</div><!-- end box -->



					<div class="box">
						<div class="clear speech">

							<div class="speech-corner-r"></div>

							<h1>Is the Prepper's Paradise a Good Fit?</h1>

							<div class="col">
								<div class="blue-ribbon">
									<h3>Cost to Purchase:</h3>
									<h1>~$50,000 + $40/mo</h1>
									<p class="notice">- cost varies per acreage qty -<br>- subject to change -</p>
								</div><!-- end blue-ribbon -->



								<a href="contact" class="link-box fancybox">Payment plans available</a>
								<a href="contact" class="link-box fancybox">Inquire for details</a>

							</div><!-- end col -->

							<div class="col">
								<h4>Want to Homestead With Us?</h4>

								<ul class="decorated">
									<li>First Come First Serve on Acreage Selection</li>
									<li>Existing Members Vote in New Members</li>
									<li>All Documents/Easements/etc done 100% Legit</li>
									<li>Neighbors that are Like Minded - Priceless</li>
									<li>Lone Wolf Homesteaders are Easy Prey for Serious Threats</li>
									<li>We Preppers are people too.  Relax. Live. Enjoy.</li>
									<li>VERY Family Friendly!</li>                               
								</ul>

							</div><!-- end col-->

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->


					<br>





					<div class="box">

						<div class="col">

							<a href="comingsoon" class="member-requirement fancybox cboxElement">

								<h3>Member Requirements</h3>
								<span>Click to download the PDF</span>
								<span class="arrow">></span>
							</a>

							<article class="content">
								<header>
									<h3 class="red">Scholarships &amp; Discounts</h3>
								</header>

								<p>Scholarships and discounts may be available on a case by case basis for those with expertise in:
									<ul>
										<li>Medical / Paramedic / Nursing</li>
										<li>Security / Defense / Military Background</li>
										<li>Gardening / Greenhouse / Livestock</li>
										<li>Concrete Home Construction</li>
										<li>Preparedness Influence / Audience</li>
									</ul>


									Please describe any expert skills / training you may have when you request your member application.
								</p>
							</article><!-- end content -->

						</div><!-- end col -->


						<div class="col">

							<article id="stepstojoin">
								<header>
									<h3><span class="red">7</span> Steps to join</h3>
								</header>

								<ol class="steps-to-join">
									<li><span>Submit Application Form</span></li>
									<li><span>Interviews</span></li>
									<li><span>Members Vote</span></li>
									<li><span>Deposit in Escrow</span></li>
									<li><span>Criminal Background Check</span></li>
									<li><span>Sign Member Agreement</span></li>
									<li><span>Work/Training Weekends</span></li>                                                                    
								</ol>

								<a href="comingsoon" class="blue-rounded-btn animate-hover right fancybox cboxElement">Request Application Form</a> 

								<div class="clear"></div>

							</article><!-- end stepstojoin -->                                


						</div><!-- end col -->
			<div class="clear"></div>
          <a href="paradise#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>


					</div><!-- end box -->





				</section><!-- end main-content -->




			</div><!-- end middle-content -->
