
    
 <div class="sticky">

	<a href="contact" class="fancybox red-button">
	Partner with Us
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->



	<div id="main-content" role="main">
		<div class="blue-bg clear">
			<section class="what-is">   
				<div class="wrapper">  
					<header>
						<h1>MSP wants to work with you</h1>                      
					</header>
					
						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>

					<div class="box">

						<h1 class="large">
							<span>4 ways</span> 
							that people are partnering with Mainstream Preppers:
						</h1>


						
					</div><!-- end box -->   

					
				<div class="box">                       
					<div class="col">
						<h3>Instructors</h3>
							<p><b>Top Pay for Top Instructors</b></p>
							
							<ul class="red-bullets">
								<li><p>Guest Instructors - Great Pay for a Great Weekend</p></li>						<li><p>Virtual (online) Trainings - Residual Income!</p></li>
								<li><p>Key Instructors - Full Classes, Great Pay, and 
										Revenue Share!</p></li>
								
							</ul>
							<a href="instructors.php">MSP's Instructor Program</a><br>
							
							<a href="contact" class="blue-rounded-btn animate-hover left fancybox cboxElement">Instructor Inquiries</a>
							
	

						</div><!-- end col -->

						<div class="col">
							<h3>Referral Marketing</h3>
							<p><b>Great Rewards for Helping Grow MSP!</b></p>
							
							<ul class="red-bullets">
								<li><p>Refer Just 3 - Your membership is FREE!</p></li>
								<li><p>Website/Blog/Forum/Channel Sponsorships</p></li>
								<li><p>Significant Income Opp for Serious Marketers</p></li>
                                <li><p><b><a href="marketingexample" class="fancybox">Example Marketing Revenue</a></b></p></li>
							</ul>

							
                       
							<a href="contact" class="blue-rounded-btn animate-hover left fancybox cboxElement">Marketing Inquiries</a>

						</div><!-- end col -->                      

					</div> <!-- end box -->


					<div class="box">



						<div class="col">
							<h3>Investors</h3>

						<p><b>A Solid Investment in helping people become self reliant.</b></p>

							<ul class="red-bullets">
							
							<li><p>Quarterly Investor Dividend</p></li>
							<li><p>Residual Income!</p></li>
							<li><p>Investor Perks</p></li>
							<li><p>Several Options Available</p></li>
							</ul>
							<a href="contact" class="blue-rounded-btn animate-hover left fancybox cboxElement">Investor Inquiries</a>

<!--<a href="businessinvest" class="blue-rounded-btn animate-hover left cboxElement">Investor Details</a> 
                      		-->
                      		<!--
							<a href="businessinvest" class="link-box">Investing Details</a>-->						
							<div class="clear"></div><br><br>
							<a href="partnerships#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                     

						</div><!-- end col -->

						<div class="col">
							<h3>Strategic Alliances:</h3>
							<p><b>Let&rsquo;s help each other!</b></p>
							
							<ul class="red-bullets">
								<li><p>Want to Sponsor our events? Want us to sponsor yours?</p></li>
								<li><p>Looking to grow your business?  Can we help?</p></li>
								<li><p>Promoting an Event? Can we help?</p></li>
								<li><p>How can we work together?</p></li>
							</ul>
							<a href="contact" class="blue-rounded-btn animate-hover left fancybox cboxElement">Alliance Inquiries</a>


						</div><!-- end col -->   

						
					</div><!-- end box -->

<div class="box"><h4>We're interested in finding ways to work with like minded people and companies in the industry.  We love win-win relationships, especially when our members win big too!</h4></div>





				</section><!-- end main-content -->




			</div><!-- end middle-content -->
