<article>

<header>
    <h1 class="red">Dr. Paul B. Range PhD. - Reliance Community Farms</h1>
     
</header>


	<p>
	<!--This couple have been actively involved in prepping, survival classes, aquaponics and permaculture a combined total of 66 years. -->
Paul started at 13 years old in charge of stores and prepping for his family during the late 50's. An Eagle Scout with a troop dedicated to wilderness survival, Paul spent 10 years in Special Forces, earned Master Jump Wings, Ranger, Pathfinder, Underwater Demolition, HALO and co-authored the first Field Manual on Helicopter Rappelling. </p>
<p>
An early innovator in aquaponics, Dr. Range grew vegetables using Linear Aquaponics, later developing several working designs of Barrelponics including Simplified Aquaponics using only one low volume pump and a non-mechanical siphon actuated dump system. 
</p><p>
Recently developing extremely low cost mechanically wind powered water pumping systems along with simple electric wind systems using hardware store parts, Paul went to Haiti for relief work. 
<!--Gloria was involved in prepping at an early age with her family. She joined the Army and became an Electronic Intelligence Specialist completing tours in Massachusetts, Korea,Texas  and Arizona.  
Gloria became more active in Aquaponics after meeting Paul at an Aquaponics Conference in North Carolina. Together they have taught Aquaponics for the past 6 years.--> 

</p><p>Both Paul and his wife Gloria are Permaculture Design Specialists and Certified Permaculture Teachers. 
For the last four years they have taught Permaculture, Urban Survival, Water Storage, Canning, Dehydrating, Food Storage and Emergency Prepardness classes at their homestead in Central Texas. Their homestead raises goats, pigs, chickens, geese, ducks, fish and vegetables. Recently they were featured in the National Geographic's "Doomsday Preppers, Episode 1. <br>
They are active in Food distribution, Community Gardens and Veterans organizations.</p>
</article>
