
    
<!-- <div class="sticky">

	<a href="contact" class="fancybox red-button">
		Inquire Today
	</a-->
   <!--  
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div>end social -->
    
	<!--a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div> end sticky -->



	<div id="main-content" role="main">
                        
                            <div id="free-trial-banner" class="blue-bg clear">
                            
                                <section>   
                                  
                                                    <header>
                                                        <h1>Free Prep School Membership</h1>                      
														<h2>Free 90 Day Trial. No Credit Card Required.  Limited to first 500 Members</h2>
                                                    </header>
                                  					
													<div class="enroll-today success">Enroll Today!</div>
                                
                                </section> <!-- end free-trial-banner -->           
                    
                                        <div class="clear"></div>
                                </div><!-- end blue-bg -->    


							<section>

 

					
     
                                
                                
                       
                                
                                	<section class="box twocol"> 
                                        
                                         
                                          <div class="wide-left">
                                         	  <link href="css/form.css" rel="stylesheet">
                                            
												<div class="form">
                                       				<h2>Thanks for signing up our 90 Day Free Prep School Membership Trial.<br />
													 We&rsquo;ll be contacting you very soon.</h2>
										
													<p class="red"><br /><b>LET&rsquo;S KEEP IN TOUCH:</b></p>
													
													<ul class="thankyou-list">
														<li><a href="http://www.facebook.com/MainstreamPreppers" class="facebook"><img src="images/fb-biggerR.gif" title="Facebook"/>Like us on Facebook</a></li>
														<li><a href="https://twitter.com/#!/PrepperSkills" class="twitter"><img src="images/twitter-biggerR.gif" title="Twitter"/>Tweet @PrepperSkills</a></li>
														<li>Don&rsquo;t forget to join our <a href="network"><b>FREE</b> Prepschool Network</a>!</li>
													</ul>
                                            
												</div><!-- end form -->
												
												
                                            </div><!-- end wide-left-->
                                            
                                            
                                            
                                            
                                            <aside class="right-col">
                                            		<a href="contact" class="questions-on-signup fancybox" data-fancybox-type="iframe">
                                                    <b>Questions?</b>
                                                    ASK US</a><br /><br />
                                                    
                                                    
                                                    <h2>ABOUT<br />
PREPSCHOOL</h2>
                                                    <ul class="related">
                                                    	<li><a href="#">Meet Our Instructors</a></li>
                                                        <li><a href="#">Testimonial</a></li>
                                                        <li><a href="#">Course Schedule</a></li>
                                                                                                           
                                                    
                                                    
                                                    </ul><!-- end related-->
                                                    
                                                    
                                            </aside><!-- end right-col-->
                                            
                                            <div class="clear"></div>

	                                </section><!-- end twocol-->
                                
                                
                                	
                                
                         







				</section><!-- end section -->




	</div><!-- end main-content -->
