

 <div class="sticky">

	<a href="application/signup" class="fancybox red-button">
		Sign Up Today
	</a>
    
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->






	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section id="prep-school-banner">   

				

					<header>
						<h1>WE TEACH SELF RELIANCE</h1>                      
					</header>



					</section> <!-- end prep-school-banner -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>
				
				
				<!--<div class="box">

				<h2>Prep School Offers:</h2>
								<div class="col">
								<ul class="decorated">
								<li>Volumes of in depth, expert skill development</li>
								<li>Top instructors from across the country</li>
								<li>Courses cover all areas of preparedness</li>
								<li>Follow Up Discussions & 1-on-1 Consultations</li>
								<li>Skip the Plane/Hotel Bill - Get Trained Online</li>
								</ul>
								</div>
								<div class="col">							
								<ul class="decorated">
								<li>Every lesson organized into detailed notes</li>
								<li>The Encyclopedia of Preparedness - FREE</li>
								<li>FREE Entry & VIP Access at Preparedness Expos</li>
								<li>Want Awesome Live Instruction?  Members Save 50%</li>
								<li>Training Fees Saved To Date:  $812,400!</li>
								</ul>
								</div>
								
							<br><br>
							
					</div>-->
					<!-- end box -->     


					<!--
					<div class="box">

						<h1 class="large">
							<span>Why</span> 
							improve your preparedness?<br>
							Have you taken our <a href="quiz">Prepper Quiz</a>?
						</h1>
								<div class="clear"></div>
						

					</div>--><!-- end box -->   

					<div class="box">
					
						<h1 class="large">
							<span>What SKILLS </span> 
							do we cover in our 'Prep School'?
						</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>

					<h2>This is only PHASE ONE Curriculum:</h2>
								
								<div class="col">
								<h4 class="black">Food Production / Storage</h4>
								<ul>
								<li>Food Production</li><!--$160-->
								<li>Permaculture</li><!--$160-->
								<li>Aquaponics</li><!--$160-->
								<li>Water Systems</li>
								
								<li>Cooking w Food Storage</li>
								<li>Cooking w Wild Edibles</li>
								<li>Dehydrating</li>
								<li>Canning/Preserving</li>
								<li>DIY Food Storage Tips</li>
								</ul>
								
								</div>
								<div class="col">							
								
								<h4 class="black">Survival</h4>
								<ul>
									<li>Woods Walkers (Survival 101)</li><!--$150-->
									<li>Survival (level 2)</li><!--$160-->
									<li>Survival (level 3)</li><!--$160-->
									<li>Bugging Out (BoB / BoV)</li><!--$100-->
									<li>Wilderness Survival (3 day)</li><!--$300-->
									<li>Wild Edibles</li><!--??-->
									<li>Winter Survival</li><!--??-->
									<li>Treating Cuts, Bites, Wounds</li>
									
									<!--Total Survival: 5 @ $870 + 3 ??-->
								</ul>
								
								
								</div>
								<div class="clear"></div>
								
								<div class="col">	
								<h4 class="black">Homesteading:</h4>
								<ul>
								
									<li>Preparedness Basics</li><!--$160-->
									<li>Shelter in Place (SIP) Strategies</li><!--$160-->
									<li>Bug Out Location Consult</li><!--$160-->
									<li>Off Grid Systems</li><!--$160-->
									<li>Security / Surveillance</li><!--$160-->
									<li>Homestead Design</li><!--$160-->
									<li>Securing your Homestead</li><!--$160-->
									<li>OPSEC Strategies</li><!--$160-->
									<li>Medical / Health</li><!--$160-->
									<li>Forming a Group - Consult</li><!--$160-->
																
									<!--Total Homesteading: 13x160=$2080-->
								</ul>
								
								</div>
								<div class="col">
								
								
								<h4 class="black">Defense / Tactical:</h4>
								
								<ul>
									<li>Fitness / Combatives</li><!--$??-->
									<li>Emergency Medical</li><!--??-->
									<li>Self Defense</li><!--$20-->
									<li>Knife Defense</li><!--??-->
									<li>Self Defense Shotgun</li><!--$70-->
									<li>Beginner Handgun</li><!--$70-->
									<li>Camouflage and Concealment</li><!--$60-->
									<li>Evasion (level 1)</li><!--$250-->
									<li>Tactical Patrolling (level 1)</li><!--$250-->
									<!--Resistance-->
									<!--Escape-->
									<!--Tactical Rifle-->
									<!--total: 6 $720  + 5 ?? -->
									
								</ul>
								
								</div>
								<div class="clear"></div>
								
								<h2>We're just getting warmed up.<br>
								More Instructors & Training Will be Added Soon</h2>
					
								<div class="clear"></div>
								</div>
								<br><br>
								
					
					
					<!--
					<h2>Plus, We Have the BEST Instructors, Period.</h2>
					<div class="col">
					<strong>We built the preparedness dream team. Seriously.</strong>
					<ul class="decorated">
								<li>US Army Special Forces Officer</li>
								<li>Survival, Evasion, Resistance, Escape Instructor</li>
								<li>Electrical Engineer, specialized in off grid technologies</li>
								<li>Authors of Preparedness books like "Survivalist Family"</li>
								<li>US Marine Veteran with combat experience</li>
								<li>Food Production Expert (Soil Development / etc)</li>
								<li>Self Defence Specialist (Krav Maga)</li>
								<li>
							</ul>    
						</div>
						<div class="col">
						<strong>Instructor Profiles:</strong>
						<ul class="decorated">
								<li>Instructor 1</li>
								<li>Instructor 2</li>
								<li>Instructor 3</li>
								<li>Instructor 4</li>
								<li>Instructor 5 - currently open</li>
							</ul>                      

						</div>-->

					</div> <!-- end box -->



				<!--div class="box">
				<u>Ella: How can we make the recent additions and Upcoming Events Sections Look Better?</u>
				<div class="col">
				<h3>Recent Additions</h3>                
					<ul class="decorated">
								
								<li><a href="comingsoon" class="fancybox">Beginner Handgun (Viking Preparedness)</a></li>
								<li><a href="comingsoon" class="fancybox">Rainwater Catchment & Greywater Systems (Engineer 775)</a></li>
								<li><a href="comingsoon" class="fancybox">BoB/BoV: Getting out of Dodge - Module 2 (Viking Preparedness)</a></li>
								
							</ul>    
							<a href="comingsoon" class="blue-rounded-btn animate-hover right fancybox cboxElement">View All Courses/Modules</a> 
								                  

				</div><div class="col">
				   
				<h3>Upcoming Live Events</h3>                
					
						<ul class="decorated">
								<li>July 4, 2012 - Charlotte, NC<br>
								<a href="comingsoon" class="fancybox">Securing/Fortifying your Home - Joel Skoussen</a> ($75)<br> 
								<i>(includes his book, "Secure Home".  a $45 Value!)</i></li>
								<li>July 27-28, 2012 - Arlington, TX<br>
								<a href="comingsoon" class="fancybox">Self Reliance Expo</a>  ($FREE for Members)</li>
								<li>July 30, 2012 - Leavenworth, KS<br>
								<a href="comingsoon" class="fancybox">Summer Wild Edibles - Viking Preparedness</a> ($50)</li>
								<li>August 5, 2012 - Springfield, MO<br>
								<a href="comingsoon" class="fancybox">Tactical Handgun for Home Defense - ATP</a> ($350)</li>
						</ul> 
						<a href="comingsoon" class="blue-rounded-btn animate-hover right fancybox cboxElement">View Events Calendar</a> 
								                     
				</div>
					
				
					</div>-->
					<!-- end box -->
                    
                    <div class="box" style="padding-top:0">
                    <a name="new"></a>
                    <img src="images/prepshool-new-events-box.gif" title="Prep School New Courses and Upcoming Events" width="934" height="598" />
                    </div>
                    
                    
                    
                    
                    



					<div class="box">
						<div class="clear speech">

							<div class="speech-corner-r"></div>
							<a name="signup"></a>
							<h1>Prep School Pricing / Signup:</h1>

							<div class="col">
								<div class="blue-ribbon">
									<!--<h3>Monthly Member Fee</h3>--><h3>Member Fee:<strike>$60.00/mo</strike></h3>
									<!--<h1>Special Price: $49.00</h1>-->
									<h1>Special Offer Below!</h1>
									<p class="notice">- subject to change September 1, 2012 -</p>
								</div><!-- end blue-ribbon -->



								<a href="blaze" class="link-box"><h3 color="black">DON'T MI$$:</h3>
								<u>CLICK HERE</u> for<br>
								First Adopter Discounts!</h3></a>

							</div><!-- end col -->

							<div class="col">
								<h4 class="black">Reasons to Join Today:</h4>

								<ul class="decorated">
									<li>100% Satisfaction Guarantee</a></li>
									<li>Cancel Anytime</li>
									<li>Can you achieve our level of preparedness/sufficiency alone?</li>
									<li>How much will you learn in just one training?</li>
									<li>Imagine the new skills you'll have in 12 months!</li>
									<li>Free GEAR & AWARDS for members (Shirt, Books, etc)</li>
									<li>Grandfathered Pricing.  Lock in the Savings!</li>                               
								</ul>

							</div><!-- end col-->

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->


					<br>





					<div class="box">

						<div class="col">

							<a href="comingsoon" class="member-requirement fancybox cboxElement">

								<h3>Member Handbook</h3>
								<span>Download the PDF</span>
								<span class="arrow">></span>
							</a>
							</div><!-- end col -->


						<div class="col">
							<article class="content">
								<header>
									<h3 class="red">How to Make your Membership FREE</h3>
								</header>

								<ul class="decorated">
										<li>Refer just 3, yours is FREE</li>
										<li>50% off ALL Live Trainings</li>
										<li>Save via special vendor discounts</li>
										<li>Simply cannot afford a membership?  <br>
										<a href="contact" class="fancybox">Drop us a line</a> and we'll try to help.</li>
										</ul>


									</p>
							</article><!-- end content -->

						


						</div><!-- end col -->

						<div class="clear"></div>

					</div><!-- end box -->

<div class="box">
                                   <article class="further-reading-box">
                                                <header>
                                                        <h1>More Prep School Info:</h1>
                                                        <h4>Member Benefits:</h4>
                                                </header>
                                                
                                                <ul class="col">
                                                    <li><a href="prepschool" class="currentpage">Prep School Overview</a></li>
                                                    <li><a href="prepschool#signup" class="currentpage">Pricing / Signup</a></li> 
                                                    <li><a href="comingsoon" class="fancybox">Upcoming Preparedness Expo's</a></li>
                                                    <li><a href="comingsoon" class="fancybox">Live Training Calendar</a></li>
                                                	<li><a href="comingsoon" class="fancybox">View Upcoming Training</a></li> 
                                                    <li><a href="comingsoon" class="fancybox">Free Prep School Modules</a></li>                                     
                                                </ul>      
                                                
                                                <ul class="col">
                                                    <li><a href="http://www.netprofitservices.com/work/mp/mainstream/mockup/prepschool-mockup-2.html"> - Viking Preparedness</a></li>
                                                    <li><a href="comingsoon" class="fancybox currentpage">James Wesley Rawles</a></li>
                                                    <li><a href="comingsoon" class="fancybox currentpage">Practical Preppers</a></li> 
                                                    <li><a href="comingsoon" class="fancybox currentpage">Geoff Lawton</a></li> 
                                                    <li><a href="comingsoon" class="fancybox currentpage">Another Instructor</a></li>
                                                                             
                                                </ul>                    
                                            <div class="clear"></div>
                                   
                                   </article><!-- further-reading-box -->
                                   
                                   
                                   <a href="prepschool#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                       </div><!-- end box -->




				</section><!-- end main-content -->




			</div><!-- end middle-content -->
