<link href="css/course.css" rel="stylesheet" type="text/css" />
<link href="css/aida.css" rel="stylesheet" type="text/css" />



 <div class="sticky">
 
	<a href="preppernetwork#signup" class="red-button">
		Sign Up 	<h2 class="free">FREE</h2>
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->






<div id="main-content" role="main" class="aida">


		<div class="blue-bg clear">

					<section id="prepper-network-banner">   

							<header>
								<h1>The Most Secure and Robost Prepper Network</h1>
								<h2>Mainstream Prepper is the Fastest Growing Network in America!</h2>                      
							</header>

						<img src="images/aida/most-secure-prepper-network.png" title="The Most Secure Prepper Network"  class="badge" />
									

					</section> <!-- end what-is -->           

				

				</div><!-- end blue-bg -->    

				<section>
 
							<div class="box prepper-network-firstbox">
									
									<div class="col col-dottedline">
									
										<h3>We offer the ability to:</h3>
										
											<ul class="red-bullets">
												<li><p>Connect with preppers in your area</p></li>
												<li><p>Help organize preparedness in your area</p></li>
												<li><p>Build coalitions &amp; alliances with local preppers</p></li>
												<li><p>Link up with local preparedness groups</p></li>
												<li><p>Receive Professional Tips &amp; Training</p></li>
											</ul>
										
									</div><!-- end col -->
								
								
									<div class="col col-dottedline">
									
										<h3>Joining Network is Risk Free:</h3>
										
											<ul class="red-bullets">
												<li><p>We never share your info, period.</p></li>
												<li><p>We never spam. End of story.</p></li>
												<li><p>We have awesome privacy/security tools.</p></li>
												<li><p>All you need to join is an email and zip code</p></li>
												<li><p>The Prepper Network is 100% FREE!</p></li>
											</ul>
										
									</div><!-- end col-->
									
									<div class="clear"></div>
							</div><!-- end box-->
							
							
					
					
						<a id="signup"></a>		
							
							<article class="red-ribbon-blue-top-box">
					
								
								<header>
									<h1>find local preppers &amp; nearby events</h1>
									<h2>Join our FREE Prepper Network</h2>
								</header>
								
								  
							<div id="form-message">Thank you!</div>
							
                           	<form action="newsletter/signup" method="post" id="join-network-form">   
                              		<input type="email" value="Enter Your Email"  name="emailaddress" id="emailaddress"  class="required"/>
                                    <div class="ampersand">&amp;</div>
                   
                              		<input type="text" value="Zip Code"  name="zip" id="zip"  class="required" />
                                   <input type="submit" class="form-btn " value="Join Free Network" name="submit" />      
                                   
                              <div id="messageBox"></div>    
							  
							  <div class="clear"></div>
							  
							  <div class="disclaimer">
                            	  note: you will never receive personal information about others, nor will your info be released.
                              </div>                          
                                   
                              </form><!-- end form-->
								
								
								
					
							
								
							</article><!-- end red-ribbon-blue-top-box-->
				


				</section><!-- end main-content -->




			</div><!-- end middle-content -->
