
    
<div class="sticky">

	<a href="prepschool" class="fancybox red-button">
	Get Prepared
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->
 
 


	<div id="main-content" role="main">
                        
  <div class="blue-bg clear">

		<section class="what-is">   

			<div class="wrapper">  

				<header>
					<h1 class="red">Prepper Skills &amp Tips</h1>                     
				</header>                                                                                        


			</div>  <!-- end wrapper -->            

			<div class="ribboncorners"></div>

		</section> <!-- end what-is -->           

		<div class="clear"></div>


	</div>

	<link href="css/quicktips.css" rel="stylesheet">
	<script src="js/quicktips.js"></script>
	
	 
	
	
	
		<section class="quicktips" >
				
				<div class="box">
	 
					
					

														
						<div class="sort col-item">	
											
								<h2 class="red">BY CATEGORY:</h2>								

								<div class="cat-wrapper">
													
													<a href="#"  id="show-cat"> All Tips </a>
													
													
													<ul id="tips-cat">
														<li>
															<label for="tips-all">
																<input type="radio" name="sort-tips" id="tips-all" value="tips-all" />
																<span>All Tips</span>
															</label>
														</li>
														
														<li>
															<label for="tips-101">
																<input type="radio" name="sort-tips" id="tips-101" value="tips-101" />
																<span>Preppers 101</span>
															</label>
														</li>
														
														<li>
															<label for="tips-community">
																<input type="radio" name="sort-tips" id="tips-community" value="tips-community" />
																<span>Community</span>
															</label>
														</li>
														
														<li>
															<label for="tips-food">
																<input type="radio" name="sort-tips" id="tips-food" value="tips-food" />
																<span>Food & Water</span>
															</label>
														</li>
														
														<li>
															<label for="tips-survival">
																<input type="radio" name="sort-tips" id="tips-survival" value="tips-survival" />
																<span>Survival</span>
															</label>
														</li>
														
														
														<li>
															<label for="tips-tactical">
																<input type="radio" name="sort-tips" id="tips-tactical" value="tips-tactical" />
																<span>Tactical</span>
															</label>
														</li>
														
														
														
														<li>
															<label for="tips-buyselltrade">
																<input type="radio" name="sort-tips" id="tips-buyselltrade" value="tips-buyselltrade" />
																<span>Buy, Sell, Trade</span>
															</label>
														</li>
														
														<li>
															<label for="tips-union">
																<input type="radio" name="sort-tips" id="tips-union" value="tips-union" />
																<span>State of the Union</span>
															</label>
														</li>
																			 
													
													</ul>
													
													</div><!-- cat-wrapper -->
								
							</div><!-- end sort -->
							
							
							
							
						<aside class="widgets quicktips col-item">

						
							
							<article class="clearfix">
							
								<header class="grey-header question-header">
									<img src="images/icons/question-icon.png" alt="Ask us a question"/>
									<h1>Got a Question?</h1>								
								</header>
								<br />
								  
								<a href="contact" class="red-rounded-btn-brighter left fancybox askus">
									<span class="quote-icon">&ldquo;</span> 
									ASK US
								</a>
								
								<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
								<script type="text/javascript">
									stLight.options({publisher: "e14d4910-0a21-4f51-bc5d-6742f176f6a3", doNotHash: true, doNotCopy: true, hashAddressBar: false});
								</script>
									
									<div id="sharethis-wrapper" class="left">
											<span class='st_facebook_vcount' displayText='Facebook'></span>
											<span class='st_twitter_vcount' displayText='Tweet'></span>
											<span class='st_googleplus_vcount' displayText='Google +'></span>
									</div><!-- end sharethis-wrapper -->
									
								
								
							</article>
							
							
							
							
							<link href="css/widgets.css" rel="stylesheet">
							<script src="js/jquery.bxSlider.min.js" type="text/javascript"></script>
							
							<script type="text/javascript">
							  $(document).ready(function(){
								  
								var slider =  $('#instructors-slideshow-small ul').bxSlider({
									auto: true,
									controls: false	
								});
								
									
								
							  });
							</script>
							
							<article class="clearfix">
								<header class="grey-header">
									<h1>Meet Our Instructors <a href="instructorpreview">ALL</a></h1>								
								</header>
								
								<div id="instructors-slideshow-small">
								
	
											<ul class="instructor-list simple">
											
													<li>
															<a href="joefox" class="see-bio fancybox">
																		
																		<span class="instructor-photo">
																			<img src="images/course/instructor/joe-fox-big.jpg" title="Joe Fox" width="75" />
																			<b class="course-num">15</b>
																		</span>
																		
																		<p class="instructor-name">
																				
																				<b class="fullname">
																					Joe Fox
																				</b>	
																				
																		
																				<span class="co">
																					<img src="images/course/instructor/viking-prepareness-logo.png" title="Viking Prepareness" />
																					Viking Preparedness
																				</span><!-- end co-name-->																
																			
																			<span class="brief">20 years, Army Special Forces </span>
																			
																		</p><!-- end instructor-name -->															
															 </a>	
															 
															 <div class="clear"></div>						
													</li>
													
													<li>
															<a href="paulrange" class="see-bio fancybox">
																		
																		<span class="instructor-photo">
																			<img src="images/course/instructor/paul-range-160.jpg" title="Dr. Paul Range" width="75" />
																			<b class="course-num">15</b>
																		</span>
																		
																		<p class="instructor-name">
																				
																				<b class="fullname">
																					Dr. Paul Range
																				</b>	
																				
																		
																				<span class="co">
																					Reliance Community Farms 
																				</span><!-- end co-name-->																
																			
																			<span class="brief">Innovator &amp; Instructor in Aquaponics</span>
																			
																		</p><!-- end instructor-name -->															
															 </a>	
															 
															 <div class="clear"></div>						
													</li>
													
													<li>
															<a href="billstill" class="see-bio fancybox">
																		
																		<span class="instructor-photo">
																			<img src="images/course/instructor/bill-still-160.jpg" title="Dr. Paul Range" width="75" />
																			<b class="course-num">15</b>
																		</span>
																		
																		<p class="instructor-name">
																				
																				<b class="fullname">
																					Bill Still
																				</b>	
																				
																		
																				<span class="co">
																					The Money Masters 
																				</span><!-- end co-name-->																
																			
																			<span class="brief">Expert on the US Monetary System</span>
																			
																		</p><!-- end instructor-name -->															
															 </a>	
															 
															 <div class="clear"></div>						
													</li>
													
											</ul>
								
								
								</div><!-- end instructors-slideshow-smal -->
							
							
							</article>
							
							
							
							
						 
							
							<article class="clearfix quiz-cta">
							
								<header class="grey-header">
									<h1>So, You think you are prepared?</h1>								
								</header>
								
								<div class="wrapper ">
								
								 <h4 class="red">Put your Preparedness to the Test</h4>
								 
								 <img src="images/aplus.gif" alt="Put your preparedness to the test!" class="left"/>
								 <a href="quiz" class="left red-rounded-btn-brighter">Take our Quiz now </a>
								 
								 <div class="clear"></div>
								 
								</div>
								
							</article>
							
							
							
							<div id="fb-root"></div>
							<script>(function(d, s, id) {
							  var js, fjs = d.getElementsByTagName(s)[0];
							  if (d.getElementById(id)) return;
							  js = d.createElement(s); js.id = id;
							  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
							  fjs.parentNode.insertBefore(js, fjs);
							}(document, 'script', 'facebook-jssdk'));</script>

							<div class="fb-like-box" data-href="https://www.facebook.com/MainstreamPreppers" data-width="450" data-show-faces="true" data-stream="true" data-header="true"></div>
							
							
							
							
							
							
 
							
							
							
							
							</aside>
							

							
						 
							
							
<!--

	To be able to sort correctly, each article must have the same class name as the corresponding input ID above
	
	-->
								 
							
								<article class="tips-detail col-item tips-survival">
								
									<span class="cat-title">Survival</span>
									<hgroup>
									
										<h1>Working In The Cold Tips</h1>
										<h3>Instructor: <a href="#">Marjory Wildcraft</a></h3>
									</hgroup>
									
									<p>As you start to live more sustainably you will be spending more time outdoors. And in the winter it can be tough. Getting or cutting firewood, tending livestock, taking care of the orchards or greenhouse – all of these activities means you’ll be getting outside in the cold. </p>
									
<p><b>#1 Wrap that neck!</b> Your neck radiates more heat than any other area. The head and feet are next on the list, but really the neck is the most important. In my backpack (which serves as a purse) I’ve used the neck wrap I keep in there more times than I can count to keep me warm during that sudden cold front that sweeps in.
You know when you start to get that scratchy throat and start feeling just the edges of a cold&hellip;</p>


											
											
											<a href="http://members.mainstreampreppers.com/discuss" class="discussnow"> View all &amp; Discuss &raquo;</a>
											<div class="clear"></div>								
								</article><!-- end tips-detail-->
								
								
								<article class="tips-detail col-item tips-101">
								
									<span class="cat-title">Preppers 101</span>
									<hgroup>
									
										<h1>Tips Title</h1>
										<h3>Instructor: <a href="#">Joe Fox</a></h3>
									</hgroup>
									
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus viverra nisl non ante bibendum cursus. Mauris vulputate purus quis ligula vulputate tempus. 
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus viverra nisl non ante bibendum cursus. Mauris vulputate purus quis ligula vulputate tempus. </p>

											
											<a href="http://members.mainstreampreppers.com/discuss" class="discussnow"> View all &amp; Discuss &raquo;</a>
											<div class="clear"></div>								
								</article><!-- end tips-detail-->
								
								
								
								
								
								<article class="tips-detail col-item tips-tactical">
								
									<span class="cat-title">Tactical</span>
									<hgroup>
									
										<h1>Tips Title</h1>
										<h3>Instructor: <a href="#">Joe Fox</a></h3>
									</hgroup>
									
											<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus viverra nisl non ante bibendum cursus. </p>
									
											<ul>											
												<li>List item</li>
												<li>List item 2</li>
												<li>List item 3</li>
											</ul>

											
											<a href="http://members.mainstreampreppers.com/discuss" class="discussnow"> View all &amp; Discuss &raquo;</a>
											<div class="clear"></div>								
								</article><!-- end tips-detail-->
								
								
								<article class="tips-detail col-item tips-community">
								
									<span class="cat-title">Community</span>
									<hgroup>
									
										<h1>Tips Title</h1>
										<h3>Instructor: <a href="#">Joe Fox</a></h3>
									</hgroup>
									
											<p>Video below is just an image, when you click, it'll take you to login to Member's page, 
											unless you want them to watch from YouTube directly, I can do that too, just let me know. </p>
									
											<div class="video">
												<a href="http://members.mainstreampreppers.com">
												<img src="images/icons/video-play-icon.png" title="play video" class="play"/>
												<img src="images/video-temp.jpg" title="Click to Watch" />
												</a>
											</div>
											
											<a href="http://members.mainstreampreppers.com/discuss" class="discussnow">Watch &amp; Discuss &raquo;</a>
											<div class="clear"></div>								
								</article><!-- end tips-detail-->
							
							
						 
					
					
					
							
								
								<article class="tips-detail col-item tips-tactical">
								
									<span class="cat-title">Tactical 2</span>
									<hgroup>
									
										<h1>Tips Title</h1>
										<h3>Instructor: <a href="#">Joe Fox</a></h3>
									</hgroup>
									
											<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus viverra nisl non ante bibendum cursus. </p>
									
											<ul>											
												<li>List item</li>
												<li>List item 2</li>
												<li>List item 3</li>
											</ul>

											
											<a href="http://members.mainstreampreppers.com/discuss" class="discussnow"> View all &amp; Discuss &raquo;</a>
											<div class="clear"></div>								
								</article><!-- end tips-detail-->
								
								
								<article class="tips-detail col-item tips-community">
								
									<span class="cat-title">Community</span>
									<hgroup>
									
										<h1>Tips Title</h1>
										<h3>Instructor: <a href="#">Joe Fox</a></h3>
									</hgroup>
									
											<p>Video below is just an image, when you click, it'll take you to login to Member's page, 
											unless you want them to watch from YouTube directly, I can do that too, just let me know. </p>
									
											<div class="video">
												<a href="http://members.mainstreampreppers.com">
												<img src="images/icons/video-play-icon.png" title="play video" class="play"/>
												<img src="images/video-temp.jpg" title="Click to Watch" />
												</a>
											</div>
											
											<a href="http://members.mainstreampreppers.com/discuss" class="discussnow">Watch &amp; Discuss &raquo;</a>
											<div class="clear"></div>								
								</article><!-- end tips-detail-->
							
							
						 
						 
							
								<article class="tips-detail col-item tips-food">
								
									<span class="cat-title">Food &amp; Water</span>
									<hgroup>
									
										<h1>Tips Title</h1>
										<h3>Instructor: <a href="#">Joe Fox</a></h3>
									</hgroup>
									
											<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus viverra nisl non ante bibendum cursus. </p>
									
											<ul>											
												<li>List item</li>
												<li>List item 2</li>
												<li>List item 3</li>
											</ul>

											
											<a href="http://members.mainstreampreppers.com/discuss" class="discussnow"> View all &amp; Discuss &raquo;</a>
											<div class="clear"></div>								
								</article><!-- end tips-detail-->
								
								
								<article class="tips-detail col-item tips-community">
								
									<span class="cat-title">Community</span>
									<hgroup>
									
										<h1>Tips Title</h1>
										<h3>Instructor: <a href="#">Joe Fox</a></h3>
									</hgroup>
									
											<p>Video below is just an image, when you click, it'll take you to login to Member's page, 
											unless you want them to watch from YouTube directly, I can do that too, just let me know. </p>
									
											<div class="video">
												<a href="http://members.mainstreampreppers.com">
												<img src="images/icons/video-play-icon.png" title="play video" class="play"/>
												<img src="images/video-temp.jpg" title="Click to Watch" />
												</a>
											</div>
											
											<a href="http://members.mainstreampreppers.com/discuss" class="discussnow">Watch &amp; Discuss &raquo;</a>
											<div class="clear"></div>								
								</article><!-- end tips-detail-->
							
					
					
						<div class="clear"></div> 
					
					
					

				
				
				</div><!-- end box -->
				
				

				
 
				</section><!-- end quicktips -->


					
 				<section class="box">
						
						<div class="need-help clear">
									Have a quick tip you want to share? let us know! <a class="iframe cboxElement red-rounded-btn" href="/contact">Contact MSP </a>
						</div><!-- end need-help -->
				
				<br /><br />
						<a href="/network">
							<img src="images/quicktips-wantmore-banner.gif" title="Want more news, tips, training, groups, local support? Join MSP Prepper Network Now!" />
						</a>
			</section>

	</div><!-- end main-content -->
