
    
<div class="sticky">

	<a href="prepschool" class="fancybox red-button">
	Get Prepared
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->
 
 


	<div id="main-content" role="main">
                        
  <div class="blue-bg clear">

		<section class="what-is">   

			<div class="wrapper">  

				<header>
					<h1 class="red">Prepper Skills &amp Tips</h1>                     
				</header>                                                                                        


			</div>  <!-- end wrapper -->            

			<div class="ribboncorners"></div>

		</section> <!-- end what-is -->           

		<div class="clear"></div>


	</div>

	<link href="css/quicktips.css" rel="stylesheet">
	
				<section class="quicktips">
				
				<div class="box">
				
					<div class="col">
					
					
							<div class="sort">
								<h2 class="red">VIEW BY CATEGORY:</h2>
								

								<div class="cat-wrapper">
								
								<b id="show-cat">All Tips</b>
								
								
								<ul>
									<li>
										<label for="tips-all">
											<input type="radio" name="sort-tips" id="tips-all" value="tips-all" />
											<span>All Tips</span>
										</label>
									</li>
									
									<li>
										<label for="tips-101">
											<input type="radio" name="sort-tips" id="tips-101" value="tips-101" />
											<span>Preppers 101</span>
										</label>
									</li>
									
									<li>
										<label for="tips-community">
											<input type="radio" name="sort-tips" id="tips-community" value="tips-community" />
											<span>Community</span>
										</label>
									</li>
									
									<li>
										<label for="tips-food">
											<input type="radio" name="sort-tips" id="tips-food" value="tips-food" />
											<span>Food & Water</span>
										</label>
									</li>
									
									<li>
										<label for="tips-survival">
											<input type="radio" name="sort-tips" id="tips-survival" value="tips-survival" />
											<span>Survival</span>
										</label>
									</li>
									
									
									<li>
										<label for="tips-tactical">
											<input type="radio" name="sort-tips" id="tips-tactical" value="tips-tactical" />
											<span>Tactical</span>
										</label>
									</li>
									
									
									
									<li>
										<label for="tips-buyselltrade">
											<input type="radio" name="sort-tips" id="tips-buyselltrade" value="tips-buyselltrade" />
											<span>Buy, Sell, Trade</span>
										</label>
									</li>
									
									<li>
										<label for="tips-union">
											<input type="radio" name="sort-tips" id="tips-union" value="tips-union" />
											<span>State of the Union</span>
										</label>
									</li>
							 							 
								
								</ul>
								
								</div><!-- cat-wrapper -->
								
							</div>
					
					
					
						<div class="clear"></div>
					</div><!-- end col -->
					
					
					
					
					
					
					<div class="col">
					
						<div class="clear"></div>
					</div><!-- end col -->
                
				
				</div><!-- end box -->
				
				
 
				</section><!-- end quicktips -->




	</div><!-- end main-content -->
