
    
 <div class="sticky">

	<a href="prepschool" class="fancybox red-button">
	Get Prepared
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->


<div id="main-content" role="main">



	<div class="blue-bg clear">

		<section class="what-is">   

			<div class="wrapper">  

				<header>
					<h1 class="red">Take the Preparedness Quiz</h1>                     
				</header>                                                                                        
<!--<div class="content">

						<h2 class="question">
						Are you Prepared?
						</h2>

						<p>
						Answer the quiz to test your preparedness and training/practice in important areas of preparedness:</p>


							</div>--><!-- end content -->    

			</div>  <!-- end wrapper -->            

			<div class="ribboncorners"></div>

		</section> <!-- end what-is -->           

		<div class="clear"></div>


	</div><!-- end blue-bg -->    


	<section>


<a name="why"></a> 
					<div class="box">
					
						<h1 class="large">
							<span>WHAT</span> 
							are the reasons you're motivated to increase your preparedness?
						</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>
							<div class="col">
							<h4 class="black">Question #1: What are you prepping for?</h4>
							<p>Until you can define the existing and possible threats you're preparing for, it's rather impossible to draft a quiz to tell you if you're ready for it.
							<br><br>Some people are preparing for job loss or continued inflation, while others are preparing for total economic collapse.  As you can imagine, preparations vary greatly based upon what possible threats you're preparing for.
							<br><br>This Quiz takes the middle ground, somewhat.  We're not including questions about nuclear/biological attacks, for example.  But know that in a grid down situation, you need to be worried about nearby and upwind nuclear power plants.
							<br><br>Some of the motivations that created this quiz are described in <a href="whyprepare">why we prepare</a>.
							<br>
							<i>Have you written out the reasons why you're a prepper?</i><br><br>
							<strong>To gauge your preparedness, take the quiz below!</strong>
							
											
							</div>
							<div class="col">
								<h4 class="black">Reasons you might become a prepper:</h4>
								<ul>
									<li>Develop Self Sufficiency Skills</li>
									<li>Job Loss / Bankruptcy</li>
									<li>House Fire / Tornado</li>
									<li>Area Flood / Earthquake / Other Disaster</li>
									<li>Drought / Crop Failures / Food Supply Disruption</li>
									<li>Sustained Power Outage</li>
									<li>Social Unrest / Riots</li>
									<li>Economic Collapse</li>
									<li>Hyperinflation</li>
									<li>Martial Law</li>
									<li>EMP</li>
									<li>Solar Flare/CME</li>
									<li>Nuclear Power Plant Meltdown</li>
									<li>Nuclear or Biological Warfare</li>
									<!--<li>Polar Shift</li> -->
									<li>Terrorist Attack</li>
									<li>Virus / Pandemic</li>
									<li>Zombie Apocalypse (just kidding!)</li>

								</ul>

							</div><!-- end col-->

						<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->   



		<div class="box">    
		
		<h2 class="question">
						Are you Prepared?
						</h2>

						<p>
						Answer the quiz to test your preparedness and training/practice in important areas of preparedness:</p>  
	                

			<h3>WATER</h3>
			<p>I'm going to assume that you already have SOME water storage in place.  If not, please don't complete this quiz until you do.<br>Water is a crucial aspect of preparedness.</p>
			<ul class="decorated">
			<li><strong><em>Do you have 2 sources of drinking water (minimum) plus an emergency storage?</em></strong></li>
			<li><strong><em>How many gallons of drinking water do you have on hand?  How many days is that for your family?</em></strong></li>
			<li><strong><em>How many gallons do you have for cooking?  How many for cleaning and sanitation?</em></strong></li>
			
			<li><strong><em>Do you have an emergency plan in place should your stored water run out?  Have you practiced that plan?</em></strong></li>
			<li><strong><em>Do you know how to prevent micro-organisms from growing in stored water?</em></strong></li>
			</ul>
				
			<div class="red-arrow-title bordered-box">
                                    <span class="red-rounded-arrow">Reality Check</span>
                                    <h4 class="black">
                                    You'll only survive 3 days without drinkable water!<br>You'll also need water for cooking and sanitation.</h4>
                                    
                                    <p class="clear">                             <strong>Experts recommend you store <span>3 gallons per day *per person*</span> of clean drinkable water.</strong><br>This is 1 gallon for drinking, 1 gallon for food preparation, and 1 gallon for sanitation.  What happens when your storage runs out?  It's important to have a <a href="retreatpace"  class="fancybox">PACE Plan</a> for clean drinkable water.</p>				    
                                    </div><br><br>
                                    <div class="clear"></div>
			<h3>FOOD</h3>
			
			<p>Job loss and short term power outages are probably the most realistic reasons you'd want food storage on hand.  But other situations could erupt such as a broken food distribution network, a serious drought, a virus outbreak, riot, or any other situation where you'd want to shelter in place.</p>
			
			<ul class="decorated">
			<li><strong><em>At 2 meals per day, how many days worth of food do you have stored for your family?  For pets/livestock?</em></strong></li>
			<li><strong><em>Do you have a stored cache of food outside of your home for emergencies?</em></strong></li>
			
			<li><strong><em>Are you self reliant by growing a percentage of your own food that you can survive on long term?  Is it balanced with meat/protein, fruit, and vegetables?  Do you require outside feed, fertilizers, etc to  produce this food?</em></strong></li>
			<li><strong><em>Are you experienced in perserving foods via canning, dehydrating, etc?  Can you survive a full winter without food?</em></strong></li>
			<li><strong><em>Do you stock necessary medicines (antibiotics, prescription drugs, etc.) and emergency medical supplies?</em></strong></li>
			<li><strong><em>There are likely ill-prepared people at your church or in your community.  Have you considered caching rations away from your property for those in dire need?</em></strong></li>
			</ul>
				
			<div class="red-arrow-title bordered-box">
                                    <span class="red-rounded-arrow">Reality Check</span>
                                    <h4 class="black">
                                    You're self reliant only when you can feed your family.  What happens if food storage runs out?</h4>
                                    
                                    <p class="clear">                             <strong>Experts recommend you keep a 3 day supply of food *per person* in a bug out bag for emergencies.<br>
                                    In your shelter or retreat, many suggest storing at least 1 year of non perishable food.</strong><br><br>
Food storage is important for surviving short to medium term emergencies.  
If your goal is long term self reliance, you need to be able to produce enough food to survive without outside help.  
This is why some preppers grow their own food, chickens, fish, and practice storing excess production to survive the growing season and winter months.</p>				    
                                    </div><br><br>
                                    <div class="clear"></div>
			
			
			
				<h3>SHELTER</h3>
			
			<p>Job loss and short term power outages are probably the most realistic reasons you'd want food storage on hand.  But other situations could erupt such as a broken food distribution network, a serious drought, a virus outbreak, riot, or any other situation where you'd want to shelter in place.</p>
			
			<ul class="decorated">
			<li><strong><em>Do you pay rent or have a mortgage?  How long can you stay in your shelter if your income stops tomorrow?</em></strong></li>
			<li><strong><em>What happens if there is an extended power outage?  Do you have a backup power system in place?</em></strong></li>
			<li><strong><em>Have you practiced cooking/sanitation/heating your home without utility water or power?</em></strong></li>
			<li><strong><em>Is your home/retreat/shelter defensible should you become a target?  Resistant to vehicles, bullets, fire?</em></strong></li>
			<li><strong><em>Are others in your immediate vicinity as prepared as you?  What is your plan if they're not?</em></strong></li>
			<li><strong><em>In a crisis situation, how will you protect your home while managing food production, sanitation, etc?</em></strong></li>
			</em></strong></li>
			<li><strong><em>Do you consider electricity a necessity?  If yes, do you have a <a href="retreatpace"  class="fancybox">PACE Plan</a> for electricity?</em></strong></li>
			<li><strong><em>Do you have the emergency items suggested by the red cross and ready.gov?	</em></strong></li>
			<li><strong><em>Do you have a bug out bag (portable 72 hour kit) in case you need to leave your home quickly?
			</em></strong></li>
			
			</ul>
				
			<div class="red-arrow-title bordered-box">
                                    <span class="red-rounded-arrow">Reality Check</span>
                                    <h4 class="black">
                                    You can shelter in place (SIP) for only ~1 week in the city.  You cannot secure a property 24x7 alone.</h4>
                                    
                                    <p class="clear">                             <strong>Experts recommend that at minimum, you get a kit and make a plan.  A decent place to start for minimum preparedness is <a href="http://ready.gov">Ready.gov</a>.</strong>
<br><br>
For those seeking a higher level of preparedness and self reliance than a 3 day supply of food, water, etc... there is much more work put into their shelter strategy.<br>
Self reliant preppers often have a stocked and secure <a href="http://en.wikipedia.org/wiki/Retreat_%28survivalism%29" class="fancybox">bug out location</a> that they'll transition to for a prolonged crisis or situation.
</p>				    
                                    </div><br><br>
                                    <div class="clear"></div>		
			<br><br>


	<h3>SECURITY</h3>
			<p>Security is more than guns and a bunker.  It's physical fitness, self defense skills, and ongoing training to maintain your skills.</p>
			<ul class="decorated">
			<li><strong><em>Ask yourself: Could you or members of your family be viewed as an easy target?<br>(examples: overweight, glasses, weak appearance or confidence lacking posture)</em></strong></li>
			<li><strong><em>Could you defend yourself from multiple attackers?  Are you ready right now?  If needed, could you outrun them?</em></strong></li>
			<li><strong><em>Do you have a home defense plan?  Have you had it reviewed by an expert?</em></strong></li>
			<li><strong><em>Have you taken defensive knife, defensive shotgun and defensive handgun courses?</em></strong></li>
			<li><strong><em>Do you practice your firearm and other defense skills regularly?</em></strong></li>
			
			</ul>
				
			<div class="red-arrow-title bordered-box">
                                    <span class="red-rounded-arrow">Reality Check</span>
                                    <h4 class="black">
                                    Physical fitness is often overlooked by preppers.  You want to look like a wolf but act like a shepherd.</h4>
                                    
                                   <p class="clear">                             <strong>Experts recommend you practice as you wish to perform.</strong><br>
                                   This means you need to include physical conditioning, self defense training, and maintenance of firearm skills into your daily life.</p>			    
                                    </div><br><br>
                                    <div class="clear"></div>



<h3>SURVIVAL / MEDICAL / SANITATION</h3>
			<p></p>
			<ul class="decorated">
			<li><strong><em>Do you have first aid / first responder training?</em></strong></li>
			<li><strong><em>Do you carry the medical kits to provide first aid?  In your home?  In your car?  On hikes?</em></strong></li>
			<li><strong><em>Do you have preps for basic sanitation should water treatment plants fail or sewers back up?</em></strong></li>
			</ul>
			<p>You are involved in a multi car accident in the middle of winter.  Your family is freezing cold and wet while others are seriously injured.</p>
			<ul class="decorated">
			<li><strong><em>Can you treat injured victims?  Do you know how/when to safely move them?</em></strong></li>
			<li><strong><em>Can you create a simple shelter for victims?  Are you carrying the gear with you?</em></strong></li>
			<li><strong><em>How many ways can you make fire?  Do you carry the needed tools in your vehicle?</em></strong></li>
			<li><strong><em>Can you help those at risk of hypothermia?</em></strong></li>
			<li><strong><em>Do you know how to signal for help?</em></strong></li>
			<li><strong><em>Can your spouse attend to your injuries?</em></strong></li>
			
			<li><strong><em>Do you carry along drinking water?  Emergency food?</em></strong></li>
			
			<li><strong><em>Can you get home with what you have on you?  </em></strong></li>
			<li><strong><em>Are you wearing the right clothes/shoes for the journey?  </em></strong></li>
			<li><strong><em>Do you have flashlights for night travel?  </em></strong></li>
			<li><strong><em>Is your family dressed for the journey too?</em></strong></li>
			
			</ul>
				
			<div class="red-arrow-title bordered-box">
                                    <span class="red-rounded-arrow">Reality Check</span>
                                    <h4 class="black">
                                    The #1 killer in a "shtf" situation will be health and sanitation.  Are you ready?</h4>
                                    
                                   <p class="clear">                             <strong>Medical emergencies and sanitation issues are some of the most overlooked skills with preppers, but also some of the most likely needed.</strong><br><br>
                                   At minimum, get training and keep a first aid kit in your home, car, and nearby.  In an emergency, you'll make a difference.  Then train others in your family and group.  You never know, you might be the one who needs assistance!</p>    
                                    </div><br><br>
                                    <div class="clear"></div>
                                    

		<h3>LIFESTYLE</h3>
		
			<ul class="decorated">
			<li><strong><em>How many times have you been to the range this month??</em></strong></li>
			<li><strong><em>When is the last time you did a 3 day bug out drill?
</em></strong></li>
			<li><strong><em>What sort of fitness regimen do you follow? </em></strong></li>
			
			<li><strong><em>Do you carry a get home bag in your vehicle?</em></strong></li>
			<li><strong><em>Have you taken a self defense shotgun class? </em></strong></li>
			<li><strong><em>Have you ever practiced a grid down situation?  Ever rehearsed bugging out?</em></strong></li> 
			</ul>
				
			<div class="red-arrow-title bordered-box">
                                    <span class="red-rounded-arrow">Reality Check</span>
                                    <h4 class="black">
                                    Practice as you want to perform.  To execute well in an emergency, stay brushed up on your skills.</h4>
                                    
                                    <p class="clear">                             <strong>Experts recommend you incorporate preparedness activities into your daily life.  Even more important is to get your family involved.  Maybe that's camping, purifying water, taking a hike, visiting the range, or rehearsing your plans for possible emergencies.</p>				    
                                    </div><br><br>
                                    <div class="clear"></div>
                                    
                                    
			<h3>Bug Out Location</h3>
			<p>Scenario: If trucks stop operating or the power grid stops working, shelves will be empty and the city has 3-7 days of water max.  Then everyone will leave the city to survive.  Eventually, someone hungry, thirsty, or angry will come across your property.
<br><br>You probably already realize it's impossible to grow &amp; prepare food, maintain personal hygiene, perform daily chores, and get nightly rest while maintaining 24x7 perimeter security.  Even 3 or 4 people cannot this job 24x7. 
			  <ul class="decorated"><li><strong><em>What is your plan for 24x7 perimeter security? (this takes multiple teams working shifts)</em></strong></li>
			<li><strong><em>How will you be able to do any daily work without being an easy target?</em></strong></li>
			<li><strong><em>How can your bug out retreat group defend against a larger group that surrounds you?</em></strong></li>
			<li><strong><em>Do you have a stocked bug out location you can get to via multiple routes, even an imperfect one?</em></strong></li></ul>
			<br><br>
			
			<div class="red-arrow-title bordered-box">
                                    <span class="red-rounded-arrow">Reality Check</span>
                                    <h4 class="black">
                                    Almost everyone can improve on something. Over time we should develop skills, gear, & a group.</h4>
                                    
                                    <p class="clear">                             <strong>Mainstream Preppers can help you through its <a href="network">free network</a>, <a href="prepschool">preparedness school</a>, <a href="retreats">bug out retreats</a>, or <a href="paradise">homesteads</a>.  <br><br>Let us know how we can assist you.  Also, feel free to <a href="contact" class="fancybox">send us questions or comments</a>.</p>				    
                                    </div><br><br>
			<!--<h3>Your Escape Route</h3>
			<p>Scenario: In the event of martial law or a social unrest scenario, you may be labeled a hoarder or even a domestic terrorist if you don't share supplies.
			You may be labeled a criminal for other reasons, or maybe the WROL situation is such that it's simply unsafe to remain in the country.
			 <ul class="decorated"><li><strong><em>Do you have a country you can go to?  How will you pay for it?  Is that in cash?  Precious metals?</em></strong></li>
			<li><strong><em>You'll need food/water/shelter/transportation immediately.  Have you pre-stocked your expat retreat?</em></strong></li>
			<li><strong><em>What is your security plan in this country?  Depending on where you go, you may stand out and you may be a target.</em></strong></li>
			<li><strong><em>What are the costs and laws associated with an extended stay?  Do you have all the paperwork needed?</em></strong></li>
			<li><strong><em>If you had to flee the US, it's safe to say the whole world is likely having problems.  You're going to need a group.  Got one?</em></strong></li></ul>   --> 
			<h2>THANKS FOR REVIEWING OUR QUIZ.  HOW'D YOU DO?</h2><br><br>
			<div class="clear"></div>
          <a href="quiz#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>

			
		</div> <!-- end box -->



	</section><!-- end main-content -->




</div><!-- end middle-content -->