
<div class="sticky">

	<a href="prepschool" class="fancybox red-button">
	Get Prepared
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->
 
 
 
 

<script src="js/quiz.js"></script>

<link href="css/quiz.css" rel="stylesheet">


	<div id="main-content" role="main">
                        
                            <div class="blue-bg clear">
                            
                                <section class="are-you-prepared-title">   
                                    <div class="wrapper">  
                                                    <header>
                                                        <h1>Are You Prepared?</h1>   
                                                   		 <a href="#">About This Quiz</a>                   
                                                    </header>

                                                    
                                                 <p class="clear">You understand <a href="aboutquiz">why you need to prepare</a>. So you gathered some food, water, planned out a location, and setup an emergency plan for your family. <b>YOU THINK YOU ARE PREPARED, BUT ARE YOU?</b>  Do you have what it takes to survive a major economic collapse, natural disaster, social unrest, and <a href="aboutquiz">many other situations</a>? 
                                                    
                                    </div>  <!-- end wrapper -->  
                                    <div class="ribboncorners"></div>
                                </section> <!-- end are-you-prepared -->           
                    
                                        <div class="clear"></div>
                                </div><!-- end blue-bg -->    


				<section class="quiz-result">
				
				<div class="decorated-corners"></div>
                
     
                	<div class="box">
                    
                    	<article class="quiz-score">	
                        	<header>
                            		<h2>You answered 40 out of 60 questions correctly.</h2>
									<p>4 Questions were unanswered, and we left them out of your result  </p>
                          		<h1><span>Your Score is</span><span class="circle">C</span></h1>
								<div class="clear"></div>
                            </header>
                       
                            <p class="share-quiz-title">Ask your friends to take this quiz, they won&rsquo;t see your score:   </p>
                            
                            
                           <?php
						   			$pageURL = $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];								
						   ?> 
                            		<a href="http://twitter.com/share?text=An%20Awesome%20Link&url=http://<?php echo $pageURL ?>" class="twitter-big">Share This on Twitter</a>
                                    <a href="http://www.facebook.com/sharer.php?u=http://<?php echo $pageURL ?>" class="facebook-big">Share This Link on Facebook</a>
                                    <a href="sharefriend" class="email-big fancybox">Email Friend</a>
                          
                          
                    	    	  <div class="clear"></div>
                              
                            	<div class="areas-improve">Areas to Improve</div>
                                <br /><br />
                                
                                
                            
                            
                    	      <div class="clear"></div>
                            
                        </article><!-- end quiz-score-->
                    
                    		
                    
                    </div><!-- end box -->
                    
                    
                                    <article class="box quiz-section">
                                                     <header>
                                                            <h1>WATER</h1>
                                                      </header>   	
                                                     
													 <div class="wrong-answers">
															 <ul>
																	<li>
																			<p><b>Question:</b> Do you have 2 sources of drinking water (minimum) plus an emergency storage? </p>
																			<p><b>Your Answer:</b> No</p>
																			
																			<p class="expert">Experts suggest 14 days worth of drinking water minimum, which is 3 gallons per day per person.<br />  
																				Example: a family of 5 needs 210 gallons.</p>
																		   
																	</li>
																  
															 </ul>
													 </div><!-- end wrong-answers -->
													 
													 
													 <div class="red-arrow-title bordered-box">
															<span class="red-rounded-arrow">Reality Check</span>
															<h4 class="black">
															You'll only survive 3 days without drinkable water!<br>You'll also need water for cooking and sanitation.</h4>
															
															<p class="clear">                            
															 <strong>Experts recommend you store <span>3 gallons per day *per person*</span> of clean drinkable water.</strong><br>This is 1 gallon for drinking, 
															 1 gallon for food preparation, and 1 gallon for sanitation.  What happens when your storage runs out?  
															 It&rsquo;s important to have a <a class="fancybox" href="retreatpace">PACE Plan</a> for clean drinkable water.
															 </p>				    
                                   					 </div>
													 
													 
												<br /><br />
												
												
													 <div class="wrong-answers">
															 <ul>
																	<li>
																			<p><b>Question:</b> Do you have an emergency plan in place should your stored water run out? Have you practiced that plan?</p>
																			<p><b>Your Answer:</b> No</p>
																			
																			<p class="expert">Experts suggest 14 days worth of drinking water minimum, which is 3 gallons per day per person.<br />  
																				Example: a family of 5 needs 210 gallons.</p>
																		   
																	</li>
																  
															 </ul>
													 </div><!-- end wrong-answers -->
													 
													 
													 <div class="red-arrow-title bordered-box">
															<span class="red-rounded-arrow">Reality Check</span>
															<h4 class="black">
															You'll only survive 3 days without drinkable water!<br>You'll also need water for cooking and sanitation.</h4>
															
															<p class="clear">                            
															 <strong>Experts recommend you store <span>3 gallons per day *per person*</span> of clean drinkable water.</strong><br>This is 1 gallon for drinking, 
															 1 gallon for food preparation, and 1 gallon for sanitation.  What happens when your storage runs out?  
															 It&rsquo;s important to have a <a class="fancybox" href="retreatpace">PACE Plan</a> for clean drinkable water.
															 </p>				    
                                   					 </div>
													 
                                        
                                        <div class="clear"></div>
                                        
                                        
                                    </article><!-- end  quiz-section -->
									
									
									
									<div class="bar"></div>
									
									
                  
                                    <article class="box quiz-section">
                                                     <header>
                                                            <h1>FOOD</h1>
                                                      </header>   	
                                                     
													 <div class="wrong-answers">
															 <ul>
																	<li>
																			<p><b>Question:</b> At 2 meals per day, how many days worth of food do you have stored for your family? For pets/livestock? </p>
																			<p><b>Your Answer:</b> No</p>
																			
																			<p class="expert">Experts suggest 14 days worth of drinking water minimum, which is 3 gallons per day per person.<br />  
																				Example: a family of 5 needs 210 gallons.</p>
																		   
																	</li>
																  
															 </ul>
													 </div><!-- end wrong-answers -->
													 
													 
													 <div class="red-arrow-title bordered-box">
															<span class="red-rounded-arrow">Reality Check</span>
															<h4 class="black">
															You'll only survive 3 days without drinkable water!<br>You'll also need water for cooking and sanitation.</h4>
															
															<p class="clear">                            
															 <strong>Experts recommend you store <span>3 gallons per day *per person*</span> of clean drinkable water.</strong><br>This is 1 gallon for drinking, 
															 1 gallon for food preparation, and 1 gallon for sanitation.  What happens when your storage runs out?  
															 It&rsquo;s important to have a <a class="fancybox" href="retreatpace">PACE Plan</a> for clean drinkable water.
															 </p>				    
                                   					 </div>
													 
													 
												<br /><br />
												
												
													 <div class="wrong-answers">
															 <ul>
																	<li>
																			<p><b>Question:</b> Do you have an emergency plan in place should your stored water run out? Have you practiced that plan?</p>
																			<p><b>Your Answer:</b> No</p>
																			
																			<p class="expert">Experts suggest 14 days worth of drinking water minimum, which is 3 gallons per day per person.<br />  
																				Example: a family of 5 needs 210 gallons.</p>
																		   
																	</li>
																  
															 </ul>
													 </div><!-- end wrong-answers -->
													 
													 
                                        
                                        <div class="clear"></div>
                                        
                                        
                                    </article><!-- end  quiz-section -->
									


	
				</section><!-- end quiz-result -->
				
													
									<div class="box share-footer">
									     <p class="share-quiz-title">Ask your friends to take this quiz, they won&rsquo;t see your score:   </p>
                
											<a href="http://twitter.com/share?text=An%20Awesome%20Link&url=http://<?php echo $pageURL ?>" class="twitter-big">Share This on Twitter</a>
											<a href="http://www.facebook.com/sharer.php?u=http://<?php echo $pageURL ?>" class="facebook-big">Share This Link on Facebook</a>
				                                    <a href="sharefriend" class="email-big fancybox">Email Friend</a>
                          
									</div>




	</div><!-- end main-content -->
