<div class="sticky">

	<a href="prepschool" class="fancybox red-button">
	Get Prepared
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->
 
 
 
 

<script src="js/quiz.js"></script>

<link href="css/quiz.css" rel="stylesheet">


	<div id="main-content" role="main">
                        
                            <div class="blue-bg clear">
                            
                                <section class="are-you-prepared-title">   
                                    <div class="wrapper">  
                                                    <header>
                                                        <h1>Are You Prepared?</h1>   
                                                   		 <a href="aboutquiz">About This Quiz</a>                   
                                                    </header>

                                                    
                                                    <p class="clear">You understand <a href="aboutquiz">why you need to prepare</a>. So you gathered some food, water, planned out a location, and setup an emergency plan for your family. <b>YOU THINK YOU ARE PREPARED, BUT ARE YOU?</b>  Do you have what it takes to survive a major economic collapse, natural disaster, social unrest, and <a href="aboutquiz">many other situations</a>? 
</p>
                                                    
                                    </div>  <!-- end wrapper -->  
                                    <div class="ribboncorners"></div>
                                </section> <!-- end are-you-prepared -->           
                    
                                        <div class="clear"></div>
                                </div><!-- end blue-bg -->    


				<section class="quiz">
				
				
                
                <form action="">
                	<div class="box" style="padding-bottom:0;">
							<b style="padding-left: 15px;">To Gauge your preparedness, take the Prepardness Quiz below!</b>
                    </div>
                    
                                    <article class="box quiz-section">
                                                     <header>
                                                            <h1>WATER</h1>
                                                            <p>If you currently do not have any water storages, please don't complete this quiz until you do. Water is a crucial aspect of preparedness.</p>
                                                     </header>   	
                                                     
                                                     <ul>
                                                            <li>
                                                                    <p>Do you have 2 sources of drinking water (minimum) plus an emergency storage? </p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>How many gallons of drinking water do you have on hand? How many days is that for your family?</p>
                                                                    <div class="inputs">
                                                                    	<input type="number" id="gallons" /> <label for="gallons">G</label>  &nbsp;
                                                                    	<input type="number" id="days" /> <label for="days">Days</label> 
                                                                    </div><!-- end inputs -->
                                                            </li>
                                                            
                                                            <li>
                                                            		<p>Do you have an emergency plan in place should your stored water run out? <br />
																			Have you practiced that plan?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                             
                                                            <li>
                                                                    <p>How many gallons do you have for cooking? How many for cleaning and sanitation?</p>
                                                                    <div class="inputs">
                                                                    	<input type="number" id="gallons" /> <label for="gallons">G</label>  &nbsp;
                                                                    	<input type="number" id="days" /> <label for="days">Days</label> 
                                                                    </div><!-- end inputs -->
                                                            </li>
                                                                            
                                                     
                                                     </ul>
                                        
                                        <div class="clear"></div>
                                        
                                        
                                    </article><!-- end  quiz-section -->

	
                                
                                
                        
                                    <article class="box quiz-section">
                                                     <header>
                                                            <h1>FOOD</h1>
                                                            <p>Job loss and short term power outages are probably the most realistic reasons you'd want food storage on hand. 
But other situations could erupt such as a broken food distribution network, a serious drought, a virus outbreak, 
riot, or any other situation where you'd want to shelter in place.</p>
                                                     </header>   	
                                                     
                                                     <ul>
                                                            <li>
                                                                    <p>At 2 meals per day, how many days worth of food do you have stored for your family? For pets/livestock?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>Do you have a stored cache of food outside of your home for emergencies?</p>
                                                                    <div class="inputs">
                                                                    	<input type="number" id="gallons" /> <label for="gallons">G</label>  &nbsp;
                                                                    	<input type="number" id="days" /> <label for="days">Days</label> 
                                                                    </div><!-- end inputs -->
                                                            </li>
                                                            
                                                            <li>
                                                            		<p>Are you self reliant by growing a percentage of your own food that you can survive on long term and balanced with meat/protein, fruit, and vegetables? 
                                                                    <br />
																			Have you practiced that plan?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                             
                                                            <li>
                                                                    <p>Do you require outside feed, fertilizers, etc to produce this food?</p>
                                                                    <div class="inputs">
                                                                    	<input type="number" id="gallons" /> <label for="gallons">G</label>  &nbsp;
                                                                    	<input type="number" id="days" /> <label for="days">Days</label> 
                                                                    </div><!-- end inputs -->
                                                            </li>
                                                            
                                                             
                                                            <li>
                                                                    <p>Do you have an emergency plan in place should your stored water run out? <br />Have you practiced that plan?</p>
                                                                    <div class="inputs">
                                                                    	<input type="number" id="gallons" /> <label for="gallons">G</label>  &nbsp;
                                                                    	<input type="number" id="days" /> <label for="days">Days</label> 
                                                                    </div><!-- end inputs -->
                                                            </li>
                                                            
                                                            <li>
                                                            		<p>Do you know how to prevent micro-organisms from growing in stored water?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                                            
                                                     
                                                     </ul>
                                        
                                        <div class="clear"></div>
                                        
                                        
                                    </article><!-- end  quiz-section -->         
                                    
                                    
                        
                                    <article class="box quiz-section">
                                                     <header>
                                                            <h1>SHELTER</h1>
                                                            <p>Job loss and short term power outages are probably the most realistic reasons you'd want food storage 
on hand. But other situations could erupt such as a broken food distribution network, a serious drought, 
a virus outbreak, riot, or any other situation where you'd want to shelter in place.</p>
                                                     </header>   	
                                                     
                                                     <ul>
                                                            <li>
                                                                    <p>Do you pay rent or have a mortgage? </p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>How long can you stay in your shelter if your income stops tomorrow?</p>
                                                                    <div class="inputs">
                                                                    	<input type="number" id="rent-months" /> <label for="rent-months">Months</label>
                                                                    </div><!-- end inputs -->
                                                            </li>
                                                            
                                                            <li>
                                                            		<p>Do you have a backup power system in place in case of an extended power outage?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                             
                                                            <li>
                                                                    <p>Have you practiced cooking/sanitation/heating your home without utility water or power?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>Is your home/retreat/shelter defensible should you become a target? Resistant to vehicles, bullets, fire?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>Are others in your immediate vicinity as prepared as you? Do you have a plan if they&rsquo;re not?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            
                                                            <li>
                                                                    <p>In a crisis situation, do you know how to protect your home while managing food production, sanitation, etc?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li class="sub-quiz-group">
                                                                    <p>Do you consider electricity a necessity? </p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                                    
                                                                    <p class="sub-question">If yes, do you have a PACE Plan for electricity?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            
                                                            <li>
                                                                    <p>Do you have the emergency items suggested by the red cross and ready.gov?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>Do you have a bug out bag (portable 72 hour kit) in case you need to leave your home quickly?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                                            
                                                     
                                                     </ul>
                                        
                                        <div class="clear"></div>
                                        
                                        
                                    </article><!-- end  quiz-section -->                       	
                                
                         
                         
                         
                                
                        
                                    <article class="box quiz-section">
                                                     <header>
                                                            <h1>SECURITY</h1>
                                                            <p>Security is more than guns and a bunker. It's physical fitness, self defense skills, and ongoing training to maintain your skills.</p>
                                                     </header>   	
                                                     
                                                     <ul>
                                                            <li>
                                                                    <p>Ask yourself: Could you or members of your family be viewed as an easy target?<br />
																		<i>examples: overweight, glasses, weak appearance or confidence lacking posture</i></p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>Could you defend yourself from multiple attackers? Are you ready right now? <br /><br />
																		If needed, could you outrun them?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                            		<p>Do you have a home defense plan? Have you had it reviewed by an expert?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                             
                                                            <li>
                                                            		<p>Have you taken defensive knife, defensive shotgun and defensive handgun courses?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                            
                                                            <li>
                                                            		<p>Do you practice your firearm and other defense skills regularly?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                                            
                                                     
                                                     </ul>
                                        
                                        <div class="clear"></div>
                                        
                                        
                                    </article><!-- end  quiz-section -->     
                                    
                                    
                                    <article class="box quiz-section">
                                                     <header>
                                                            <h1>SURVIVAL / MEDICAL / SANITATION</h1>
                                                            <p class="clear"></p>
                                                     </header>   	
                                                     
                                                     <ul>
                                                            <li>
                                                                    <p>Do you have first aid / first responder training?<br />
																	</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>Do you carry the medical kits to provide first aid? In your home? In your car? On hikes?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                            		<p>Do you have preps for basic sanitation should water treatment plants fail or sewers back up?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                             
                                                             <li class="scenario">
                                                             <p><b>Sceanrio: You are involved in a multi car accident in the middle of winter. Your family is freezing cold and wet while others are seriously injured.</b>
                                                             
                                                             </p>
                                                             </li>
                                                             
                                                            <li>
                                                            		<p>Can you treat injured victims? Do you know how/when to safely move them?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no selected">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                            
                                                            <li>
                                                            		<p>Can you create a simple shelter for victims? Are you carrying the gear with you?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                             
                                                            
                                                            <li>
                                                            		<p>How many ways can you make fire? Do you carry the needed tools in your vehicle?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                                        
                                                                        
                                                            
                                                            <li>
                                                            		<p>Can you help those at risk of hypothermia?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>    
                                                     
                                                            
                                                            <li>
                                                            		<p>Do you know how to signal for help?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>   
                                                             
                                                            
                                                            <li>
                                                            		<p>Can your spouse attend to your injuries?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>   
                                                             
                                                        
                                                            <li>
                                                            		<p>Do you carry along drinking water? Emergency food?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>  
                                                             
                                                            <li>
                                                            		<p>Can you get home with what you have on you?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>  
                                                             
                                                            <li>
                                                            		<p>Are you wearing the right clothes/shoes for the journey?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>
                                                             
                                                            <li>
                                                            		<p>Do you have flashlights for night travel?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>   
                                                             
                                                            <li>
                                                            		<p>Is your family dressed for the journey too?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                             </li>                                                        
                                                     </ul>
                                        
                                        <div class="clear"></div>
                                        
                                        
                                    </article><!-- end  quiz-section -->             
                                    

                                    
                                    <article class="box quiz-section">
                                                     <header>
                                                            <h1>LIFESTYLE</h1>
                                                            <p class="clear"></p>
                                                     </header>   	
                                                     
                                                     <ul>
                                                            <li>
                                                                    <p>How many times have you been to the range this month?</p>
                                                                 <div class="inputs">
                                                                    	<input type="number" id="range-frequency" /> <label for="range-frequency">Times</label>
                                                                    </div><!-- end inputs -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>When is the last time you did a 3 day bug out drill?	</p>
                                                                  <div class="inputs">
                                                                    	<input type="number" id="last-drill-month" /> <label for="last-drill-month">Months</label>
                                                                    </div><!-- end inputs -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>What sort of fitness regimen do you follow?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>Do you carry a get home bag in your vehicle?
																	</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>Have you taken a self defense shotgun class?
																	</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            
                                                            <li>
                                                                    <p>Have you ever practiced a grid down situation? Ever rehearsed bugging out?
																	</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                      </ul>



    
                                        <div class="clear"></div>
                                        
                                        
                                    </article><!-- end  quiz-section -->             
                                    
                                    
                                    
                                    
                                    <article class="box quiz-section">
                                                     <header>
                                                            <h1>Bug Out Location</h1>      
                                                            <p class="clear"></p>                                                      
                                                     </header>   	
                                                         <p class="scenario"><b>Scenario: If trucks stop operating or the power grid stops working, shelves will be empty and the city has 3-7 days of water
                                                                max. Then everyone will leave the city to survive. Eventually, someone hungry, thirsty, or angry will come across your property.</b><br />
                                                                <br />
                                                                <b>You probably already realize it&rsquo;s impossible to grow &amp; prepare food, maintain personal hygiene, perform daily chores, and 
                                                                get nightly rest while maintaining 24x7 perimeter security. Even 3 or 4 people cannot this job 24x7.</b>
                                                            </p>

                        
                                                     <ul>
                                                            <li>
                                                                    <p>Did you have a 3 day bug out drill recently within 3 months?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>What sort of fitness regimen do you follow?</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>Do you carry a get home bag in your vehicle?
																	</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            <li>
                                                                    <p>Have you taken a self defense shotgun class?
																	</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                            
                                                            <li>
                                                                    <p>Have you ever practiced a grid down situation? Ever rehearsed bugging out?
																	</p>
                                                                    <div class="yes-no">
                                                                            <a href="#" class="yes selected">Yes</a>
                                                                            <a href="#" class="no">No</a>
                                                                    </div><!-- end yes-no -->
                                                            </li>
                                                            
                                                      </ul>



    
                                        <div class="clear"></div>
                                        
                                        
                                    </article><!-- end  quiz-section -->      
                                    
									<div class="box submit-quiz clear">
                                    		<h1>How&rsquo;d You DO?</h1>
                                            <input type="submit" value="see YOUR results" />
                                    </div><!-- end submit-quiz-->
                                    
                                    <div class="clear"></div>

					</form>

				</section><!-- end quiz -->




	</div><!-- end main-content -->
