
    
 <div class="sticky">

	<a href="application/request" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->



	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>BUG OUT RETREATS</h1>                      
					</header>


					<div class="content">

						<h2 class="question">
							What is a Bug Out Retreat?
						</h2>

						<p>
							A <a href="http://en.wikipedia.org/wiki/Retreat_%28survivalism%29" class="fancybox">bug out retreat</a> is a place of refuge for those in the preparedness/survivalist movement.  
							<br>Often called a "Bug Out Location" or "BOL", they are a self sufficient, secluded, easily defended, homestead that would be used in troubled times to escape the chaos, violence, and other effects of possible threats and disasters.</p>
							<p>
								Within about a tank of gas of your home, a secure bug out retreat keeps stores of food and water, clothes, medical and other supplies, off grid power, and more.  Ready for your arrival at a moment's notice.</p>

							
							</div><!-- end content -->    

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>
				
				
					<div class="box"> 

<h3 class="black">EXAMPLE BUG OUT RETREATS</h3>
<img src="images/retreat-examples.jpg" class="image right" />
								<p><br>
								In order:<br>
								-- Rural Mtn Cabin<br>
								-- Ozark Homestead<br>
								-- Undergrnd Bunker<br>
								-- Bug Out RV</p>
								
				
							<div class="clear"></div>
							
							<p>Different styles of bug out locations are designed for different purposes.  For evading coastal storms, the Bug Out RV might be ideal.<br>
							But during apocalyptic nuclear war, sitting in your underground bunker watching <i>"Doomsday Preppers"</i> on your DVR will be better.<br>
							Seriously though - Different retreats suit different purposes.  
							It's about having a secure, secluded, stocked, self reliant retreat.</p>
							

						</div><!-- end box -->   


					<a name="why"></a> 
					<div class="box">
					
						<h1 class="large">
							<span>15 Reasons</span> 
							you might want a<br>Bug Out Retreat:
						</h1>


						<div class="clear speech">
							<div class="speech-corner"></div>
							<div class="col">
								<h4 class="black">15 Reasons you might want a Retreat</h4>
								<ul>
									<li>Develop Self Sufficiency Skills</li>
									<li>Job Loss / Bankruptcy</li>
									<li>House Fire / Tornado</li>
									<li>Area Flood / Earthquake / Other Disaster</li>
									<li>Drought / Crop Failures / Food Supply Disruption</li>
									<li>Sustained Power Outage</li>
									<li>Social Unrest / Riots</li>
									<li>Economic Collapse</li>
									<li>Hyperinflation</li>
									<li>Martial Law</li>
									<li>EMP</li>
									<li>Solar Flare/CME</li>
									<li>Nuclear Power Plant Meltdown</li>
									<li>Nuclear or Biological Warfare</li>
									<!--<li>Polar Shift</li> -->
									<li>Terrorist Attack</li>
									<li>Virus / Pandemic</li>
									<li>Zombie Apocalypse (just kidding!)</li>

								</ul>

							</div><!-- end col-->

							<div class="col">
								<h4 class="black">The Typical Bug Out Location</h4>
								<p>Most survivalists cannot afford to live at a rural homestead retreat year round.  They have jobs, families, etc.  Many people live in or near town but setup a retreat for an 11th hour departure, planning to quietly arrive and sustaining themselves through dangerous events.</p>
								
								<h4 class="black">Why not just take shelter in your home?</h4>
								<p>Looking at the reasons for having a retreat, if those scenarios lasted weeks or longer, most any city or suburban home would not be a smart place to be.  Even being in a country home that is not designed as a retreat would put you at high risk for crime, violence, and generally just as vulnerable as your neighbor.</p> 
								
								<h4 class="black">Is Having a Bug Out Location Worth It?</h4>
								<p>Building a homestead or retreat for a bug out location is time consuming to build, tremendously expensive, and burdensome to maintain.  However, with current events and what sometimes seems as a high possibility of a major breakdown, many are not willing to chance not having an operational bug out location at the ready.</p>

								</div><!-- end col-->

							
							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->   

	<div class="box"> 

<h3 class="black">Mainstream Prepper RETREAT Groups</h3>


<img src="images/retreat-preview.jpg" class="image right" />
								<p>Mainstream Preppers is helping preppers connect with skilled prepper groups and form bug out retreats.  <strong>
The combination of skills, gear, and self reliance would be difficult to match working alone.</strong><br><br>
								When thinking about retreats, note that the #1 ingredient is having a prepper group.  There is strength in numbers.  
								With the right group in place, the retreat is stronger, and much more affordable.
								<br>
								<br>Please Note:<br>
								This graphic is for illustration purposes only.   
								Any real retreat design would be kept confidential.
								</p>
								
				
							<div class="clear"></div>
							
						</div><!-- end box -->   


   						<div class="box">
                                   <article class="further-reading-box">
                                                <header>
                                                        <h1>Interested? Learn More:</h1>
                                                        <h2>Bug Out Retreat Info:</h2>
                                                </header>
                                                
                                                <ul class="col">
                                                    <li><a href="retreats" class="currentpage">What's a Bug Out Retreat?</a></li>
                                                    <li><a href="retreats#why" class="currentpage">Why you might want a Retreat</a></li>
                                                    <!--<li><a href="retreatpros">Bugging Out vs. Shelter in Place</a></li>
                                                    --><li><a href="retreatgroup">Strength in Numbers: Forming a Group</a></li>
                                                   </ul>      
                                                
                                                <ul class="col">
                                                     <li><a href="retreatideal">The Ideal Prepper Retreat</a></li>
                                                    <li><a href="retreatlocations">Potential Retreat Locations</a></li>
                                                    <li><a href="comingsoon" class="fancybox">Retreat Cost Estimate: Build Your Own</a></li>
                                                    <!--<li><a href="retreatfaq">Retreat FAQ</a></li>-->
                                                    <!--<li><a href="retreatmaterial">Are you Mainstream Material?</a></li>
                                                    <li><a href="retreatcosts">Pricing & How to Join</a></li>-->
               					<li><a href="application/request" class="fancybox">>> Inquire for Retreat Group Info</a></li>             
                                                </ul>                    
                                            <div class="clear"></div>
                                   
                                   </article><!-- further-reading-box -->
                                   
                                   
                                   <a href="retreats#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                       </div><!-- end box -->



				</section><!-- end main-content -->




			</div><!-- end middle-content -->
