
  
    
 <div class="sticky">

	<a href="application/request" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->



	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>Potential Retreat Locations</h1>                      
					</header>

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>
				
				
		       
       

					<div class="box network-map">
					<div class="map">
							<div class="description">
								<h4>Potential Bug Out Retreats:</h4>
								<ol>
									<li class="phase-one-text">Camden County, MO</li>
									<li class="phase-two-text">Montgomery County, AR</li>
									<li class="phase-three-text">Eastern IN or NW Ohio</li>
									<li class="phase-four-text">Uruguay and/or Costa Rica</li>
									<li><a href="contact" class="fancybox">Israelite (YHVH) Community</a></li>
									<li><a href="contact" class="fancybox">Have Land?  Let's Talk!</a></li>
								</ol>

							</div><!-- end description-->

							<div id="hover-des"></div>

							<div class="map-legend">
								<div class="phase-one-color"></div>Phase One<br>
								<div class="phase-two-color"></div>Phase Two<br>
								<div class="phase-three-color"></div>Phase Three
							</div>


							<div class="phase-one phases"><img src="images/network-map-marker.png" title="Marker" class="marker"/></div>
							<div class="phase-two phases"><img src="images/network-map-marker.png" title="Marker" class="marker"/></div>
							<div class="phase-three"></div>

							<img src="images/network-map.gif" class="map-image" />                                   
						</div><!-- end map -->

						<div class="col">
							<h3>Strategic Locations</h3>

							<p>Retreat groups are being formed, locations are being discussed, placed strategically for the following:
							</p>

							<ul class="decorated">
								<li>1 tank of gas from large cities</li>
								<li>Light population density</li>
								<li>Away from likely drift</li>
								<li>Away from Nuclear Plants</li>
								<li>Away from major fault lines</li>
								<li>Secluded/Hidden</li>
								<li>Accessible for members</li>
								<li>Good soil for growing food</li>
								<li>Decent year round climate</li>
								<li>Usable Acreage</li>
								<li>Purpose built, but still nice</li>
							</ul>


					</div><!-- end col -->


				</div><!-- end network-map -->


			


   								<div class="box">
                                   <article class="further-reading-box">
                                                <header>
                                                        <h1>Interested? Learn More:</h1>
                                                        <h2>Bug Out Retreat Info:</h2>
                                                </header>
                                                
                                                <ul class="col">
                                                    <li><a href="retreats">What's a Bug Out Retreat?</a></li>
                                                    <li><a href="retreats#why">Why you might want a Retreat</a></li>
                                                    <!--<li><a href="retreatpros">Bugging Out vs. Shelter in Place</a></li>
                                                    --><li><a href="retreatgroup">Strength in Numbers: Forming a Group</a></li>
                                                   </ul>      
                                                
                                                <ul class="col">
                                                     <li><a href="retreatideal">The Ideal Prepper Retreat</a></li>
                                                    <li><a href="retreatlocations" class="currentpage">Potential Retreat Locations</a></li>
                                                    <li><a href="comingsoon" class="fancybox">Retreat Cost Estimate: Build Your Own</a></li>
                                                    <!--<li><a href="retreatfaq">Retreat FAQ</a></li>-->
                                                    <!--<li><a href="retreatmaterial">Are you Mainstream Material?</a></li>
                                                    <li><a href="retreatcosts">Pricing & How to Join</a></li>-->
               					<li><a href="application/request" class="fancybox">>> Inquire for Retreat Group Info</a></li>             
                                                </ul>                    
                                            <div class="clear"></div>
                                   
                                   </article><!-- further-reading-box -->
                                   
                                   
                                   <a href="retreatlocations#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                       </div><!-- end box -->



				</section><!-- end main-content -->

			</div><!-- end middle-content -->
