
    
 <div class="sticky">

	<a href="application/request" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->



	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>BUG OUT RETREAT: Pros & Cons</h1>                      
					</header>

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>
				
				
		  


					<div class="box">
					
				
				<h3 class="black">CONS OF A BUG OUT RETREAT</h3>
								<p>Often overlooked, there are some significant negatives to buying land and and building a cabin to bug out to.  A few examples:</p>
								
							                    
					<div class="col">
							<h4>High Cost</h4>
							                     
					<div class="col">
							<ul>
								<li>Acreage</li>
								<li>House or Cabin</li>
								<li>Well & Septic</li>
								<li>Perimeter Security</li>
								<li>Underground Bunker</li>
								<li>Off Grid Backup Power</li>
							</ul>
							</div>    
                <div class="col">
							<ul>
								<li>Livestock, Greenhouses</li>
								<li>Secure Home Design</li>
								<li>Internet / Utilities</li>
								<li>Barn / Shop / Storage</li>
								<li>Heating / Cooling / etc</li>
							</ul>
							</div> 

						</div><!-- end col -->

						<div class="col">
							<h4>High Maintenance</h4>
							<div>						
							<ul>
								<li>Cleaning / Maintaining two homes</li>
								<li>Maintaining remote Gardens / Greenhouses</li>
								<li>Caring for animals / livestock</li>
								<li>Doing projects by yourself, on weekends</li>
								<li>After all this work, you're still alone</li>
								
							</ul></div>                      
		
						
						</div><!-- end col -->                      
  

							<div class="clear"></div>
					
                    <p><strong>It's sad, but true:</strong> Many spend hundreds of thousands of dollars on bug out locations that are far from ideal for long term survival.<br>  In some cases, they're nothing more than rural homes with little or no retreat design to them.</strong></p>	
				
                            
                            <div class="red-arrow-title bordered-box">
                                    <span class="red-rounded-arrow">Reality Check</span>
                                    <h4 class="black">
                                         Building a well designed bug out retreat easily costs over <span>$300,000</span> + thousands of hours of work. 
                                    </h4>
                                    
                                    <p class="clear">We've looked at this carefully and have consulted with experts.  If you want underground shelter, off grid power, permaculture landscape, secure/fortified design, and all the equipment that goes with it... it's $300k-$500k to design and build a truly self sufficient bug out retreat.  
                                    On top of that, it's nearly a FULL TIME job to maintain it. <br><br>Most people can neither afford to build a retreat nor have the time to finish/maintain it, so they don't.   <em>Is this you?</em></p>							                            
                        		  
                            </div>

								
						
							<div class="clear"></div>

						</div><!-- end box -->   


						<div class="box">

						

<h3 class="black">Decision Point: Half Ass BOL or Amazing SIP?</h3>
	<p>If you don't have the skills or resources to create a fully stocked bug out retreat for your group (or you don't have a group), one really has to consider the viability of building a separate BOL.
	Instead of a half way, barely stocked, not self reliant bug out location, one might be wiser to invest in sheltering in place (SIP).<br>
	<br>
	We were in this same dilemma for three years, carefully weighing our options.<br>
	This is what led us to start creating <a href="retreats">bug out locations</a> for Mainstream Preppers!
	</p>
	</div>
					</div><!-- end box -->   
                    
                    
                   <div class="box">
                                   <article class="further-reading-box">
                                                <header>
                                                        <h1>Interested? Learn More:</h1>
                                                        <h2>Bug Out Retreat Info:</h2>
                                                </header>
                                                
                                                <ul class="col">
                                                    <li><a href="retreats">What's a Bug Out Retreat?</a></li>
                                                    <li><a href="retreats#why">Why you might want a Retreat</a></li>
                                                    <!--<li><a href="retreatpros" class="currentpage">Bugging Out vs. Shelter in Place</a></li>
                                                    --><li><a href="retreatgroup">Strength in Numbers: Forming a Group</a></li>
                                                   </ul>      
                                                
                                                <ul class="col">
                                                     <li><a href="retreatideal">The Ideal Prepper Retreat</a></li>
                                                    <li><a href="retreatlocations">Potential Retreat Locations</a></li>
                                                    <li><a href="comingsoon" class="fancybox">Retreat Cost Estimate: Build Your Own</a></li>
                                                    <!--<li><a href="retreatfaq">Retreat FAQ</a></li>-->
                                                    <!--<li><a href="retreatmaterial">Are you Mainstream Material?</a></li>
                                                    <li><a href="retreatcosts">Pricing & How to Join</a></li>-->
               					<li><a href="application/request" class="fancybox">>> Inquire for Retreat Group Info</a></li>             
                                                </ul>                    
                                            <div class="clear"></div>
                                   
                                   </article><!-- further-reading-box -->
                                   
                                   <a href="retreatpros#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                       </div><!-- end box -->


				</section><!-- end main-content -->




			</div><!-- end middle-content -->
