
    
 <div class="sticky">

	<a href="application/request" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->


	<div id="main-content" role="main">

		<div class="blue-bg clear">
			<section id="retreats-banner">   

                
        
                            <header>
                                <h1>the Ideal Bug Out Retreat</h1>                      
                            </header>


			

					</section> <!-- end retreats-banner -->           

					<div class="clear"></div>
				</div><!-- end blue-bg -->    


				<section>
                    
	<div class="box">
			<h1 class="large red">THE IDEAL PREPPER RETREAT:</h1>

<div class="box">                       
					<div class="col">
							<h3>Self Sufficient</h3>

							<p>A well planned retreat is not just secure, it's infrastructure systems are <strong>self reliant for extended periods</strong> of time.</p>

							<ul class="decorated">
								<li><a href="retreatpace"  class="fancybox">PACE Plan (4 sources) for Water</a></li>
								<li><a href="retreatpace"  class="fancybox">PACE Plan (4 sources) of Electricity</a></li>
								<li>Long Term Sustainable</li>
								<li>Permaculture driven Food Production</li>
								<li>24x7x365 Security</li>
								<li>No single points of failure</li>
								
							</ul>    
                

						</div><!-- end col -->

						<div class="col">
							<h3>Homestead Amenities</h3>

							<ul class="decorated">
								<li>Large Community Kitchen</a></li>
								<li>Nice Bath/Shower Rooms</a></li>
								<li>Community R&amp;R Space</a></li>
								<li>Private Rooms with ample storage.</a></li>
								<li>Raised Bed Gardens &amp; Greenhouses</a></li>
								<li>Animals / Livestock</a></li>
								<li>RV/Camper Hookups? (some desire this)</li>
								<li>Private Cabins</li>
								<li>Playground for little kids? (jungle gym / tree house)</li>
								<li>Playground for big kids (gun range) - a must have!</li>

							</ul>                      

						</div><!-- end col -->                      

					</div> <!-- end box -->
					
					
					
					
					
					<div class="box">



						<div class="col">
						<h3>Secure by Design</h3>

						<!--<p>Retreats will be designed for security with the following features:</p>-->

							<ul class="decorated">
								<li>Securable Perimeter Zone</li>
								<li>Entry Control Point, Access Denial</li>
								<li>24x7x365 Security</li>
								<li>Hardened exterior with no blind spots</li>
								<li>Access Delay w/ Choke Points</li>
								<li>Listening Posts / <a href="http://en.wikipedia.org/wiki/Observation_post" class="fancybox">Observation Posts</a> (LP/OPs)</li>
								<li>Man Trap Foyer</li>
								<li>Closing (metal) Shutters</li>
								<li>Underground Shelter / "Bunker"</li>
							</ul>      
						</div><!-- end col -->

						<div class="col">
							<h3>On Site Supplies</h3>

							<ul class="decorated">
								<li>1 year food</li>
								<li>3 months living expenses</li>
								<li>Multiple water sources & storage</li>
								<li>Operational gardens/greenhouses</li>
								<li>Chickens for eggs (and for chicken sandwiches)</li>
								<li>Producers of of meat, milk, and manure</li>
								<li>Supplies for use, charity, and barter</li>
								<li>Well stocked EMP Faraday Cage</li>
								<li>Medical and defense supplies</li>
								<li>Communications systems</li>
								
							</ul>                      

						</div><!-- end col -->   

					</div><!-- end box -->
					
					<div class="box"> 
					
					<div class="box"> 
<!--
<h1 class="black">MAINSTREAM PREPPERS AIMS TO ASSIST RETREAT GROUPS IN HAVING  RETREATS AIM TO<br>HAVE <u>ALL</u> OF THE BENEFITS LISTED ABOVE!</h1>
<br><br>-->
							<div class="clear"></div>

						</div><!-- end box -->   


<h3 class="black">What does YOUR ideal retreat look like?</h3>

						<p>Take a minute and <a href="contact" class="fancybox">let us know</a> what you think might be missing.
						</p>		
							
							<div class="clear"></div>

						</div><!-- end box -->   

					
					

   					

   								<div class="box">
                                  <article class="further-reading-box">
                                                <header>
                                                        <h1>Interested? Learn More:</h1>
                                                        <h2>Bug Out Retreat Info:</h2>
                                                </header>
                                                
                                                <ul class="col">
                                                    <li><a href="retreats">What's a Bug Out Retreat?</a></li>
                                                    <li><a href="retreats#why">Why you might want a Retreat</a></li>
                                                    <!--<li><a href="retreatpros">Bugging Out vs. Shelter in Place</a></li>
                                                    --><li><a href="retreatgroup">Strength in Numbers: Forming a Group</a></li>
                                                   </ul>      
                                                
                                                <ul class="col">
                                                     <li><a href="retreatideal" class="currentpage">The Ideal Prepper Retreat</a></li>
                                                    <li><a href="retreatlocations">Potential Retreat Locations</a></li>
                                                    <li><a href="comingsoon" class="fancybox">Retreat Cost Estimate: Build Your Own</a></li>
                                                    <!--<li><a href="retreatfaq">Retreat FAQ</a></li>-->
                                                    <!--<li><a href="retreatmaterial">Are you Mainstream Material?</a></li>
                                                    <li><a href="retreatcosts">Pricing & How to Join</a></li>-->
               					<li><a href="application/request" class="fancybox">>> Inquire for Retreat Group Info</a></li>             
                                                </ul>                    
                                            <div class="clear"></div>
                                   
                                   </article><!-- further-reading-box -->
                                   
                                   
                                   <a href="retreatideal#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                       </div><!-- end box -->


				</section><!-- end main-content -->




			</div><!-- end middle-content -->
