
    
 <div class="sticky">

	<a href="application/request" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->



	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>Retreat Costs & How to Join</h1>                      
					</header>

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>
				
				

					
                    
                    

					<div class="box">
						<div class="clear speech">

							<div class="speech-corner-r"></div>

							<h1>Bug Out Retreat Price Information</h1>

							<div class="col">
								<div class="blue-ribbon">
									<h3>Cost to Join:</h3>
									<h1>$19,600 + $300/mo</h1>
									<p class="notice">- varies by retreat & phase, see application for full details -</p>
								</div><!-- end blue-ribbon -->



								<a href="retreatpricing" class="link-box fancybox">See Price Options / Details</a>
								<a href="contact" class="link-box fancybox">Inquire for Details</a>

							</div><!-- end col -->

							<div class="col">
							
							<h4 class="black">Common Questions</h4>
							
							<ul class="decorated">
								<li><a href="retreatfaq#cheaper">Are there cheaper retreat options?</a> (yes)</li>
								<li><a href="retreatfaq#join">Can just anyone join?</a> (no)</li>
								<li><a href="retreatfaq#single">What if I'm coming alone? Is it cheaper?</a> (yes)</li>
								<li><a href="retreatfaq#relative">Can I bring my mom, or other relative?</a> (maybe)</li>
								<li><a href="retreatfaq#skills">What skills must I acquire to join?</a> (several)</li>
								<li><a href="retreatfaq#private">Can I get a Private Cabin?</a> (yes)</li>								
								<li><a href="retreatfaq#use">How often can I use the retreat?</a> (depends)</li>
								<li><a href="retreatfaq#live">Can I just move in, like as in forever?</a> (not sure)</li>								
								<li><a href="retreatfaq#sell">Can I sell my retreat membership?</a> (yes*)</li>
								<li>What questions do you have?  <a href="contact"  class="fancybox">Submit a Question.</a></li>
								

							</ul>                    
							<a href="retreatfaq" class="link-box">Full Retreat FAQ</a></strong></p>
  
			
							<!--
								<h4 class="red">THE COST OF NOT JOINING?</h4>

								<ul class="decorated">
									<li><a href="#">What does setting up your own retreat cost?</a></li>
									<li><a href="#">Can you achieve our level of preparedness alone?</a></li>
									<li><a href="#">Are you more vulnerable without a group?</a></li>
									
									<li><a href="#">What kinds of events can you not ride out in your home?</a></li>
									<li><a href="#">Do you feel these events are possible, or even likely to occur?</a></li>
									
									<li><a href="#">How much will you learn with us in the next year alone?</a></li>
									<li><a href="#">How much is your family's security &amp; preparedness worth?</a></li>                               
								</ul>
							-->

							</div><!-- end col-->

							<div class="clear"></div>

						</div><!-- end speech -->

					</div><!-- end box -->



					<div class="box">

						<div class="col">

							<a href="comingsoon" class="member-requirement fancybox cboxElement">

								<h3>Member Requirements</h3>
								<span>Click to read the requirements</span>
								<span class="arrow">></span>
							</a>

							<article class="content">
								<header>
									<h3 class="red">Scholarships &amp; Discounts</h3>
								</header>

								<p>Those interested in self sufficiency and preparedness can apply to be involved with our retreats.  However, those with special skills may be considered on a case by case basis for scholarships and discounts.  Some of the skills desired:
									<ul>
										<li>Medical / Paramedic / Nursing</li>
										<li>Security / Defense / Military Background</li>
										<li>Gardening / Greenhouse / Livestock</li>
										<li>Concrete Home Construction</li>
										<li>Preparedness Influence / Audience</li>
									</ul>


									Please describe any expert skills / training you may have when you request your member application.
								</p>
							</article><!-- end content -->

						</div><!-- end col -->


						<div class="col">

							<article id="stepstojoin">
								<header>
									<h3><span class="red">7</span> Steps to join</h3>
								</header>

								<ol class="steps-to-join">
									<li><span>Request Application</span></li>
									<li><span>Submit Retreat App</span></li>
									<li><span>Interviews / Members Vote</span></li>
									<li><span>Member Fee: Placed in Escrow</span></li>
									<li><span>Criminal Background Check</span></li>
									<li><span>Sign Member Agreement</span></li>
									<li><span>Join us for Training, Work, & Fun</span></li>                                                                    
								</ol>

								<a href="application/request" class="blue-rounded-btn animate-hover right fancybox cboxElement">Request Retreat Application</a> 

								<div class="clear"></div>

							</article><!-- end stepstojoin -->                                


						</div><!-- end col -->

						<div class="clear"></div>

					</div><!-- end box -->

			


                  			<div class="box">
                                   <article class="further-reading-box">
                                                <header>
                                                        <h1>Interested? Learn More:</h1>
                                                        <h2>Bug Out Retreat Info:</h2>
                                                </header>
                                                
                                                <ul class="col">
                                                    <li><a href="retreats">What's a Bug Out Retreat?</a></li>
                                                    <li><a href="retreats#why">Why you might want a Retreat</a></li>
                                                    <li><a href="retreatpros">Bugging Out vs. Shelter in Place</a></li>
                                                    <li><a href="retreatgroup">Strength in Numbers: Building a Group</a></li>
                                                    <li><a href="retreatideal">The Ideal Bug Out Retreat</a></li>
                                                    </ul>      
                                                
                                                <ul class="col">
                                                    <li><a href="retreatlocations">Current / Future Locations</a></li>
                                                    <li><a href="comingsoon" class="fancybox">Retreat Cost Estimate: Build Your Own</a></li>
                                                    <li><a href="retreatfaq">Retreat FAQ</a></li>
                                                    <li><a href="retreatmaterial">Are you Mainstream Material?</a></li>
                                                    <li><a href="retreatcosts" class="currentpage">Pricing & How to Join</a></li>                           
                                                </ul>                    
                                            <div class="clear"></div>
                                   
                                   </article><!-- further-reading-box -->
                                   
                                   
                                   <a href="retreatcosts#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                       </div><!-- end box -->




				</section><!-- end main-content -->

			</div><!-- end middle-content -->
