
    
 <div class="sticky">

	<a href="application/request" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->


<div id="main-content" role="main">



	<div class="blue-bg clear">

		<section class="what-is">   

			<div class="wrapper">  

				<header>
					<h1>Retreat FAQ</h1>                     
				</header>                                                                                        


			</div>  <!-- end wrapper -->            

			<div class="ribboncorners"></div>

		</section> <!-- end what-is -->           

		<div class="clear"></div>


	</div><!-- end blue-bg -->    


	<section>




		<div class="box">      
		
<p>The only STUPID question is the one you don't ask.  You've hit this page b/c you've got a question.  If you don't see the answer, <a href="contact" class="fancybox">ask</a>.
</p>		

<header>
    <h1 class="red">COMMON RETREAT QUESTIONS</h1>
     
</header>



							
							<ul class="decorated">
							<a name="cheaper"></a>
								<li><strong>Are there cheaper retreat options?</a></strong></li>
								<p>We have considered less expensive options for bug out retreats.  <a href="retreatpricing"  class="fancybox">More info here</a>.</p>
							<a name="join"></a>	
								<li><strong>Can just anyone join?</a></strong></li>
								<p>Not just anyone can join our retreat.  While the decision on whether to vote you in ultimately falls on the members who join before you, here are some guidelines:<br>
								One of the most important aspects of a retreat is putting together the right group. Here are some thoughts on the type of people we want:
								We want people that work hard, respect others, find solutions, follow rules, seeking to learn, seeking to improve their preparedness, etc.</p>
							<a name="single"></a>
								<li><strong>What if I'm coming alone? Is it cheaper?</a></strong></li>
								<p>Yes, individuals will enter cheaper than couples or families.  Per person fees are still being determined.</p>
							<a name="relative"></a>	
								<li><strong>Can I bring my mom, or other relative?</a> </strong></li>
								<p>If planned in advance - YES.  But, anyone over 17 must be voted in by retreat members, must be involved with training, and must have their minimum supplies just as you do.</p>
							<a name="skills"></a>	
								<li><strong>What skills must I acquire to join?</a> </strong></li>
								<p>We want all retreat members cross trained in basic survival and homesteading.  We'd also like each retreat member to pick an area of specialty - something they enjoy.  The best way to acquire the needed skills is to join our <a href="prepschool">prep school</a> and don't delay before joining the retreat.  You need not be an expert before you join.</p>
							<a name="cabin"></a>	
								<li><strong>Can I get a Private Cabin?</a></strong></li>
								<p>We are definitely fans of retreat options with private rooms.  If you want your own cabin, please consider our <a href="homesteads">homesteading</a> offerings as it might be perfect for you.</p>								
							<a name="use"></a>	
								<li><strong>How often can I use the retreat?</a> </strong></li>
								<p>We don't have everything figured out yet.  This is one of the things we don't yet know.  Retreat members ultimately will decide.</p>
							<a name="live"></a>	
								<li><strong>Can I just move in, like as in forever?</a> </strong></li>								
								<p>We don't have everything figured out yet.  This is one of the things we don't yet know.  Retreat members ultimately will decide.</p>
							<a name="sell"></a>	
								<li><strong>Can I sell my retreat membership?</a> </strong></li>
								<p>In the event you move away or otherwise wish to sell your position in the retreat, we're here to support you.  However, the new member must be voted in by the group, just as you were.  Other details tbd.</p>
							<a name="question"></a>	
								<li><strong>What question do you have?  <a href="contact.html"  class="fancybox">Submit a Question.</a></strong></li>
								

							</ul>                    

			
			
			<div class="clear"></div>
          <a href="retreatfaq#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>

			
		</div> <!-- end box -->

			<div class="box">
                                   <article class="further-reading-box">
                                                <header>
                                                        <h1>Interested? Learn More:</h1>
                                                        <h2>Bug Out Retreat Info:</h2>
                                                </header>
                                                
                                                <ul class="col">
                                                    <li><a href="retreats">What's a Bug Out Retreat?</a></li>
                                                    <li><a href="retreats#why">Why you might want a Retreat</a></li>
                                                    <li><a href="retreatpros">Bugging Out vs. Shelter in Place</a></li>
                                                    <li><a href="retreatgroup">Strength in Numbers: Building a Group</a></li>
                                                    <li><a href="retreatideal">The Ideal Bug Out Retreat</a></li>
                                                    </ul>      
                                                
                                                <ul class="col">
                                                    <li><a href="retreatlocations">Current / Future Locations</a></li>
                                                    <li><a href="comingsoon" class="fancybox">Retreat Cost Estimate: Build Your Own</a></li>
                                                    <li><a href="retreatfaq" class="currentpage">Retreat FAQ</a></li>
                                                    <li><a href="retreatmaterial">Are you Mainstream Material?</a></li>
                                                    <li><a href="retreatcosts">Pricing & How to Join</a></li>                           
                                                </ul>                    
                                            <div class="clear"></div>
                                   
                                   </article><!-- further-reading-box -->
                                   
                                   
                                   <a href="retreatcosts#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                       </div><!-- end box -->

	</section><!-- end main-content -->




</div><!-- end middle-content -->