<article>

<header>
    <h1 class="red">RETREAT PRICING</h1>
     
</header>

							<h1>Which Bug Out Retreat is Right for you?</h1>


								<table width="90%" cellspacing="5" cellpadding="6" border="1" bordercolor="#efefef"><th><tr><td></td><td><strong>BUDGET</strong></td><td><strong>STANDARD</strong></td><td><strong>ADVANCED</strong></td></tr></th>
								<tr><td>Our Cost to Design/Build</td><td>~$200,000</td><td>~$300,000</td><td>~$450,000</td></tr>
								<tr><td>Your Cost to Join</td><td><strong>$9800</strong></td><td><strong>$14,500</strong></td><td><strong>$19,600</strong></td></tr>
								<tr><td># of Acres</td><td>25+</td><td>40+</td><td>60+ Prime</td></tr>
								
								<tr><td>External Construction</td><td>metal</td><td>2x6 wood</td><td>concrete</td></tr>
								<tr><td>Living Space</td><td>barracks style</td><td>dorm rooms</td><td>private rooms</td></tr>
								<tr><td>Passive Solar Design</td><td>no</td><td>no</td><td>yes</td></tr>
								<tr><td>Geothermal Radiant Floors</td><td>no</td><td>no</td><td>yes</td></tr>
								<tr><td>Off Grid Power</td><td>no</td><td>yes</td><td>yes</td></tr>
								<tr><td>Full Time Caretaker</td><td>no</td><td>yes</td><td>yes</td></tr>
								<tr><td>Large Pond & Stream</td><td>no</td><td>yes</td><td>yes</td></tr>
								<tr><td>Underground Shelter / "Bunker"</td><td>no</td><td>yes</td><td>BIG</td></tr>
								</table><br><br>
							    note: All Retreats will have a monthly maintenance fee, but that fee will vary by retreat based upon overhead and planned projects
								<br><br>
								Please, take a moment and tell us <a href="contact"  class="fancybox">which retreat you think will be most popular?</a>.
								<br><br>
								To us, the ~$5,000 between each price break buys ALOT.  But if enough members request one, we'll *consider* a cheaper route.
					<br>
<!--<img src="images/placeholder.jpg" class="image right" />

</article>
