<article>

<header>
    <h1 class="red">PACE Plan</h1>
     
</header>

<p>A Pace Plan consists of a <strong>P</strong>rimary, <strong>A</strong>lternate, <strong>C</strong>ontingency, and <strong>E</strong>mergency source/supply.
<br><br>
<h4>WATER</h4>
Our Retreats use a PACE plan for water via:  <ul class="decorated">          
          <li><strong>P</strong>rimary: Atmospheric Water Generation</li><li><strong>A</strong>lternate: Well Water </li><li><strong>C</strong>ontingency: Rain Water Catchment
          </li><li><strong>E</strong>mergency on site Creek combined with water filtration</li></ul>
          
In Addition, we have <u>thousands of gallons</u> of clean water stored on site.
<br>PLUS, we have a <strong>PACE plan</strong> for <u>water filtration</u>.  We like clean water!
<br><br>

<h4>ELECTRICITY</h4>
Our Retreats use a PACE plan for electricy via:  <ul class="decorated"><li>
<strong>P</strong>rimary: Utility Power</li><li><strong>A</strong>lternate: Off Grid Solar charging immense Battery Power Supply
</li><li><strong>C</strong>ontingency: Natural Gas Generator</li><li><strong>E</strong>mergency: smallish gas generator</li></ul>
We are pre-wired for minimal yet sustainable operation solely from our isolated off grid power system.

<!--<img src="images/placeholder.jpg" class="image right" />

</article>
