
    
 <div class="sticky">

	<a href="application/request" class="fancybox red-button">
		Inquire Today
	</a>
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->



	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>Are you Mainstream Material?</h1>                      
					</header>

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>
				
				
					<div class="box"> 

<h3 class="black">We're Looking for a few good preppers.</h3>
<p>info goes here.</p>
								
				
				
				
										
							<div class="clear"></div>

						</div><!-- end box -->   

	<div class="box">
					
				
			

				<div class="box">                       
					<div class="col">
						<h3>Who we want to join</h3>

							<p>One of the most important aspects of a retreat is putting together the right group.  Here are some thoughts on the type of people we want:</p>

							<ul class="decorated">
								<li>People that want to carry their share of the water</li>
								<li>People that respect others even with they disagree</li>
								<li>People that find solutions instead of focusing on problems</li>
								<li>People that follow simple rules, and lead by example</li>
								<li>People that know it all - your head will not fit</li>
								<li>People that want to learn preparedness - please, come!</li>
								<li>Strict "No Whacko" policy.  No Seriously - we have one.</li>
								</ul>
								<br><br>
								
						</div><!-- end col -->

						<div class="col">
							<h3>Community</h3>
							<p>If truly bad times come, you'll need a team.  We're forming a prepared retreat community <b>NOW</b> so that when that time comes, we're ready.  <br><br><i>"People need to team up with like minded folks in their neighborhoods, or in their church congregations...<br>
							It takes more than one family to survive.  People will have to break out of their shells, team up with like minded folks, and get actively prepared."</i><br>- James Wesley Rawles, SurvivalBlog.com<!-- SGT interview, may 13 2012--></p>                      

						</div><!-- end col -->                      
					</div> <!-- end box -->
					
					
					
								<div class="box">                       
						
						<div class="col">
							<h3>EVERYTHING a Retreat should be</h3><p>Sure, it's got the 4 S's  (secluded, secure, stocked, sufficient).  But more than that, it's a place you'd actually WANT to be.<br><br>If you're like me, when TSHTF and it's time to get serious about survival, I want to be a part of a group like that will be at this retreat.  I want my family to be able to not just survive, but thrive.  I know that if my BOL is just a rural property, I am not self sufficient and I cannot provide security 24x7.<br><br>I'm the perfect customer for this retreat, and that's why I'm building it.  I'm willing to cover a BIG chunk of the cost to build it.  Want to join me?  Even more importantly, want to join our community?  We're seeking applicants.</p>
							</div><!-- end col -->

						<div class="col">
									                       
						<h3>Show me the money</h3>

							<p>In the interest of best use of funds and full honesty, full financial records will be made available to retreat members.  Members also have voting power for use of project and discretionary funds.  Not only will you see the money, you'll help direct where it goes.
							
							<!--<br><br><strong>It's not a top down structure.  It's a member driven model.</strong><br>The people that join the retreat aren't customers, they're members.  It's not our retreat.. it's yours!  Mainstream Preppers is merely the vehicle through which people meet, agreed on a retreat plan and its rules, and come together in a smart way to implement and maintan it.--></p>
							
							
							<br><h4 class="black">THE FIRST COMPATIBILITY TEST:</h4>

							<p>Are you a <a href="prepschool">prep school</a> member?  If not (or not joining today), then today is probably not the right time to be looking at the retreat.<br>A desire to develop self sufficiency skills as well as work as a well trained team are high priorities of retreat members.  The Prep School truly is the tank from which retreat members will be drawn.  Remember, new retreat members are voted in by the existing members.</p>
							
							</div><!-- end col -->                      
					</div> <!-- end box -->
								<div class="clear"></div>


					</div> <!-- end box -->
                    
    
								
						
							<div class="clear"></div>

						</div><!-- end box -->   

    					<div class="box">
                                 <article class="further-reading-box">
                                                <header>
                                                        <h1>Interested? Learn More:</h1>
                                                        <h2>Bug Out Retreat Info:</h2>
                                                </header>
                                                
                                                <ul class="col">
                                                    <li><a href="retreats" class="currentpage">What's a Bug Out Retreat?</a></li>
                                                    <li><a href="retreats#why" class="currentpage">Why you might want a Retreat</a></li>
                                                    <!--<li><a href="retreatpros">Bugging Out vs. Shelter in Place</a></li>
                                                    --><li><a href="retreatgroup">Strength in Numbers: Forming a Group</a></li>
                                                   </ul>      
                                                
                                                <ul class="col">
                                                     <li><a href="retreatideal">The Ideal Prepper Retreat</a></li>
                                                    <li><a href="retreatlocations">Potential Retreat Locations</a></li>
                                                    <li><a href="comingsoon" class="fancybox">Retreat Cost Estimate: Build Your Own</a></li>
                                                    <!--<li><a href="retreatfaq">Retreat FAQ</a></li>-->
                                                    <!--<li><a href="retreatmaterial">Are you Mainstream Material?</a></li>
                                                    <li><a href="retreatcosts">Pricing & How to Join</a></li>-->
               					<li><a href="application/request" class="fancybox">>> Inquire for Retreat Group Info</a></li>             
                                                </ul>                    
                                            <div class="clear"></div>
                                   
                                   </article><!-- further-reading-box -->
                                   
                                   
                                   <a href="retreatmaterial#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                       </div><!-- end box -->


				</section><!-- end main-content -->




			</div><!-- end middle-content -->
