<link href="css/course.css" rel="stylesheet" type="text/css" />
<link href="css/aida.css" rel="stylesheet" type="text/css" />


<script src="js/jquery.bxSlider.min.js" type="text/javascript"></script>

<script type="text/javascript">
  $(document).ready(function(){
	  
    var slider =  $('#slideshow-wrapper').bxSlider({
		auto: true,
		controls: false	
	});
	
	    $('#prev-slide').click(function(){
			slider.goToPreviousSlide();
			return false;
		});
		
	
	    $('#next-slide').click(function(){
			slider.goToNextSlide();
			return false;
		});
	
	
	
  });
</script>


 <div class="sticky">

	
	<a href="selfreliance#signup" class="red-button">
		Sign Up 	<h2 class="free">FREE</h2>
	</a>

    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Facebook</a>
    </div><!-- end social -->
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->






<div id="main-content" role="main" class="aida">


		<div class="blue-bg clear">

					<section  id="self-reliance-banner">   

							<header>
								<h1>Become Self Reliant!</h1>                      
							</header>

							<img src="images/aida/aida-selfReliance-plant.png" title="Become Self Reliant!" class="aida-plant"/>
							<img src="images/aida/aida-selfReliant-bannerribbon.png" title="Become Self Reliant!" class="aida-bannerribbon"/>
 
									

					</section> <!-- end what-is -->           

				

				</div><!-- end blue-bg -->    

				<section>
 
							<div class="box selfreliance-firstbox">
								
									<h1 class="red"><i>There is a growing self reliance movement. </i></h1>
									
									<div class="col">
										<p>Nationwide, Americans are increasing their preparedness and becoming more and more self reliant.  We’re glad you’re a part of it!  Self Reliance involves mastering key areas like food production, homesteading, survival skills, self defense, and forming or joining a local group of like minded people.</p>
										
									</div><!-- end col -->
								
								
									<div class="col">
										<p>More than gear, or even skills, self reliance is a lifestyle.  It takes lots of time and practice, but it’s extremely rewarding. There is much to learn.  </p>
									
										<div class="we-can-help">We Can Help</div>
										
									</div><!-- end col-->
									
									<div class="clear"></div>
							</div><!-- end box-->
							
							
							
							
							<article class="blue-ribbon-top-box">
							
								<header>
									<h1>Mainstream Preppers is the fast track to Self Reliance</h1>
								</header>
								
								<div class="highlight">
								
									<h2 class="huge">
										Our Preparedness School Teaches <i class="red">All Aspects</i> of Self Reliance.
									</h2>
									<br />
									<p>We offer tips, expert training, gear reviews, and the fastest growing self reliance network / community.</p>
									
									<div class="clear"></div>
									
								</div><!-- end brief -->
								
								
								<h1 class="blue question">
									<span class="blue-circle">Q.</span>  What skills do we cover in our “Prep School”?
								</h1>
								
								
								<div class="col">
									<h3 class="text-red-bg">Food Production / Storage</h3>
									
									<ul class="red-bullets">
									
										<li><p>Food Production</p></li>
										<li><p>Permaculture</p></li>
										<li><p>Aquaponics</p></li>
										<li><p>Water Systems</p></li>
										<li><p>Cooking w Food Storage</p></li>
										<li><p>Cooking w Wild Edibles</p></li>
										<li><p>Dehydrating</p></li>
										<li><p>Canning/Preserving</p></li>
										<li><p>DIY Food Storage Tips</p></li>
									</ul>
								
								</div><!-- end col -->
								
								
								<div class="col">
									<h3 class="text-red-bg">Survival</h3>
									
									<ul class="red-bullets">
									
										<li><p>Woods Walkers (Survival 101)</p></li>
										<li><p>Survival (level 2)</p></li>
										<li><p>Survival (level 3)</p></li>
										<li><p>Bugging Out (BoB / BoV)</p></li>
										<li><p>Wilderness Survival (3 day)</p></li>
										<li><p>Wild Edibles</p></li>
										<li><p>Winter Survival</p></li>
										<li><p>Treating Cuts, Bites, Wounds</p></li>
									</ul>
								
								</div><!-- end col -->
								
								<div class="clear"></div>
								
								
								<div class="col">
									<h3 class="text-red-bg">Homesteading</h3>
									
									<ul class="red-bullets">
									
										<li><p>Preparedness Basics</p></li>
										<li><p>Shelter in Place (SIP) Strategies</p></li>
										<li><p>Bug Out Location Consult</p></li>
										<li><p>Off Grid Systems</p></li>
										<li><p>Security / Surveillance</p></li>
										<li><p>Homestead Design</p></li>
										<li><p>Securing your Homestead</p></li>
										<li><p>OPSEC Strategies</p></li>
										<li><p>Medical / Health</p></li>
										<li><p>Forming a Group - Consult</p></li>
									</ul>
								</div><!-- end col -->
								
								
																
								
								<div class="col">
									<h3 class="text-red-bg">Defense / Tactical:</h3>
									
									<ul class="red-bullets">
									
										<li><p>Fitness / Combatives</p></li>
										<li><p>Emergency Medical</p></li>
										<li><p>Self Defense</p></li>
										<li><p>Knife Defense</p></li>
										<li><p>Self Defense Shotgun</p></li>
										<li><p>Beginner Handgun</p></li>
										<li><p>Camouflage and Concealment</p></li>
										<li><p>Evasion (level 1)</p></li>
										<li><p>Tactical Patrolling (level 1)</p></li>
									</ul>
								</div><!-- end col -->
								
								
								<div class="clear"></div>								
								
							</article><!-- end blue-ribbon-top-box-->
							
							
					
				
							<article id="instructors-slideshow" class="instructor-preview ">
							
								<header>
									<h1><img src="images/aida/big-instructor-icon.png" title="MSP instructors" /> Our Instructors are <span class="blue">EXPERTS</span> in Self Reliance</h1>
								</header>
							
								<div id="slideshow-wrapper">
											
											
											<ul class="instructor-list">
											
													<li class="red">
													
														<div class="categories">Preparedness Lifestyle</div>
															
															<div class="instructor-photo">
																<img src="images/course/instructor/joe-fox-big.jpg" title="Joe Fox" />
															</div>
															
															<div class="instructor-name">
																	<p class="co">
																		<img src="images/course/instructor/viking-prepareness-logo.png" title="Viking Prepareness" />
																		Viking Preparedness
																	</p><!-- end co-name-->
																	<p class="fullname">
																		Joe Fox
																	</p>
															</div><!-- end instructor-name -->
															<p class="brief">20 years, Army Special Forces </p>
															
															<ul>
																<li>SERE Instructor </li>
																<li>Survivalist, Prepper, Author, Pastor</li>
																<li>Special Emphasis in Preparedness Lifestyle</li>
															</ul>
															
															<a href="joefox" class="see-bio fancybox">See Instructor&rsquo;s Bio</a>								
													</li>
													
													
											
													<li class="blue">
													
														<div class="categories">Aquaponics</div>
															
															<div class="instructor-photo">
																<img src="images/course/instructor/paul-range-160.jpg" title="Paul Range" />
															</div>
															
															<div class="instructor-name">
																	<p class="co">		Reliance Community Farms
																						</p><!-- end co-name-->
																						<p class="fullname">
																							Dr. Paul Range
																						</p>
																				</div><!-- end instructor-name -->
																				<p class="brief">Innovator & Instructor in Aquaponics</p>
																				<ul>
																				<li>Certified Permaculture Design Specialist</li>
																				<li>Instructor in Permaculture, Water Storage, Canning, Dehydrating, Urban Survival & Emergency Preparedness</li>
																				<li>Homesteader, featured on Doomsday Preppers Season 1</li>
																				</ul>
																				<a href="paulrange" class="fancybox see-bio">See Instructor&rsquo;s Bio</a>								
																		</li>
																		
											</ul><!-- end instructor-list -->
											
											
											
																
											<ul class="instructor-list">	
																		
													<li class="red">
													
														<div class="categories">Economic Knowledge</div>
															
															<div class="instructor-photo">
																<img src="images/course/instructor/bill-still-160.jpg" title="Bill Still" />
															</div>
															
															<div class="instructor-name">
																	<p class="co">
																		
																		The Money Masters
																	</p><!-- end co-name-->
																	<p class="fullname">
																		Bill Still
																	</p>
															</div><!-- end instructor-name -->
															<p class="brief">Expert on the US Monetary System</p>
															
															<ul>
																<li>Best Selling Author of over 20 books</li>
																<li>Award winning documentary writer/director</li>
																<li>Creator of the Money Masters</li>
																<li>Creator of <a href="http://www.secretofoz.com" target="_blank">The Secret of Oz</a></li>
																
																
															</ul>
												
															<a href="billstill" class="fancybox see-bio">See Instructor&rsquo;s Bio</a>								
													</li>
													
													<li class="blue">
													
														<div class="categories">Defensive Skills</div>
																								
															<div class="instructor-photo">
																<img src="images/course/instructor/gary-williams-160.jpg" title="Gary Williams" />
															</div>
															
															<div class="instructor-name">
																	<p class="co">
																		
																		F.I.R.E. Defensive Skills
																	</p><!-- end co-name-->
																	<p class="fullname">
																		Gary Williams
																	</p>
															</div><!-- end instructor-name -->
															<p class="brief">"Train Like You Fight"</p>
															
															<ul>
																<li>Certified law enforcement officer</li>
																<li>Active duty military member</li>
																<li>NRA certified instructor</li>
																<li>20yr martial arts practitioner</li>
					
															</ul>
															
															<a href="garywilliams" class="fancybox see-bio">See Instructor&rsquo;s Bio</a>								
													</li>	
													
											</ul><!-- end instructor-list -->	
													
																
											<ul class="instructor-list">
													
											
													<li class="red">
													
														<div class="categories">Preparedness 101</div>
															
															<div class="instructor-photo">
																<img src="images/course/instructor/zac-bauer-160.jpg" title="Zac Bauer" />
															</div>
															
															<div class="instructor-name">
																	<p class="co">
																		
																		New 2 Torah
																	</p><!-- end co-name-->
																	<p class="fullname">
																		Zachary Bauer
																	</p>
															</div><!-- end instructor-name -->
															<p class="brief">Preparedness 101</p>
															
															<ul>
																<li>Former Infantry Soldier</li>
																<li>Firearms instructor, avid shooter</li>
																<li>Special Emphasis in Emergency Basics</li>
																<li>Learning and Teaching Torah</li>
															</ul>
															
															<a href="zacbauer" class="fancybox see-bio">See Instructor&rsquo;s Bio</a>								
													</li>
													
													
													<li class="blue">
												
																
																<div class="categories">Food Production</div>
																	
																	<div class="instructor-photo">
																		<img title="Marjory Wildcraft" src="images/course/instructor/marjory-wildcraft-160.jpg">
																		
																	</div>
																	
																	<div class="instructor-name">
																			<p class="co">
																				Backyard Food Production 
																			</p><!-- end co-name-->
																			<p class="fullname">
																				Marjory Wildcraft
																			</p>
																	</div><!-- end instructor-name -->
																	
																	<p class="brief">Expert on organic backyard food production</p>
																	<ul>
																		<li>Her manuals used by over 250,000 in 30 countries</li>
																		<li>Passionate about self reliance and sustainable living</li>
																	</ul>
								
																	
																	<a class="fancybox see-bio" href="marjorywildcraft">See Instructor&rsquo;s Bio</a>
																	
																				
													
													</li>	
														
										</ul><!-- end instructor-list -->
												
												
												
										<ul class="instructor-list">
												
																						
												<li class="blue">
													
												
													
														<div class="categories">Tactical Training</div>
																								
															<div class="instructor-photo">
															
																<img title="Invictus AGI" src="images/course/instructor/invictus-160.jpg">
															</div>
															
															<div class="instructor-name">
																	<p class="co">
																	</p><!-- end co-name-->
																	<p class="fullname">
																		Invictus Alliance Group</p>
															</div><!-- end instructor-name -->
															
															
															<p class="brief">Veteran Owned Elite Professional Organization includes:</p>
																		<ul>
																		<li>2 Green Berets &amp; former Delta Force (Tom and Scot)</li>
																		<li>2 Army Special Forces Veterans (Magnus and Jasper)</li><li>1 Marine Scout Sniper Instructor (Grant)</li>
																		</ul>
																		
																		<a class="fancybox see-bio" href="comingsoon">See Instructor Bios</a>	
																					
																		
														</li>	
															
												
										</ul>
												

										
										
											
										</div><!-- end slideshow-wrapper -->
									
										<div class="clear"></div>
										
										
									
										<div id="slider-control">
											<a href="#" id="prev-slide">Prev</a>
											<span>Instructor Preview</span>
											<a href="#" id="next-slide">Next</a>		
										</div>
									
							</article> <!-- end instructors-slideshow-->
							
							
							
							<div class="box" id="msp-prepschool">
							
								<img src="images/aida/msp-prepschool-badge.png" title="MSP Prep School" id="prepschool-badge"/>
								
								<div class="fast-track-self-reliance">
								
											<h1>Our Preparedness School will fast track your path to self reliance!</h1>
											
											<ul>
												<li><p>Network with Preppers<br />
														in your Area</p></li>
												<li><p>Unlimited Access to <b class="red">TOP NOTCH</b> Preparedness Courses</p></li>
												<li><p>Receive Invites to Local<br />
														Training &amp; Events</p></li>
												<li><p>Develop your Preparedness /<br />
														Self Reliance Skill Set!</p></li>
												<li><p>Join Groups with Like<br />
														Minded Preppers</p></li>
		
		
												<li><p>Special Member Discounts &amp; Group Pricing</p></li>
											
											</ul>
									
								
								</div><!-- end fast-track-self-reliace -->
								
								<div class="clear"></div>
								
								
										<a id="signup"></a>
								
								<div class="special-offer-banner">
						
										<h1>Try out our Prep School <b class="red">100% FREE</b> of Charge!</h1>
										<p><i>Free trial lasts 30 days. No catch, no obligation, no credit card required. It's Risk Free!</i></p>							
								
								</div><!-- end special-offer-banner -->
								
								
								
								
								
								
								
								
								
								
								
                               
                       
                                
                                	<section class="box twocol"> 
                                        
                                         
                                          <div class="wide-left">
                                         	  <link href="css/form.css" rel="stylesheet">
                                            
                                       		   <div id="form-message"></div>
                                            
                                                <form action="selfreliance" method="post" id="request-application" class="myform">
                                                
                                                   <div class="form">
                                                
                                               		<div>
                                                       <label for="firstname">First Name:</label>
                                                    	<input name="firstname" id="firstname" type="text" class="firstname required" />
                                                     </div>
                                                     <div>  
                                                             <label for="lastname">Last Name</label>
                                                             <p class="optionallabel">Optional</p>
                                                            <input name="lastname" id="lastname"  type="text"  class="lastname optional" /> 
                                                    </div>  
                                                    <div class="clear"></div>
                                                    <div>  
                                                       <label for="emailaddress">Email Address:</label>
                                                       <input name="emailaddress" id="emailaddress" type="email"  class="required" />     
                                                    </div>
                                                    <div> 
                                                    	<label for="phone">Phone:</label>
                                                         <p class="optionallabel">Optional</p>
                                                        <input name="phone" id="phone" type="number" maxlength="10" class="optional"  />
                                                    </div>
                                                     <div class="clear"></div>
                                                       
                                                     <div>
                                                        <label for="zip" class="clear">Current Zip Code:</label>
                                                        <input name="zip" id="zip" type="text" class="zipcode required" maxlength="10"  />
                                                        </div>
                                                        
                                                        <div class="clear"></div>
                                                       
                                                       <label for="primary">Primary Motivation for Preparedness: </label>
                                                           <select name="primary" id="primary">
                                                                <option>--Select--</option>
                                                                <option>Develop Self Sufficiency Skills</option>
                                                                <option>Job Loss / Bankruptcy</option>
                                                                <option>House Fire / Tornado</option>
                                                                <option>Area Flood / Earthquake / Other Disaster</option>
                                                                <option>Drought / Crop Failures / Food Supply Disruption</option>
                                                                <option>Sustained Power Outage</option>
                                                                <option>Social Unrest / Riots</option>
                                                                <option>Economic Collapse</option>
                                                                <option>Hyperinflation</option>
                                                                <option>Martial Law</option>
                                                                <option>EMP  </option>
                                                                <option>Solar Flare/CME</option>
                                                                <option>Nuclear Power Plant Meltdown</option>
                                                                <option>Nuclear or Biological Warfare</option>
                                                                <option>Terrorist Attack</option>
                                                                <option>Virus / Pandemic</option>
                                                                <option>Zombie Apocalypse (just kidding!)</option>
                                                           </select>
                                                      
                                                      
                                                       
                                                       
                                                       <label for="comments">Questions/Concerns</label>
                                                       <textarea  name="comments" id="comments" class="commments required"></textarea>
                                                                                                         
                                                    
                                                            <div class="clear"></div>
                                               
                                           				 </div><!-- end form -->
                                            
                                            <br />
                                                  
                                                       
                                                    
                                                         
                                                       <input type="submit" class="form-btn" value="BECOME A MEMBER" name="submit" id="submit"/> 
                                                       
                                               
                                               
                                                </form>         
                                                
                                              
												 
                                            </div><!-- end wide-left-->
                                            
                                            
                                            
                                            
                                            <aside class="right-col">
                                            		<a href="contact" class="questions-on-signup fancybox" data-fancybox-type="iframe">
                                                    <b>Questions?</b>
                                                    ASK US</a><br /><br />
                                                    
                                                    
                                                    <h2>ABOUT<br />PREPSCHOOL</h2>
                                                    <ul class="related">
                                                    	<li><a href="instructorpreview">Meet Our Instructors</a></li>
                                                        <li><a href="comingsoon" class="fancybox">Course Schedule</a></li>
                                                                                                           
                                                    
                                                    
                                                    </ul><!-- end related-->
                                                    
                                                    
                                            </aside><!-- end right-col-->
                                            
                                            <div class="clear"></div>

	                                </section><!-- end twocol-->
                                
                                
								
								
								
								
								
							
							
							
							</div><!-- end msp-prepschool -->
							
				


				</section><!-- end main-content -->




			</div><!-- end middle-content -->
