<article>

<header>
    <h1 class="red">Survival, Evasion, Resistance and Escape</h1>
     
</header>


<p>As a Special Forces solider, Joe Fox attended many US and foreign SERE courses and training exercises.  He was certified by the US Army as a SERE instructor and in that capacity trained military and civilian government personnel as well as law enforcement agencies in all aspects of SERE.  Since retiring from the service, he has continued to teach aspects of SERE to civilian personnel as well as federal, state and local law enforcement organizations.</p>

</article>
