
<header>
		<h1 class="red underline">Email a friend about the Prepareness Quiz</h1>
</header>




<section class="form">

  <div id="form-message"></div>

	<form action="application/request" method="post" id="email-friend" class="myform">
   
   
           <label for="emailaddress">Your Friend&rsquo;s Email Address:</label>
           <input name="emailaddress" id="emailaddress" type="email"  class="required" />     
        
           <label for="comments">Your Message</label>
           <textarea  name="comments" id="comments" class="commments"></textarea>

           <input type="submit" class="form-btn " value="Submit" name="submit" id="submit"/>        
   </form>

</section>
