

 <div class="sticky">

	    <a href="network#join" class="cboxElement red-button">Sign Up<h2 class="free">FREE</h2></a>
    
    
    
    <div class="social">
	    <h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
    </div>
    
	<a class="fancybox ask-questions" href="contact">
		Ask a question
    </a>

 </div><!-- end sticky -->

<div id="main-content" role="main">


<!-- temporary      <div class="blue-bg">
                       
                                <section id="home-banner">
                                       
                                       <header class="thriving">
	                                       <h1>Thriving through good times and bad</h1>
                                           <h2>WE&rsquo;RE BUILDING GROUPS OF SKILLED, PREPARED, LIKE-MINDED PEOPLE.</h2>
                                       </header>
                                       
                                       <img src="images/home-banner-2-icons.png" title="Thriving through good times and bad" style="margin-bottom: 20px;" />
                                       
                                       <div id="plan-options">
                                       		<h3>We teach self reliance + strength in numbers.  Join Us!</h3>
                                            
                                            <nav>
                                                    <ul>
                                                    	<li>
                                                                <a href="network">
                                                                	<img src="images/free-flag-vertical-green.png" title="Free to join!" alt="Join our Free Network" class="free-vertical"/>
                                                                    <strong>Join the <br>
																	Network</strong>
                                                                    	Find Prepper Groups
                                                                    </a>
                                                        </li>
                                                    	<li>
                                                                <a href="prepschool">
                                                                    <strong>Get <br>
																			Training</strong>
                                                                 	   We Teach Self Reliance
                                                                    </a>
                                                        </li>
                                                    	<li>
                                                                <a href="retreats">
                                                                    <strong>Join a <br>
																			Retreat</strong>
                                                                    	Strength in Numbers
                                                                    </a>
                                                        </li>
                                                    	<li class="last">
                                                                <a href="paradise">
                                                                    <strong>Prepper&rsquo;s <br>
																			Paradise</strong>
                                                                   	Community Homesteading
                                                                    </a>
                                                        </li>
                                                    
                                                    </ul>
                                            </nav>
                                            

                                       
                                       </div><!-- end plan-options-->
                                        
                                        
                                 </section>
                                        
           
                    </div><!-- end blue-bg -->                     
                                 
<center>
<!--<h2>To be an American</h2><br>-->
<iframe src="http://embed.videodigm.com//bfe9ca6b9e99b7657ee22d03a2b10982" 
width="960" height="600" frameborder="0" scrolling="no" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
<br><br>
<!--<h2>Forward March</h2>-->
<iframe src="http://embed.videodigm.com//2636d889a78280eb9c827a89de5aced1" 
width="960" height="600" frameborder="0" scrolling="no" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
<br><br>
<img src="images/veterans-960.jpg" title="Veterans Day 2012">
</center>
</div><!-- end middle-content -->



<section id="blog" class="box">

	
	<br>
	
                                   <a href="index#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>

	<div class="clear"></div>			
</section><!-- end blog -->

