



	<div id="main-content" role="main">


		<div class="blue-bg clear">

			<section class="what-is">   

				<div class="wrapper">  

					<header>
						<h1>WHY SHOULD YOU PREP?</h1>                      
					</header>
					
					<div class="content">
					<h2>
						I HAVE NO IDEA WHY YOU SHOULD PREP.  BUT HERE'S WHY I DO:</h2>
						<p>There is a common mindset that preparing for rough times is odd or weird.  Let's dive into our mindsets and think logically about our choices.</p>
						
				</div>

				<div class="content">
					<h2 class="question">
						Ever think it's weird to get into preparedness?</h2>
						<p>There is a common mindset that preparing for rough times is odd or weird.  Let's dive into our mindsets and think logically about our choices.</p>
						
				</div>
					

						</div>  <!-- end wrapper -->            

						<div class="ribboncorners"></div>

					</section> <!-- end what-is -->           

					<div class="clear"></div>


				</div><!-- end blue-bg -->    


				<section>
				
				
				

					<div class="box">
						<h1 class="large">
							<span>Ask yourself:</span> 
							Why you do these things?
						</h1>




						<div class="clear speech">
							<div class="speech-corner"></div>

							<div class="col">
								<h4 class="black">Do you do these things? Why?</h4>
								<ul>
									<li>Do you lock your door at night?</li>
									<li>Do you lock your car at the mall?</li>
									<li>Walk down shady alleyways alone at night?</li>
									<li>Do you flash large sums of cash around to strangers?</li>
									<li>Do you have life insurance?</li>
									<li>Do you try to keep extra money in your bank account for unexpected expenses?</li>
									<li>Do you make some life choices (example: diet/exercise) b/c you think about your health in retirement years?</li>
																		
								</ul>

								<h4 class="black">Wouldn't it be weird if...</h4>
								<ul>
									<li>you lived in an earthquake zone and had NO plan?</li>
									<li>you learned a hurricane was fast approaching and did NOTHING to prepare or evacuate?</li>
									<li>a wildfire was approaching your home and you didn't pack a single thing in case you had to leave?</li>
									<li>you planned to hike all day, but didn't bother to pack a drink?</li>
									<li>you knew you faced a long drive but did not bother to check your fuel level?</li>
									<li>your teenage child was going to an unfamiliar place and you DIDN'T say "be careful" as they left?</li>
								</ul>
								
								<h4 class="black">If you agree with ANY of the above, you like to be prepared.</h4>
								<p>Preparedness at its basic level is taking steps within your ability to mitigate risk and thrive through possible circumstances.
								<br><br>
								<h4>Ultimately, we choose to rely upon steps we can take ourselves to limit the downside risk if certain events occur.
								We elect not to "take the chance" that everything will work, we decide we want to be ready for situations with consequences.<br><br>WE PREPARE.</h4>
								
								
							</div><!-- end col-->

							<div class="col">
								<h4 class="black">Preppers prepare for more possible situations than the "normal" person.</h4>
								<p>Preppers think critically about possible events that while may have a low probability, carry a high consequence.
								They assess the risk they present and decide what measures (if any) they should take to mitigate that risk.
								Preppers take these steps on their own, as their goal is to be self reliant and therefore more independent and secure than those that do not prepare for such situations.
								</p>
								<h4 class="black">Serious Threats We Face Today:</h4>
								<ul>
									<li>Economic Hardship</li>
									<li>Job Loss</li>
									<li>Medical Emergency</li>
									<li>Violent Crime</li>
									<li>Home Invasion</li>
									<li>Localized Power Outage</li>
									<li>Widespread Power Outage</li>
									<li>Prolonged Power Outage</li>
									<li>Spike in Fuel Prices</li>
									<li>Temporary gaps in availability of supplies</li>
									<li>Backup plans in case of unexpected situation</li>
									<li>Redundancies in case of equipment or service failures</li>
									
								</ul>

							</div><!-- end col-->

							<div class="clear"></div>

						</div><!-- end speech -->
						
						
					</div><!-- end box -->   
					
					<div class="box">
						<h2 class="question">
						Will you look WEIRD if you increase your preparedness?</h2>
						<p>Shows like Doomsday Preppers and others have sensationalized the most extreme and sometimes obscure viewpoints about preparedness.  Some people picture preppers as hoarders or people that live without running water or electricity.  In fact, most preppers are people who are not willing to chance NOT having running water and electricity, and willing to become self reliant to ensure their lifestyle!</p>
						</div><!-- end box -->  
							<div class="clear"></div>
					
					<div class="box">
					
					<h4>If you think about it...</h4>
						<h1 class="large">
							<span>It's Weird</span> 
							if you DON'T want to<br>BE PREPARED!
						</h1>
						
					<div class="clear"></div>
                    <a href="whyprepare#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>
                     	

					</div><!-- end box -->   
					
					<div class="box">                       


			<h3>5 years ago, I had it all figured out.</h3>
<ul class="decorated">
				<li>I had enough friends.</li><li>
I had enough money.</li><li>
I had cool toys.</li><li>
I had a house and wife.</li><li>
I had enough God in my life.</li></ul>
<p>I was working out the details of building a custom house 3x more expensive than the house I had at the time.  It was going to be sweet!  My favorite part was the 5 car garage and the lot I had picked out - surrounded by $500,000+ homes.
</p>
<h4>The only thing I didn't have was any sense of what was coming.</h4>

<h3>Then, by mistake... I took the Red Pill</h3>
<p>My life priorities changed almost in an instant when I found out I was going to be a dad.
I believe my exact quote was "I'm going to need a shotgun".  And with that, my journey began.
<br /><br />
I decided to read about the housing market, to make sure it was a good idea to build this house with little money down.  I thought to myself "what's a housing bubble?"
<br /><br />
So, I started researching money.  I figured out just how much debt we were in (iousa), and I learned a whole lot about the monetary system (money changers).
<br /><br />


<i>
This of course led me to politics, where I basically new much was messed up.
The "Red" team talked a good game, "humble foreign policy, peace, prosperity, liberty" but I was really seeing that absolutely none of it was true!  What Hypocrites!
<br /><br />
I tried switching to the "Blue" team, figuring they must have had it right all along.
All I learned is that they want to penalize success success, limited freedom, support poverty, and all the while they endorse huge spending.  They support an agenda of huge government, huge debt, redistribution of wealth, and limited freedom.
<br /><br />
<h3>I was feeling pretty sold out!</h3>
<h5>Does anyone stand for what I value?</h5>

A lightbulb went off when I watched a video in which a candidate that I watched in two debates and didn't even glance at articulated everything I now believed in just a few minutes.  here's that video:  http://www.youtube.com/watch?v=FG2PUZoukfA
<br /><br />
I bought his books, and read some other books as well. (here's my book list).
<br /><br />
I arrived at my current view:
<ul><li>The monetary system is downright evil.  It is the biggest transfer of wealth scheme imaginable, and supported by both R's and D's.  99% of the public is ignorant on this issue.  Through inflation and then deflation, the average person is wiped out. 
</li><li>Both parties are part of a larger agenda that grows government and slowly erodes our liberties.  Both sides believe if they just had more power, they could use laws, taxes, and regulations to fix all our problems.  They fail to see that big government is the problem.
</li><li>Virtually nobody believes in the country as it was founded anymore.</li></ul>
</i>



<h3>Just then, my journey turned for the worse.</h3>

<h5>The more I learned, the more I came to a realization:</h5>
<h3>We're headed for a total economic collapse!</h3>
We're racing along in our lives without any vision of where we're going as a nation.  
Meanwhile, we're on course for a total economic collapse.  

What's worse is that our moral compass has been lost.
I fear Americans are no longer a people who will make the sacrifices to fight through adversity and come out stronger for it.

<br /><br />
My fear is that when the true collapse comes, we'll be drowning in debt and problems and we'll happily grab ahold of any snake to stay afloat.   That snake has been part of the plan all along and will mark the end of the age for America.
<br /><br />
If you don't yet believe we're headed for an economic collapse, consider this: <a href="#">ADD LINK to PAGE HERE.</a>

<h3>Clinging to God and Guns</h3>

<h5>For a year or two, I deceived myself, thinking that this would protect me:</h5>
<ul class="decorated"><li>
shotgun</li><li>
handgun with concealed carry permit</li><li>
decent training and many boxes of ammo</li><li>
silver coins for barter</li><li>
gold coins for preserving wealth</li><li>
a few weeks of food</li><li>
maybe a garden and a neighborhood watch program</li></ul>

So, I was a very low level prepper for a few years.<br />
But as events have unfolded, and I've kept learning along the way, I now understand:

<h3>A stack of coins, a few guns and a garden will NOT protect us from what's coming.</h3>


<p>Once I realized that we're headed for a full scale collapse, alot of my options seemed flawed.</p>

</div><!-- end box -->
<div class="box">  

			<div class="col">
				<h3>Suburban Prepper</h3>

				<p>Here's the reason stockpiles in my suburban house won't work:</p>

				<ul>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>

				</ul>   
				<h4>Verdict: Only works for short term scenarios.</h4>                   
			</div><!-- end col -->
			
			<div class="col">
				<h3>Bug Out to Country</h3>

				<p>Here's the reason grabbing my bug out bag and headed for the forest won't work:</p>

				<ul>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
				</ul>   
				<h4>Verdict: Risky for a family</h4>                   
			</div><!-- end col -->

		</div> <!-- end box -->
<div class="box">  

			<div class="col">
				<h3>The Lone Wolf Approach</h3>

				<p>Here's the reason setting up my little homestead in the boonies won't work:</p>

				<ul>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>

				</ul>   
				<h4>Verdict: A sitting duck target</h4>                   
			</div><!-- end col -->
			
			<div class="col">
				<h3>The Lone Expat Approach</h3>

				<p>Here's the reason just moving to Central or South America won't work:</p>

				<ul>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
					<li><a href="overlay.html"  class="iframe cboxElement">coming soon</a></li>
				</ul>   
				<h4>Verdict: Risky for a family</h4>                   
			</div><!-- end col -->
			
			
			<div class="clear"></div>
          <a href="whyprepare#topbanner" class="back-to-top"><span>Go</span> Back to Top</a>

		</div> <!-- end box -->



 					




				</section><!-- end main-content -->




			</div><!-- end middle-content -->
