<article>

<header>
    <h1 class="red">Zachary Bauer &mdash; New 2 Torah</h1>
     
</header>


	<p>After highschool, Zachary Bauer joined the Army infantry where he served during his enlistment in a mechanized infantry battalion stationed in Germany.  After the Army, and then college, he came home and began his involvement in 2nd Amendment politics volunteering and serving a former U.S. Senate candidate, and as campaign manager for a U.S. Congressional candidate.
</p><p>
During this time he founded <a href="http://www.MissouriCarry.com" target="_blank">MissouriCarry.com</a>, a website dedicated to bringing and passing a Concealed Carry law to the state of Missouri. Zachary served 2 terms on the board of directors for his state NRA affiliate, The Missouri Sport Shooting Assocation. 
</p><p>
While remaining deeply entrenched with Missouri and national politics, Zac stayed dedicated to training in survival tactics and weapons training. He has over 80 hours of classroom training alone with organizations such as the American Assocation of Certified Firearms Instructors (AACFI), The Defensive Shooting Academy, (TDSA) and many others. 
</p><p>
Zac currently goes out of his way to instruct others on the beginning steps to establish an emergency preparedness plan and what basics are needed to survive a disaster situation.  He usually does this for faith based institutions and in bible study classes interested in what it takes to get started in the prepper mindset.
</p><p>
Aside from Emergency Preparedness, Zachary also instructs and teaches on the Torah and Bible topics at New2Torah.com.  He and his wife live on an intentional homestead community dedicated to a self sufficient lifestyle deep within the Missouri Ozarks.
</article>
