<header>
		<h1 class="red underline">Network Signup</h1>
</header>



<section class="form">

  <div id="form-message"></div>

	<form action="newsletter/signup" method="post" id="newsletter-form">
   
           <label for="firstname">First Name: (optional)</label>
   		<input name="firstname" id="firstname" type="text" class="firstname"  />
   
           <label for="emailaddress">Email Address:</label>
           <input name="emailaddress" id="emailaddress" type="email"  class="required" />    
		   
		   <label for="zipcode">Zip Code: (NEVER shared.  ONLY used to notify you of events in your area.)</label>
           <input name="zipcode" id="zipcode" type="text" class="required" />    


           <input type="submit" class="form-btn " value="Submit" name="submit" />        
   </form>

</section>
