<div class="sticky">

	<a href="prepschool" class="fancybox red-button">
		Get Prepared
	</a>

	<div class="social">
		<h5>Share this:</h5>
		<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
		<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
	</div><!-- end social -->

	<a class="fancybox ask-questions" href="contact">
		Ask a question
	</a>

</div><!-- end sticky -->





<script src="js/quiz.js"></script>
<script type="text/javascript" charset="utf-8">
	// handle hidden checkbox
	$(function() {
		$('a.bool').click(function() {
			value = $(this).hasClass('yes')
			checkbox = $(this).parent().find('input.yes-no-checkbox')
			
			checkbox[0].checked = value
		})
	})
</script>

<link href="css/quiz.css" rel="stylesheet">


<div id="main-content" role="main">

	<div class="blue-bg clear">

		<section class="are-you-prepared-title">   
			<div class="wrapper">  
				<header>
					<h1>Are You Prepared?</h1>   
					<a href="aboutquiz">About This Quiz</a>                   
				</header>


				<p class="clear">You understand <a href="aboutquiz">why you need to prepare</a>. So you gathered some food, water, planned out a location, and setup an emergency plan for your family. <b>YOU THINK YOU ARE PREPARED, BUT ARE YOU?</b>  Do you have what it takes to survive a major economic collapse, natural disaster, social unrest, and <a href="aboutquiz">many other situations</a>? 
				</p>

			</div>  <!-- end wrapper -->  
			<div class="ribboncorners"></div>
		</section> <!-- end are-you-prepared -->           

		<div class="clear"></div>
	</div><!-- end blue-bg -->    


	<section class="quiz">



		<form action="" method="post">
			<div class="box" style="padding-bottom:0;">
				<b style="padding-left: 15px;">To Gauge your preparedness, take the Prepardness Quiz below!</b>
			</div>
			
			
			<? foreach ($this->quizSetup['sections'] as $section): ?>
				<article class="box quiz-section">
					<header>
						<h1><?= $section['title'] ?></h1>
						
						<? if (!empty($section['description'])): ?>
							<p><?= $section['description'] ?></p>
						<? else: ?>
							<p class="clear"></p>
						<? endif ?>
					</header>   	

					<ul>
						<? foreach ($section['questions'] as $question): ?>
							<? if ($question['type'] == 'heading'): ?>
								<li class="scenario">
									<p>
										<b>
											<?= $question['question'] ?>
										</b>
									</p>
								</li>
								<? continue ?>
							<? endif ?>

							<li>
								<p><?= $question['question'] ?></p>
							
								<? if ($question['type'] == 'bool'): ?>
							
									<div class="yes-no">
										<a href="#" class="bool yes <? if ($question['default'] == 'yes')  echo 'selected' ?>">Yes</a>
										<a href="#" class="bool no <? if ($question['default'] == 'no')  echo 'selected' ?>">No</a>

										<input type="checkbox" class="yes-no-checkbox" name="<?= $question['key'] ?>" id="<?= $question['key'] ?>" style="display: none" />
									</div><!-- end yes-no -->
									
							
								<? elseif ($question['type'] == 'inputs'): ?>
									<div class="inputs">
								
										<? foreach ($question['inputs'] as $input): ?>
											<input type="number" name="<?= $input['key'] ?>" id="<?= $input['key'] ?>" />
											<label for="<?= $input['key'] ?>"><?= $input['label'] ?></label>  &nbsp;
										<? endforeach ?>

									</div>
								<? endif ?>
							</li>
						<? endforeach ?>

						</ul>

						<div class="clear"></div>


					</article><!-- end  quiz-section -->
			<? endforeach ?>


			<div class="box submit-quiz clear">
				<h1>How&rsquo;d You DO?</h1>
				<input type="submit" value="see YOUR results" />
			</div><!-- end submit-quiz-->

			<div class="clear"></div>

		</form>

	</section><!-- end quiz -->




</div><!-- end main-content -->
