<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

	<head>
		<base href="<?= $this->baseUrl ?>" />
		
		<meta charset="utf-8">

		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><?= $this->metaTitle ?></title>

		<link rel="shortcut icon" href="favicon.ico" />

		<meta name="title" content="<?= $this->metaTitle ?>">
		<meta name="keywords" content="<?= $this->metaKeywords ?>">
		<meta name="description" content="<?= $this->metaDescription ?>">

		<meta name="viewport" content="width=device-width">

		<link rel="stylesheet" href="css/base.css">
		<link rel="stylesheet" href="css/style.css">
		<link rel="stylesheet" href="css/inside.css" />
		<link rel="stylesheet" type="text/css" href="css/jquery.fancybox.css" media="screen" />

		<script src="js/libs/modernizr-2.5.3.min.js"></script>


		<script type="text/javascript">

		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-31234979-3']);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

			</script>
		

	</head>



	<body>
		<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->



		<div id="trial">
			Pre-Sale until July 4th, 2012.  <a href="blaze">Blaze the Trail with Us</a>  
		</div><!-- end trial -->




		<header id="topbanner" role="banner">
			<div class="content">
				<nav id="top-links">
					<ul>
						<li><a href="about">About</a></li>
						<li><a href="blog">Blog</a></li>					
						<!--<li><a href="newsletter/signup" data-fancybox-type="iframe" class="fancybox">About</a></li>
						<li><a href="application/request" data-fancybox-type="iframe" class="fancybox">Application</a></li>-->
						<li><a href="faq">FAQ</a></li>
						<li><a href="overlay" data-fancybox-type="iframe" class="fancybox-small">(overlay)</a></li>      
						<li><a href="contact" data-fancybox-type="iframe" class="fancybox">Contact</a></li>                       
					</ul><!-- end top-links -->
				</nav><!-- end top-links -->


				<a href="index.php" id="logo">
					<img src="images/mainstream-preppers-logo.png" title="Mainstreatm Preppers" />
				</a>





				<?php //$currentFile = basename($_SERVER['REQUEST_URI'], ".php");  ?>


				<?php if (!empty($this->showHomepageContentInHeader)): //if ($currentFile == 'index'): ?>             

					<!-- ################ home page content ############### -->   
					<p class="intro">
						Mainstream Preppers develops <b>local groups</b> of preppers for the purposes of <b>skill development, bug out retreats, and homesteading</b>.</p>
						<p class="intro">
							Is your goal self reliance, yet you recognize there is strength in a well trained group?  You just might be the next Mainstream Prepper. 
						</p>

					<?php else: ?>        
						<!-- ################ all other pages ############### -->            
						<nav id="main-nav" role="navigation">
							<ul>
								<li><a href="index.php">Home</a></li>
								<li><a href="prepschool">Prep School</a></li>
								<li><a href="retreats">Retreats</a></li>
								<li><a href="homesteads">Homesteading</a></li>
								<li><a href="blaze">May Special</a></li>
								<!--
								<li><a href="application/request"  data-fancybox-type="iframe" class="fancybox">About</a></li>
								<li><a href="newsletter.html"  data-fancybox-type="iframe" class="fancybox-small">FAQ </a></li>
								<li><a href="customers">Featured Customers</a></li>								
								<li><a href="#">Contact </a></li>
								<li><a href="#">News</a></li>
								<li><a href="#">EXECUTIVE PEPPERS</a></li>-->
							</ul>
						</nav>

					<?php endif; ?>


					<ul class="right-bullet">
						<li><a href="quiz">Take the Preparedness Quiz</a></li>
						<li><a href="whyprepare">Why Should You Prep?</a></li>
						<li><a href="newsletter/signup" data-fancybox-type="iframe" class="free-sms fancybox">Join the Network<span>FREE</span></a></li>
					</ul> <!-- end right-bullet -->

				</div><!-- end content -->


			</header><!-- end topbanner -->



			<?php echo $this->layout()->content; ?>



			<section id="privacy">

				<header>
					<h3>Privacy &amp; Safety</h3>
				</header>

				<nav>
					<ul>
						<li><a href="#">Privacy <br>Policy</a></li>
						<li><a href="#">Confidentiality <br>Agreement</a></li>
						<li><a href="#">Security <br>Agreement</a></li>
						<li><a href="#">Safety <br>Requirements</a></li>
						<li class="last"><a href="#">Release <br>Waiver</a></li>
					</ul>

				</nav>


			</section><!-- end privacy -->


			<footer id="main-footer">
				<small>&copy; 2012 Mainstream Preppers, LLC. All Rights Reserved.</small>
				<div class="nps"><a href="http://www.netprofitservices.com" target="_blank"><img src="images/nps-logo.gif" title="Web site by Net Profit Services, Inc." /></a> | <a href="mailto:info@netprofitservices.com" title="">Send us a note</a></div>

			</footer><!-- end main-footer -->




			<script src="js/libs/jquery-1.7.1.min.js"></script>
			<script src="js/libs/jquery-ui-1.8.19.custom.min.js"></script>

			<script type="text/javascript" src="js/jquery.fancybox.pack.js"></script>

			<script src="js/plugins.js"></script>
			<script src="js/script.js"></script>

		</body>
	</html>