
  <h1>We are sorry. An error occurred. Please try again or <a href="/contact">contact us</a>.</h1>

<? if (true): ?>
  <h2><? echo $this->message ?></h2>

  <? if (isset($this->exception)): ?>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><? echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><? echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <? endif ?>
<? endif ?>