

<!-- <div class="sticky">

<a href="contact" class="fancybox red-button">
Inquire Today
</a-->
<!--  
<div class="social">
<h5>Share this:</h5>
<a href="https://twitter.com/#!/PrepperSkills" class="twitter">Twitter</a>
<a href="http://www.facebook.com/MainstreamPreppers" class="facebook">Follow us on Facebook</a>
</div>end social -->

<!--a class="fancybox ask-questions" href="contact">
Ask a question
</a>

</div> end sticky -->



<div id="main-content" role="main">

	<div id="free-trial-banner" class="blue-bg clear">

		<section >   

			<header>
				<h1>Free Prep School Membership</h1>                      
				<h2>Free 45 Day Trial. No Credit Card Required.  Limited to first 500 Members</h2>
			</header>

			<div class="enroll-today">Enroll Today!</div>

		</section> <!-- end free-trial-banner -->           

		<div class="clear"></div>
	</div><!-- end blue-bg -->    


	<section>









		<section class="box twocol"> 


			<div class="wide-left">
				<link href="css/form.css" rel="stylesheet">



				<form action="expospecial" method="post" id="request-application" class="myform">

					<div class="form">

						<div>
							<label for="firstname">First Name:</label>
							<input name="firstname" id="firstname" type="text" class="firstname required" />
						</div>
						<div>  
							<label for="lastname">Last Name</label>
							<p class="optionallabel">Optional</p>
							<input name="lastname" id="lastname"  type="text"  class="lastname optional" /> 
						</div>  
						<div class="clear"></div>
						<div>  
							<label for="emailaddress">Email Address:</label>
							<input name="emailaddress" id="emailaddress" type="email"  class="required" />     
						</div>
						<div> 
							<label for="phone">Phone:</label>
							<p class="optionallabel">Optional</p>
							<input name="phone" id="phone" type="number" maxlength="10" class="optional"  />
						</div>
						<div class="clear"></div>

						<div>
							<label for="zip" class="clear">Current Zip Code:</label>
							<input name="zip" id="zip" type="text" class="zipcode required" maxlength="10"  />
						</div>

						<div class="clear"></div>
						
						<? if (false): ?>
						<label for="primary">Primary Motivation for Preparedness: </label>
						<select name="primary" id="primary">
							<option>--Select--</option>
							<option>Develop Self Sufficiency Skills</option>
							<option>Job Loss / Bankruptcy</option>
							<option>House Fire / Tornado</option>
							<option>Area Flood / Earthquake / Other Disaster</option>
							<option>Drought / Crop Failures / Food Supply Disruption</option>
							<option>Sustained Power Outage</option>
							<option>Social Unrest / Riots</option>
							<option>Economic Collapse</option>
							<option>Hyperinflation</option>
							<option>Martial Law</option>
							<option>EMP  </option>
							<option>Solar Flare/CME</option>
							<option>Nuclear Power Plant Meltdown</option>
							<option>Nuclear or Biological Warfare</option>
							<option>Terrorist Attack</option>
							<option>Virus / Pandemic</option>
							<option>Zombie Apocalypse (just kidding!)</option>
						</select>
						
						<? else: ?>
							<input type="hidden" name="primary" value="expo" id="primary" />
						<? endif ?>
						<? /*
						<label>Secondary Motivations(s) for Preparedness: </label> 
						<div class="checkboxes">
							<? $options = array(
								'Develop Self Sufficiency Skills',
								'Job Loss / Bankruptcy',
								'House Fire / Tornado',
								'Area Flood / Earthquake / Other Disaster',
								'Drought / Crop Failures / Food Supply Disruption',
								'Sustained Power Outage',
								'Social Unrest / Riots',
								'Economic Collapse',
								'Hyperinflation',
								'Martial Law',
								'EMP',
								'Solar Flare/CME',
								'Nuclear Power Plant Meltdown',
								'Nuclear or Biological Warfare',
								'Terrorist Attack',
								'Virus / Pandemic',
								'Zombie Apocalypse (just kidding!)',
								'Simpler Lifestyle',
								'Like Minded Friends/Neighbors'
							); ?>

							<? $i = 1 ?>
							<? foreach ($options as $option): ?>
							<div>
								<input name="secondary[]" id="secondary-<?= $i ?>" value="<?= $option ?>" type="checkbox" />
								<label for="secondary-<?= $i++ ?>"><?= $option ?></label>
							</div>
						<? endforeach ?>
					</div><!-- end checkboxes -->           
					*/ ?>
					
					
					<label for="comments">Questions/Concerns</label>
					<textarea  name="comments" id="comments" class="commments required"></textarea>


					<div class="clear"></div>

				</div><!-- end form -->

				<br />



				<input type="submit" class="form-btn" value="BECOME A MEMBER" name="submit" id="submit"/> 



			</form>         
			
			<div id="form-message"></div>
			

		</div><!-- end wide-left-->




		<aside class="right-col">
			<a href="contact" class="questions-on-signup fancybox" data-fancybox-type="iframe">
				<b>Questions?</b>
				ASK US</a><br /><br />


				<h2>ABOUT<br />
					PREPSCHOOL</h2>
					<ul class="related">
						<li><a href="instructorpreview">Meet Our Instructors</a></li>
						<li><a href="comingsoon" class="fancybox">Course Schedule</a></li>



					</ul><!-- end related-->


				</aside><!-- end right-col-->

				<div class="clear"></div>

			</section><!-- end twocol-->












		</section><!-- end section -->




	</div><!-- end main-content -->
